Rename Audacity to Tenacity
tenacityteam/tenacity-legacy pull request #144
Opened 2021-07-08 01:31 UTC by ajayyy

- [x] The code in this pull request is licensed under "GPLv2 or any later version"
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

2021-07-08 01:52 UTC, ajayyy commented
Moving out other rename stuff to this RFC: https://github.com/tenacityteam/tenacity/issues/145

2021-07-08 02:08 UTC, ajayyy commented
Windows one works, can someone test the mac build?

2021-07-08 02:14 UTC, caughtquick commented
> It builds on Windows for me, can someone test the mac build. Is the .app file named properly?

Let's just wait for it to build shouldn't we? And see from there?

2021-07-08 02:17 UTC, ajayyy commented
> Let's just wait for it to build shouldn't we? And see from there?

Even if it builds, I want to confirm it runs properly

2021-07-08 02:18 UTC, caughtquick commented
> 
> 
> > Let's just wait for it to build shouldn't we? And see from there?
> 
> 
> 
> Even if it builds, I want to confirm it runs properly

I have a MacBook but I do need to install MacOS on it, I'll do that sometime next week so I can test.

2021-07-08 03:21 UTC, logo4poop commented
Testing on mac now!

2021-07-08 03:23 UTC, ajayyy commented
Just pushed more changes :) I think it might have been installing to the Audacity folder still before

2021-07-08 03:38 UTC, logo4poop commented
![image](https://user-images.githubusercontent.com/24994565/124858625-6a762b00-df7c-11eb-8984-1dc999bf27ba.png)
Builds fine, although I cannot run it like normal. I have to use the terminal.

2021-07-08 04:43 UTC, Martexte commented
![image](https://user-images.githubusercontent.com/54096565/124863519-c62acd80-dfe9-11eb-9194-4264034a1e81.png)

The binary built as intended, and ran just fine. Tested on Arch Linux.

2021-07-08 09:39 UTC, fitojb commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Extra “Â” character in here, is it intended?

2021-07-08 09:41 UTC, Semisol commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Unicode issues probably.

2021-07-08 14:38 UTC, ajayyy commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Where is this character? I only see a copyright symbol

2021-07-08 14:51 UTC, ajayyy commented
Bit really sure what's up with the Linux build failing due to dependencies. Help is appreciated

2021-07-08 14:53 UTC, falkTX commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
I dont see any extra characters either, this is fine.

2021-07-08 14:56 UTC, ajayyy commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
I see it when viewing the full diff on GitHub

2021-07-08 14:56 UTC, falkTX commented on win/audacity.rc
> +            VALUE "LegalCopyright", "Copyright © 1999-2021. All rights reserved."
One utf8 letter too much here

> Copyright Â© 1999-2021

2021-07-08 14:57 UTC, falkTX commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Also here?

> AudacityÂ® is a registered...

2021-07-08 14:57 UTC, falkTX commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
same, I "unresolved" the convo here.
I think this file got messed up.

2021-07-08 14:59 UTC, falkTX commented
Shouldn't `tenacity.desktop` have been renamed in this PR?

2021-07-08 15:00 UTC, falkTX commented
Sorry, fat fingers, it is too easy to close the close button by mistake!

2021-07-08 16:28 UTC, ajayyy commented
> Shouldn't `tenacity.desktop` have been renamed in this PR?

No

2021-07-08 16:43 UTC, ajayyy commented
@logo4poop I think the Mac app might work now

2021-07-08 21:51 UTC, emabrey commented on win/audacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
https://stackoverflow.com/questions/42966981/special-character-%C3%82-inserted-before-copyright-symbol

2021-07-09 03:19 UTC, Martexte commented
> Not really sure what's up with the Linux build failing due to dependencies. Help is appreciated

What error messages did you get? What dependencies were mentioned?

2021-07-09 03:24 UTC, ajayyy commented
@MalevolentStrix Seen the GitHub actions build https://github.com/tenacityteam/tenacity/pull/144/checks?check_run_id=3021316930 . I think a project name is incorrect somewhere, causing the dependencies to be put in the wrong place.

2021-07-09 07:20 UTC, falkTX commented
It might be good to tackle this with renaming little by little instead of all at once.
So we have a more clear idea where it fails.
Would take a long time because of how long the builds are.. :thinking:

2021-07-11 16:18 UTC, Semisol commented
Small reminder: Please sign off your commits. Do this by:
```
git rebase --signoff HEAD~<amount of commits not signed off>
git push --force-with-lease
```

2021-07-11 21:48 UTC, Be-ing commented on win/audacity.rc
>          BLOCK "040904b0"
rename this file to tenacity.rc

2021-07-12 14:55 UTC, ajayyy commented on win/audacity.rc
>          BLOCK "040904b0"
I was trying to keep as many file names and only change the files they output to. I guess for a small file like this, it may be worth it though. What do you think?

2021-07-12 16:41 UTC, ajayyy commented
I switched the encoding back, but the extra symbols seem to be gone

2021-07-12 22:09 UTC, Be-ing commented on win/audacity.rc
>          BLOCK "040904b0"
Yes, we should not have anything called `audacity` anywhere in this repository other than crediting the original authors of the code.

2021-07-13 14:41 UTC, Corsaka commented
@ajayyy I was unaware of the existence of a windows installer. Is it not just a build like the rest?

2021-07-13 15:14 UTC, ajayyy commented
@Corsaka Yes, it seems you just need to run a cmake build on Windows with InnoSetup installed. I have done this, but it still is not appearing in my build folder. I guess I need to try again on master to see if it is the right set up at least.

2021-07-14 10:51 UTC, fossdd requested changes

2021-07-14 10:51 UTC, fossdd commented on CHANGELOG.txt
> +   * (macOS) Tenacity.app now has its resources inside it rather than in a
Can you maybe remove the CHANGELOG entirely as we have to build our own changelog?

2021-07-14 11:06 UTC, fossdd requested changes, later dismissed
Searching trough the internet I found: http://stackoverflow.com/questions/63151195/ddg#63152521. Maybe you can add `libwxgtk-webview3.0-gtk3-0v5` and `libwxgtk-media3.0-gtk3-0v5` to `scripts/ci/dependencies.sh#L32` to fix the debian packaging CI error.

2021-07-14 15:56 UTC, ajayyy commented on CHANGELOG.txt
> +   * (macOS) Tenacity.app now has its resources inside it rather than in a
I'll revert these changes and I think deleting it can be handled in a separate patch

2021-07-14 21:02 UTC, ajayyy commented
@fossdd doesn't seem to have worked, but thanks for the idea

2021-07-15 01:04 UTC, ajayyy commented
Ubuntu build is fixed!

Now we just need someone to test the mac build again (cc @logo4poop )

There is also the Windows Installer, but I wasn't able to get that one working on master either, so if we don't care about it, I guess we can ignore it for now.

2021-07-15 01:07 UTC, ajayyy commented on win/audacity.rc
>          BLOCK "040904b0"
I think we can save this for another pull request, I think we should keep this one just about getting the binaries saving in the right place

2021-07-15 10:36 UTC, fossdd commented
Perfect! The linux appimage executable worked on my machine. Is any mac user here?

2021-07-15 10:37 UTC, fossdd submitted a review, later dismissed

2021-07-15 17:19 UTC, Be-ing commented on win/audacity.rc
>          BLOCK "040904b0"
sure

2021-07-15 18:28 UTC, Be-ing approved these changes, later dismissed

2021-07-16 03:09 UTC, LoganDark commented
> Perfect! The linux appimage executable worked on my machine. Is any mac user here?

I'm a Mac user (10.14 Mojave, Intel). A couple notes before I share my results:

- The build connects to artifactory.audacityteam.org. If Tenacity wants to be 100% independent, that should probably be removed. Either replaced with another server or removed altogether.

  The offending packages that are retrieved from that server (I believe) are `expat`, `libid3tag`, `libmad`, and of course wxWidgets.

- Here are the steps I used to clone your repository:

  ```
  git clone https://github.com/ajayyy/tenacity
  cd tenacity
  git checkout rename
  git remote add upstream https://github.com/tenacityteam/tenacity
  git merge upstream/master
  ```

- Building the Xcode project and libraries like wxWidgets took about 8 minutes. Not bad.

- The Xcode project contains 'Audacity':

  ![K9yFS2ksMn](https://user-images.githubusercontent.com/4723091/125884056-81c82daf-fd61-44a9-9652-b3f543b3eb83.png)

Alright. Now to the good stuff. I tested launching & lightly using the application and investigated any issues that I found. Here is a summary of the few biggest things I found and the results of my investigations:

- Many of your Info.plist strings are incorrect. Many of the strings are `Audacity version ...` or `Audacity.icns` and the like. `CFBundleName` is `Audacity`. This can be fixed by changing `/cmake-proxies/cmake-modules/MacOSXBundleInfo.plist.in`.

- Onto the double-clicking issue. It appears the reason Tenacity.app cannot be launched via double-clicking or `open` is because `CFBundleExecutable` is set to `Wrapper`, which does... absolutely nothing. It returns a 0 status code, but does not actually launch anything. The source code of `Wrapper` can be found in `/mac/Wrapper.c`, where `static const char audacity[] = "Audacity";`. Changing this string to `"Tenacity"` fixes the issue 🎉 

- The window title says `Audacity`. Grepping for `"Audacity"` (with quotes), I can see that the CMake project still self-identifies as Audacity in a few places, and tons of the locales also say Audacity (this is probably the source of the title).

All in all, this is very close to being fully functional and rebranded. Feel free to poke me if you need me to test anything else out.

2021-07-16 06:00 UTC, panos commented on help/audacity.appdata.xml
> +  <id>org.tencacityaudio.Tenacity</id>
Shouldn't the entire file be renamed as well?

2021-07-16 06:04 UTC, panos commented on scripts/build/macOS/DMGSign.cmake
> +set( APP_IDENTIFIER "org.tenacityaudio.tenacity" )
This opens up a separate issue: If we are going to refer to ourselves as "Tenacity Audio", do we rename the entire organization as well? (I can do it if needed.)

2021-07-16 06:05 UTC, panos commented on help/audacity.appdata.xml
> +  <id>org.tencacityaudio.Tenacity</id>
Also, typo.

2021-07-16 06:07 UTC, panos commented on scripts/build/macOS/DMGSign.cmake
> +set( APP_IDENTIFIER "org.tenacityaudio.tenacity" )
People use domains in reverse very often as part of their identifier. This happens very frequently in Android applications too.

2021-07-16 10:05 UTC, panos commented on scripts/build/macOS/DMGSign.cmake
> +set( APP_IDENTIFIER "org.tenacityaudio.tenacity" )
FYI: Others said (for obvious reasons) not to touch the organization name, so it's just the typo in my previous comment that should be dealt with.

2021-07-16 11:01 UTC, fossdd submitted a review, later dismissed
I would also change the file names like `help/audacity.1` and search where it's used.

2021-07-16 11:01 UTC, fossdd commented on help/audacity.appdata.xml
> +        <p>New features in Tenacity 2.3.0:</p>
I would remove the releases: Tenacity's versions are not the same as in Audacity.

2021-07-16 11:01 UTC, fossdd commented on linux/tenacity.sh
>  #!/bin/sh
You changed the file modes from the file. Now it isn't executable anymore, can you revert it to 755?

2021-07-16 11:01 UTC, fossdd commented on scripts/build/macOS/NotarizeMacos.cmake
>  # DMG_LOCATION - the path to Audaicty dmg package
Do you also changed the DMG file?

2021-07-16 11:01 UTC, fossdd commented on win/Audacity.exe.manifest
>        name="Audacity.Audacity.Audacity"
What's with this entry?

2021-07-16 13:42 UTC, panos commented on help/audacity.appdata.xml
> +        <p>New features in Tenacity 2.3.0:</p>
We could completely remove the changelog and just direct people to Audacity's CHANGELOG.TXT if we continue using patches from them??

2021-07-17 13:38 UTC, panos commented
Oops, forgot to sign off my commits because I was working on a different directory. I'll force-push those changes again, they need to be thoroughly tested.

2021-07-17 13:38 UTC, panos commented
*sigh*, here goes.

2021-07-17 13:48 UTC, panos commented
Cool, DCO fails even if my commits *are* signed off, and everything is broken due to some very weird reason that I'm failing to understand here.

2021-07-17 16:14 UTC, fossdd commented on help/audacity.appdata.xml
> +        <p>New features in Tenacity 2.3.0:</p>
Yep

2021-07-17 20:15 UTC, leio commented on help/tenacity.1
> +.I ~/.tenacity-data/Plug-Ins
If ~/.audacity-data gets changed anyways, it would be best if it is moved to a XDG compliant path, as doing that later would involve having to write migration support, while can get away without it now. Littering the home folder directly with hidden subdirectories is considered bad practice nowadays, and this should be used instead: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

In glib the functions for getting these are `g_get_user_cache_dir`, `g_get_user_config_dir`, `g_get_user_data_dir`, as appropriate (so to do it properly, might have to split things up between them). I don't think wxStandardPaths supports this at all, it seems stuck in the 1990's, but there's already __WXGTK__ specific code for that in the codebase, which could just call the glib function at that point prolly.

2021-07-18 05:23 UTC, LoganDark commented
@panos you have a bad habit of force-pushing, whenever I go to view the latest changes from my email they're all gone (: always gotta click "Files Changed" again

2021-07-18 05:26 UTC, panos commented
> @panos you have a bad habit of force-pushing, whenever I go to view the latest changes from my email they're all gone (: always gotta click "Files Changed" again

Yeah, you're absolutely right and I'm sorry about this, I just have ajayyy's changes in a separate directory and I forgot to turn on signing off by default. I just fixed that, I'll cut it off.

2021-07-18 10:00 UTC, leio commented on help/tenacity.1
> +.I ~/.tenacity-data/Plug-Ins
As discussed on IRC, as long as we don't mind a double data loss from git builds before any releases, and get this part figured out before any initial release, it would make sense to tackle this in a separate step, as long as it's not forgotten.

Looks like wx3.1 has some opt-in XDG basedirs awareness, but not full, and wxGTK is currently required for non-OSX/non-Windows platforms (it always links to glib/gtk+ explicitly in cmake in that case right now), so imo the direct glib usage makes most sense, if we want to support wx3.0 (I have that working in a dirty way locally already).

2021-07-18 11:53 UTC, panos commented
Need some help with testing this. There's still a few details, but the issues that @leio brought up will probably have to be addressed in a different pull request for the sake of efficiency.

2021-07-19 22:16 UTC, Be-ing commented
What specifically needs to be tested? Builds for a certain OS?

2021-07-21 07:22 UTC, panos commented
> What specifically needs to be tested? Builds for a certain OS?

- The builds need to use the name "Tenacity" instead of Audacity. (Does this happen on macOS? Can we get it done on Windows, because that isn't ready yet here?)
- Same goes for the Flatpak-relevant manifests and the man pages.

2021-07-21 13:28 UTC, Be-ing commented
There are a bunch of merge conflicts now.

2021-07-21 16:23 UTC, ajayyy commented
MacOS dmg installer works. The name is changed, but it does say "Audacity.app" in the help text.

![image](https://user-images.githubusercontent.com/12688112/126524025-0ebd2c6c-4822-4518-aace-6880fa260f5b.png)

It works fine on double click for me, so the issues @logo4poop mentioned are fixed

2021-07-21 17:00 UTC, ajayyy commented on help/tenacity.1
> +.I ~/.tenacity-data/Plug-Ins
Can you make an issue for this (if it doesn't exist)? I'll change it back to audacity-data for now

2021-07-21 17:08 UTC, panos commented on .gitignore
> +.vscode/
Is it possible to undo this commit and merge this separately?

At this rate, we'll probably have to merge everything at once with a squash or rebase, squash some selected commits and make the commit messages much more descriptive. (I can take care of that, considering that it's a loose end that I participated in. I think that it'd be a good idea to do this either way.)

2021-07-21 17:14 UTC, panos commented
I tend to run `git pull origin master --rebase` and then manually resolve the conflicts in order to prevent merge commits, they can clutter up the tree very easily and make it impossible to tell apart if a tree merge originates from a single PR or multiple PRs. It's small stuff, but it can get very bad and chaotic after a lot of time. Should I take a look at that for you?

2021-07-21 17:17 UTC, ajayyy commented
@panos I did that at first but changed to merge commit as it was overwriting build history, which I think was useful to see for this pull request.

2021-07-21 17:20 UTC, panos commented
> @panos I did that at first but changed to merge commit as it was hiding the build history, which I think was useful to see for this pull request.

Hm, understood, I'll try to fix up some commits that I wanted to rebase anyway (such as the permissions fix and the `~/.audacity-data` thing) either way and push it once again. Working on it right now.

2021-07-21 17:37 UTC, panos commented
Okay, rebasing this with corrections is a bit of a hell.

2021-07-21 17:51 UTC, panos commented
I can't even rebase this using `git rebase HEAD~100` (not even `-i`) without doing anything to the tree whatsoever because of:

```
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Removing INSTALL
error: could not apply 762175fb6... Improve documentation
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 762175fb6... Improve documentation
```

Jesus.

2021-07-21 17:54 UTC, emabrey commented
I've already gotten this done, the windows and linux builds at least. Check master. I haven't modified the Mac installer though, but you may not be aware I have done this unless delete CMake cache, reconfigure and regenerate.

2021-07-21 17:58 UTC, ajayyy commented
@panos We can just squash and merge into one commit

2021-07-21 17:59 UTC, ajayyy commented
@emabrey yea, I noticed some of the stuff was changed in parallel when merging upstream back into this branch, but I fixed the conflicts

2021-07-21 18:02 UTC, emabrey commented
I didn't change the mac configuration because I wasn't sure if you have to register app names on Mac. Does the app identifier have to be registered?

2021-07-21 18:04 UTC, panos commented
> @panos We can just squash and merge into one commit

Yeah, that's fair. Merging against master in the middle of the PR definitely complicated a lot of things and we should avoid that in the future from now on.

2021-07-21 18:06 UTC, emabrey commented
My PR? Or did you merge this one?

2021-07-21 18:26 UTC, emabrey requested changes
I don't think you should add back the trademark information. We are not authorized to use that trademark at all.

2021-07-21 18:26 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Why did you add the trademark back?

2021-07-21 18:26 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "InternalName", "DarkAudacity"
Why did you rename it back to DarkAudacity?

2021-07-21 18:26 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "OriginalFilename", "DarkAudacity.exe"
Same issue, why rename back to `DarkAudacity.exe`?

2021-07-21 18:26 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Same trademark issue as below.

2021-07-21 18:40 UTC, ajayyy commented on win/tenacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
I removed it again, but I am a little concerned about removing it if we still have references to Audacity left.

2021-07-21 18:54 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
https://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:t5wpq6.3.12
I don't think they have a trademark on the word "Audacity"
"The color(s) blue, red, orange, and yellow is/are claimed as a feature of the mark. The mark consists of the word Audacity in rounded block letters in blue gradient to the right of a pair of headphones with a soundwave as displayed in a digital audio workstation (DAW) flowing between the ear cups of the headphones in which the headphones are in blue, and the soundwave is in red, orange, and yellow."

2021-07-21 18:58 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Also the registered owner of the "Audacity" trademark is actually `MuseCY SM Ltd.`, not Dominic Mazzoni.

2021-07-21 19:11 UTC, closed without merging

2021-07-21 19:22 UTC, ajayyy commented
I broke this pull request, will make a new one in a bit

2021-07-21 19:42 UTC, ajayyy commented
https://github.com/tenacityteam/tenacity/pull/332

2021-07-21 19:56 UTC, emabrey commented on win/tenacity.rc
> +            VALUE "LegalTrademarks", "Audacity® is a registered trademark of Dominic Mazzoni."
Actually, there are two word trademarks as well:

https://tmsearch.uspto.gov/bin/showfield?f=doc&state=4805:nulhm8.2.18
https://tmsearch.uspto.gov/bin/showfield?f=doc&state=4805:nulhm8.2.48