RFC: Add CONTRIBUTING.md and require DCO
tenacityteam/tenacity-legacy pull request #171
Opened 2021-07-08 21:17 UTC by Semisol

## To people here: We want *your* feedback, so please approve, or request changes/comment on what you think needs to be improved.

A CONTRIBUTING.md document has been added, and along with
it a Developer Certificate of Origin (DCO) which has been
partially discussed on IRC.

A Developer Certificate of Origin (DCO) is used in projects
big and small to ensure that liability falls on the person
who wrote the commits if they violate any licenses. You need to
"sign off" your commits by adding `Signed-off-by: user <email@email.email>`
to the last lines (where `Co-authored-by`, etc reside).
We have decided to go this way due to a sign off being permanent
and verifiable in the commit history, unlike GH issues/srht mailing
list archives.

A summed up version of it is:
You're either submitting your own work, or affirming that you have permission to submit another person's work under this license, while keeping the original contributor's copyright over the code.

Currently unmerged patches/PRs will be requested to sign-off their commits.

- [x] The code in this pull request is licensed under "GPLv2 or any later version"\*
- [x] (N/A) I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-08 21:19 UTC, falkTX commented on .github/pull_request_template.md
> +- [ ] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
Shouldn't `§` be `&` ?

2021-07-08 21:21 UTC, Semisol commented on .github/pull_request_template.md
> +- [ ] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
Nope, I intentionally made it a section sign.

2021-07-08 21:21 UTC, SFR-git commented on .github/pull_request_template.md
> +- [ ] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
No, `§` generally indicates a specific part of a document.

2021-07-08 21:23 UTC, imachug commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
Does that mean everyone who notices a bug will have to resort either to IRC or mailing lists to report it?

2021-07-08 21:23 UTC, SFR-git commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
This should change to "version 2 or later"

2021-07-08 21:24 UTC, Semisol commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
I was being sort of conflicted about that too. I'll change it.

2021-07-08 21:24 UTC, Semisol commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
Only when upstream is merged, probably.

2021-07-08 21:24 UTC, falkTX commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
good point, no. maybe best to clarify what "confirmed bugs" mean.

I think the intention is to not allow things that are not real bugs in the software.

2021-07-08 21:25 UTC, SFR-git commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
Yes. If it's not actually a bug, we'll explain. If it is a quick fix, someone can send a patch and resolve it. If it's a more complicated problem, or something we can only resolve once something else is fixed, then we ask you to file a ticket.

Think of it as a todo list.

2021-07-08 21:25 UTC, imachug commented on CONTRIBUTING.md
> +for more details.
You might want to make it obvious that you should amend and force-push only *your* commits. E.g. if you add a comment to a file and then fix a typo, the 'fix a typo' part should be amended, but adding a comment shouldn't be amended into earlier commits from upstream.

2021-07-08 21:30 UTC, imachug commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
@SFR-git That doesn't sound very user-friendly (or developer-friendly in this case). The usual approach to handle this is that all confirmed issues are labeled, and all unlabeled issues are considered to-be-labeled-and-maybe-not-a-bug.

2021-07-08 21:30 UTC, Semisol commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
I still think it is not necessary for GH.

2021-07-08 21:32 UTC, SFR-git approved these changes, later dismissed
The concept of "confirmed issues" is worth talking about at some point, but I think this is enough for now.

2021-07-08 21:34 UTC, imachug commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
It may be useful to add something like '(switching over to GPL 2-or-later is in process)' nonetheless so that people are not confused when they see 'GPL 2 only' in one place and 'GPL 2-or-later' in another place.

2021-07-08 21:35 UTC, ajayyy commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
If we wait, then we will have to contact all new contributors again to change. I think it should be changed to
```suggestion
license, version 2 only (see [`LICENSE`](LICENSE)). All contributions are accepted under GNU General Public
license, version 2 or any later version.
```

2021-07-08 21:36 UTC, Semisol commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
Not sure how this would play out, I don't want to do this

2021-07-08 21:36 UTC, imachug commented
Tricky question: does it make sense to ask those who contribute via GitHub for a DCO? GitHub already includes the name of the PR author in the description of the merge commit, so what's the point?

2021-07-08 21:38 UTC, Semisol commented
> Tricky question: does it make sense to ask those who contribute via GitHub for a DCO? GitHub already includes the name of the PR author in the description of the merge commit, so what's the point? Just a checkbox in the PR description looks enough.

The problem with a checkbox though is that it does not persist. It only is on GH and nowhere to be found on the actual git clone, but DCOs are bound to the whole commit history.

2021-07-08 21:39 UTC, ajayyy commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
See https://dolphin-emu.org/blog/2015/05/25/relicensing-dolphin/

2021-07-08 21:40 UTC, imachug commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
> Not sure how this would play out, I don't want to do this

The problem is you have to decide *now*: either you have plans to switch to GPL 2+, in which case you have to do what was suggested above, or you don't have such plans, because if you decided to perform the switch after accepting GPL 2-only contributions, you'd have to redo all of them from scratch, which would probably be equivalent to performing all the changes commited to Tenacity since today.

2021-07-08 21:42 UTC, imachug commented
> The problem with a checkbox though is that it does not persist. It only is on GH and nowhere to be found on the actual git clone, but DCOs are bound to the whole commit history.

Right, but my point is that merge commits by GitHub are also bound. You can have CI check that the checkbox is set and not accept the PR otherwise or something. It wouldn't be very troublesome for you but would be much easier for contributors.

2021-07-08 21:43 UTC, Semisol commented
> > The problem with a checkbox though is that it does not persist. It only is on GH and nowhere to be found on the actual git clone, but DCOs are bound to the whole commit history.
> 
> Right, but my point is that merge commits by GitHub are also bound. You can have CI check that the checkbox is set and not accept the PR otherwise or something. It wouldn't be very troublesome for you but would be much easier for contributors.

Also it is easy to sign-off commits in Git: -s in the commit command.
And also, I still don't feel comfortable using that approach.

2021-07-08 21:49 UTC, SFR-git commented
> > The problem with a checkbox though is that it does not persist. It only is on GH and nowhere to be found on the actual git clone, but DCOs are bound to the whole commit history.
> 
> Right, but my point is that merge commits by GitHub are also bound. You can have CI check that the checkbox is set and not accept the PR otherwise or something. It wouldn't be very troublesome for you but would be much easier for contributors.

You can't prove with 100% certainty that a contributor checked that box, just from the git log. All we're doing is passing the responsibility to the contributor.

2021-07-08 21:50 UTC, emabrey commented on CONTRIBUTING.md
> +only. We'll ask you to file a ticket if appropriate.
https://stackoverflow.com/questions/42966981/special-character-%C3%82-inserted-before-copyright-symbol

2021-07-08 23:10 UTC, Be-ing commented
I don't understand the difference between "signing off" and the author of the commit. Can you elaborate on this?

2021-07-09 04:52 UTC, SFR-git commented
> I don't understand the difference between "signing off" and the author of the commit. Can you elaborate on this?

By "Signing-off" you agree to the DCO, and affirm that to your knowledge you have permission to contribute this code under the GPLv2.

This way, if it turns out someone's intellectual property was infringed upon, the responsibility isn't on the maintainers' hands, but on the original contributor's.

I suggest reading the entire DCO if you haven't already — it's short and simple to understand.

2021-07-09 06:39 UTC, adrianheine commented
I feel like this DCO tries to solve a rather academical legal problem while making contributing a bit more complicated.

2021-07-09 06:47 UTC, SFR-git commented
I think it's a worthwhile tradeoff. Many projects already use a DCO, including Docker, Samba, Git, Open vSwitch, OpenDaylight, Ceph, OpenSearch and qemu.

If you use the Git CLI, it's a one-time configuration:
```sh
$ git config format.signoff true
```

That makes `git commit` automatically include a signoff.

2021-07-09 06:53 UTC, fossdd commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
May also write to keep the changes clean, cause of the rebasing of the upstream?

2021-07-09 07:11 UTC, SFR-git commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
> If we wait, then we will have to contact all new contributors again to change. I think it should be changed to
> `[Suggested change]`

I think simply changing "only" to "or any later version" is enough. Also capitalise "License".

```suggestion
License, version 2 or any later version (see [`LICENSE`](LICENSE)).
```

2021-07-09 08:00 UTC, imachug commented
> Also it is easy to sign-off commits in Git: -s in the commit command.

Not if the changes have already been committed: you'll either have to redo them or perform a signoff rebase. Also there's no checkbox for signoff in GitHub commit UI. I'm not saying all these problems are impossible to solve, but every nuanced requirement reduces the potential number of contributors and increases the rate of invalid PRs.

> You can't prove with 100% certainty that a contributor checked that box, just from the git log. All we're doing is passing the responsibility to the contributor.

See, the point of a DCO is that *the maintainers* know for sure whom they got the commits from. From this point of view, using a bot under your control or simply checking if the checkbox is checked (pun not intended) with your eyes is as evidentiary (if not more so, because replacing `[ ]` with `[x]` manually is a less common action than slightly modifying a CLI command) as a footer in the commit description.

On the other hand, *normal users* cannot completely trust either of the ways if they don't trust you. You say that a merge committed via GitHub UI is not a proof that the checkbox was set. My response is that if someone doesn't trust the maintainers, Signed-Off-By is not a proof either, because absolutely everyone can fake commit authorship and commit something as if it was signed off by Linus Torvalds, including you. Secondly, maybe you don't know that but when you create a PR from me/repo to upstream/repo, GitHub immediately allows upstream/repo maintainers to push to me/repo, which would allow you to add the Signed-Off-By header.

If you were going to use Signed-Off-By as a proof in court, that won't work. Then why not make it easier for contributors while retaining the same level of security?

2021-07-09 08:14 UTC, SFR-git commented
> you'll either have to redo them or perform a signoff rebase. 

That's negligible. `git rebase --signoff HEAD~5` is a very simple command, and maintainers ask contributors to rebase their PRs all of the time.

> Signed-Off-By is not a proof either, because absolutely everyone can fake commit authorship and commit something as if it was signed off by Linus Torvalds, including you.
 
That is only correct if you don't sign your commits with PGP, which I urge everyone to do.
Generally, though, yes. It's not any more "secure" than checking a box.

> If you were going to use Signed-Off-By as a proof in court, that won't work. Then why not make it easier for contributors while retaining the same level of security?

Keep in mind GitHub is not the only way to contribute: people sending patches through sourcehut will still be required to sign a DCO. Only requiring DCO from one channel is unnecessary complexity which will inevitably lead to confusion.

When someone makes a PR and doesn't sign the DCO, we'll kindly ask them to sign it, and will provide the appropriate commands to do so. It's not very complicated. If it was, [no one would be using it](https://github.com/tenacityteam/tenacity/pull/171#issuecomment-876956840).

2021-07-09 08:41 UTC, imachug commented
> That's negligible. `git rebase --signoff HEAD~5` is a very simple command, and maintainers ask contributors to rebase their PRs all of the time.

That is easy for you and for me, but may not be so for those who use graphical git clients or GitHub UI (neither is good but still).

> That is only correct if you don't sign your commits with PGP, which I urge everyone to do.

An evil maintainer could just strip a PGP signature they don't like so that's not an argument.

>  Generally, though, yes. It's not any more "secure" than checking a box.

So why not allow both?

> Keep in mind GitHub is not the only way to contribute: people sending patches through sourcehut will still be required to sign a DCO. Only requiring DCO from one channel is unnecessary complexity which will inevitably lead to confusion.

How is *that* complex? Requiring two actions from contributors (-s and a checkbox) *is* complex. Optimization makes things easier, not harder. You *will* have non-signed-off commits in the codebase either way, so what is the problem? I really don't see it, is that just maintainers' laziness or am I missing something?

> When someone makes a PR and doesn't sign the DCO, we'll kindly ask them to sign it, and will provide the appropriate commands to do so. It's not very complicated. If it was, no one would be using it.

Tenacity *was founded* because people didn't want Audacity to do what everyone else does (read: privacy policy, CLA, etc.).

The list you provided contains:
- Docker, OpenSearch and Ceph, that are maintained by for-profit companies,
- Samba, that inherently had problems with code licensing because it's an implementation of proprietary SMB and you don't want to accidentally copy leaked Microsoft code,
- I'd also add Linux here, that are both maintained by Linus Torvalds, the inventor of DCO that most people use, who also could have some problems with UNIX proprietary code back then,
- Git, Open vSwitch, OpenDaylight, that are maintained by Linux Foundation too and probably adopted DCO only because of Linus,
- qemu, which looks like an exception to me.

Im my very humble opinion, Tenacity had not and will not face the same problems as Amazon, Red Hat and other companies do, it does not contain anything that potentionally can be a trade secret, and it is not maintained by Linus our saviour Torvalds.

You are not a corporation, and people switched from Audacity to Tenacity *exactly* because of this. You do not have to repeat what others do, and you have to keep in mind that not everything that others do is best practice. Seeing how you use 'but mum they did it too' argument just a few days after shaming Audacity team for that is astonishing at best.

2021-07-09 08:54 UTC, imachug commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
That won't work either because older commits are under GPL 2 only.

2021-07-09 08:55 UTC, falkTX commented
There could very likely be other examples of projects using DCO, we should not look at the list as an indication of anything but that other projects are successfully using it.

DCO is to protect the maintainers and not the users, it seems quite good to me.
The push from DCO is not because some others are doing it, but because we want to.

It is complicated to manage Github and sourcehut in 2 different ways, if one requires signed-off DCO and the other doesn't.

The contributions from upstream audacity will obviously not have DCO on them, but IMO contributions made to this repository should.

2021-07-09 08:56 UTC, falkTX commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
Upstream already relicensed to GPLv2+

2021-07-09 08:56 UTC, SFR-git commented
Keep in mind I'm not part of the team: I'm talking for myself, my opinions and takes are my own.

If Semisol or any other dev provides a different response, this isn't them "taking anything back" like Muse did. Both of our standpoints are clear, let's see what others have to say.

2021-07-09 09:00 UTC, imachug commented
*I'm no longer sure if this discussion is still beneficial so if it's not feel free to hide this comment as offtopic and I'll shut up.*

> It is complicated to manage Github and sourcehut in 2 different ways, if one requires signed-off DCO and the other doesn't.

- `If` got a patch via email
  - Make sure the patch has `Signed-Off-By` field
- `If` got a PR via GitHub
  - It's already OK

What's 'complicated' here? I really don't understand what exactly is the problem, you're *developers*, not, say, managers who have little experience in coding, or users or contributors who shouldn't even care about the differences (I believe SourceHut users know what signoff is already and mainly GitHub users won't even try to use SourceHut once so it's not a problem for them).

2021-07-09 09:02 UTC, Semisol commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
Added to todo list, will see in a few mins

2021-07-09 09:05 UTC, Semisol commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
I think we have GPLv2 only commits

2021-07-09 09:32 UTC, imachug commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
> Upstream already relicensed to GPLv2+

Via CLA that not everyone signed?

2021-07-09 09:45 UTC, Semisol commented
Also let me explain why I wanted to add this: The GitHub checkbox isn't that permanent enough in the Git log.
For the "faking" of commits, if needed we can enforce PGP signatures but that is another whole thing in itself up for another debate/RFC.

2021-07-09 10:05 UTC, falkTX commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
They said they did and the repository is theirs, it is not our place to judge.
If you fork the repository now, it will be already GPLv2+

2021-07-09 10:21 UTC, falkTX requested changes, later dismissed
please mention version 2 or any later version instead of version 2 only.

GPLv2+ is compatible with GPLv2, we gain nothing by restricting to GPLv2 only.

2021-07-09 10:44 UTC, falkTX submitted a review, later dismissed

2021-07-09 10:59 UTC, SFR-git approved these changes, later dismissed

2021-07-09 11:35 UTC, SFR-git commented on CONTRIBUTING.md
> +license, version 2 only (see [`LICENSE`](LICENSE)).
Closing: the line this discussion references is outdated.

2021-07-09 11:38 UTC, Semisol commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
Wait may I requewst more details?

2021-07-09 11:39 UTC, SFR-git commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
I think "Proper formatting guidelines" covers "keeping changes clean".

2021-07-09 11:41 UTC, SFR-git commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
How about this:
```suggestion
2. Do not change any variable names unless necessary.
3. Keep changes compatible with upstream whenever possible.
```

2021-07-09 12:12 UTC, imachug commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
upstream as in Audacity or Tenacity? I think it makes sense to elaborate.

2021-07-09 12:14 UTC, Semisol commented
Should be added now.

2021-07-09 12:16 UTC, Semisol commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
Elaborated on it

2021-07-09 12:16 UTC, SFR-git commented on CONTRIBUTING.md
> +2. Do not change any variable names unless necessary.
That's a good point. I'm inclined to say "both", but this should be properly specified

2021-07-09 12:18 UTC, SFR-git approved these changes
If no one has any more suggestions, this can me merged.

2021-07-09 12:56 UTC, falkTX approved these changes

2021-07-09 12:58 UTC, merged