docs: installing tenacity is not supported, yet.
tenacityteam/tenacity-legacy pull request #187
Opened 2021-07-09 16:12 UTC by fossdd

Resolves: GH #172

Updates the documentation that installing tenacity is not yet supported

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

2021-07-09 22:24 UTC, Be-ing approved these changes, later dismissed

2021-07-10 00:10 UTC, emabrey approved these changes

2021-07-10 03:10 UTC, emabrey requested changes

2021-07-10 03:10 UTC, emabrey commented on BUILDING.md
> +In the moment, you are unable to install tenacity system-wide due conflits with libraries. You have to run Step 4 to use Tenacity. We are trying to fix that for the first stable release.
This should probably say "At the moment," not "In the moment"

2021-07-10 08:48 UTC, fossdd commented on BUILDING.md
> +In the moment, you are unable to install tenacity system-wide due conflits with libraries. You have to run Step 4 to use Tenacity. We are trying to fix that for the first stable release.
done

2021-07-10 14:49 UTC, emabrey approved these changes

2021-07-10 15:12 UTC, Semisol commented
reminder to maintainers: **squash** and merge, thanks

2021-07-10 15:12 UTC, Semisol approved these changes

2021-07-10 15:12 UTC, merged