CMake: fix search of LAME from system with module from Mixxx
tenacityteam/tenacity-legacy pull request #226
Opened 2021-07-11 23:40 UTC by Be-ing

Mixxx is licensed GPLv2 or later. This CMake module comes from:
https://github.com/mixxxdj/mixxx/blob/main/cmake/modules/Findmp3lame.cmake
Thanks to @Holzhaus for writing the CMake module.

Signed-off-by: Be <be@mixxx.org>

Resolves: #225

I am not certain if this fully works yet because there are still other build problems using system libraries.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-11 23:41 UTC, Be-ing commented
Audacity can't copy this fix because it is licensed GPL v2 or later :grin:

2021-07-12 01:32 UTC, fossdd requested changes
Can you add `lame` to the `.builds/archlinux.yml` file, to fix the builds.sr.ht CI?

2021-07-12 16:21 UTC, SFR-git commented
> Can you add `lame` to the `.builds/archlinux.yml` file, to fix the builds.sr.ht CI?

I think `lame-dev` is needed, actually.
There's an almost-comprehensive list of the packages for building without conan somewhere [here](https://builds.sr.ht/~sfr), in a failed Archlinux build.

2021-07-13 03:28 UTC, Be-ing commented
Closing in favor of #228

2021-07-13 03:28 UTC, closed without merging