Corrected inaccurate build instructions and vague points in install instructions
tenacityteam/tenacity-legacy pull request #227
Opened 2021-07-12 01:34 UTC by Songtech-0912

##  PR Description

Signed-off-by: Jacky Song <dixinlily@hotmail.com>

* The original install instructions for Linux systems had the incorrect instruction of `cmake -G "Unix Makefiles" -Duse_ffmpeg=loaded ../tenacity` where it should've actually been `cmake -G "Unix Makefiles" -Duse_ffmpeg=loaded ..`
* As well as fixing this, I also added an alternate instruction for running `make` to reduce processor resource use and to explicitly specify the different options of compiling (which may be confusing for beginners)

- [x] I have signed off my commits using `-s` or `Signed-off-by`
- [x] I made sure the code compiles on my machine (this change is not related to code)
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

2021-07-12 01:41 UTC, fossdd requested changes
nice PR

2021-07-12 01:41 UTC, fossdd commented on BUILDING.md
> +   $ cmake -G "Unix Makefiles" -Duse_ffmpeg=loaded ..
This doesn't work. `build` isn't in the same directory as the git repo.

2021-07-12 01:45 UTC, Songtech-0912 commented on BUILDING.md
> +   $ cmake -G "Unix Makefiles" -Duse_ffmpeg=loaded ..
Oops, my bad. I'll correct that. I just instinctively got used to cd-ing into a repo once I cloned it so I didn't get why it didn't work as intended :(

2021-07-12 01:47 UTC, Songtech-0912 commented
I've fixed the changes, merge?

2021-07-12 02:10 UTC, fossdd commented
You can revert the commit and re-commit it with the sign. Search on the Internet to search how to.

2021-07-12 02:11 UTC, fossdd submitted a review, later dismissed

2021-07-12 02:11 UTC, fossdd commented on BUILDING.md
> +    $ git clone https://github.com/tenacityteam/tenacity/ && cd tenacity
Can you cd in a new line?

2021-07-12 02:16 UTC, Songtech-0912 commented on BUILDING.md
> +    $ git clone https://github.com/tenacityteam/tenacity/ && cd tenacity
Sorry, I don't quite get what you mean. Do you mean this:

```bash
$ git clone https://github.com/tenacityteam/tenacity/
$ cd tenacity
```

2021-07-12 02:28 UTC, Songtech-0912 commented on BUILDING.md
> +    $ git clone https://github.com/tenacityteam/tenacity/ && cd tenacity
I've separated it to a new line.

2021-07-12 02:31 UTC, Songtech-0912 commented
Both commits are now signed, the revert commit and the correction commit.

2021-07-12 05:43 UTC, panos submitted a review, later dismissed

2021-07-12 05:44 UTC, panos commented
Need additional confirmation here.

2021-07-13 11:03 UTC, Songtech-0912 commented
Ok, no problem. Take your time.

2021-07-13 11:58 UTC, imachug commented
Hi! I see that you signed-off the new commit, but the reverted commit is still in the history so DCO still does not pass. Can you please do something like this to replace the latest 3 commits with a single correct one?

```
git reset --soft HEAD~3  # revert 3 latest commits
git commit -s -m " Fixed instructions to enter repo before building on newline"  # commit new changes
git push --force-with-lease
```

Thank you!

2021-07-13 12:14 UTC, Songtech-0912 commented
Thank you for the advice! I have followed your instructions and force-pushed to git, that should've solved the unsigned past commit issue.

2021-07-13 12:21 UTC, imachug commented on BUILDING.md
> +   $ make -j`let numcores=$(nproc)-2 ; echo $numcores`
What do you think about using `make -j$(($(nproc)-2))` instead? It's shorter and also works well in bash. I'm not sure whether it's too cryptic, what's your opinion?

2021-07-13 12:24 UTC, Songtech-0912 commented on BUILDING.md
> +   $ make -j`let numcores=$(nproc)-2 ; echo $numcores`
Yeah, I agree, that would be a superior choice as long as there is an explanation of what the command means - I'll add that.

2021-07-13 12:37 UTC, Songtech-0912 commented
@imachug I've changed the `make` command to the one you suggested.

2021-07-13 12:39 UTC, imachug approved these changes

2021-07-13 12:41 UTC, Semisol commented
> Hi! I see that you signed-off the new commit, but the reverted commit is still in the history so DCO still does not pass. Can you please do something like this to replace the latest 3 commits with a single correct one?
> 
> ```
> git reset --soft HEAD~3  # revert 3 latest commits
> git commit -s -m "Fixed instructions to enter repo before building on newline"  # commit new changes
> git push --force-with-lease
> ```
> 
> Thank you!

You may also `git rebase HEAD~3 --signoff`.

2021-07-13 12:42 UTC, imachug commented
> You may also git rebase HEAD~3 --signoff.

Those the 3 commits were something like 'do change (no sign-off)', 'rollback previous commit', 'do change (with sign-off)' so I think this worked better but yeah.

2021-07-13 12:50 UTC, Semisol commented
> > You may also git rebase HEAD~3 --signoff.
> 
> Those the 3 commits were something like 'do change (no sign-off)', 'rollback previous commit', 'do change (with sign-off)' so I think this worked better but yeah nice to hear rebase supports signoff.

I tested, it does not double sign-off.

2021-07-13 13:24 UTC, Songtech-0912 commented
Checks look like they've all passed. Any other things that I may potentially need to change in the commit?

2021-07-13 13:27 UTC, panos approved these changes

2021-07-13 13:30 UTC, imachug commented
cc @fossdd (very sorry if rushing you)

2021-07-13 13:31 UTC, merged

2021-07-13 13:32 UTC, imachug commented
Thank you for your contribution!