[POC] use CMake find_package instead of cmake-proxies hacks
tenacityteam/tenacity-legacy pull request #228
Opened 2021-07-12 02:04 UTC by Be-ing

Signed-off-by: Be <be@mixxx.org>

This is a proof-of-concept for how Tenacity could ignore the mess in the cmake-proxies directory entirely and use straightforward CMake modules with `find_package` instead. Most of these CMake modules were written by @Holzhaus for Mixxx which is licensed GPLv2 or later, so Audacity cannot use them. Mixxx uses vcpkg for dependencies so these CMake modules will Just Work with dependencies built with vcpkg or Linux system packages. I think this is a viable path forward that hopefully won't create many conflicts merging code from Audacity in the future.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-12 05:07 UTC, Be-ing commented
There was a FindwxWidgets.cmake module in there that was interfering with `find_package`. The one that comes with CMake works, however I had to uninstall the Fedora packages for wxWidgets 3 because it was preferring 3 to 3.1.

2021-07-12 05:08 UTC, Be-ing commented
src/KeyboardCapture.cpp has a `#include <gtk/gtk.h>`... what version of GTK does it depend on?

2021-07-12 09:28 UTC, AnotherFoxGuy commented
But how would this work on windows? Are you required to build with MSYS2/Cygwin/MinGW or need to use vcpkg?

2021-07-12 10:53 UTC, Be-ing commented
Use vcpkg for Windows and macOS.

2021-07-12 11:32 UTC, sykhro commented
not strictly related to this pr, what does tenacity need glib for? It's the heck of a dependency which seems a bit odd for a c++ project

2021-07-12 11:35 UTC, Be-ing commented
Good question... also, why is Audacity directly using GTK APIs if it uses wxWidgets??

2021-07-12 11:39 UTC, falkTX commented
audacity uses stuff beyond wxwidgets for some native platform support.
you can find the platform-dependent macros everywhere throughout the code.

For gtk (and win32 and macOS), audacity has a custom file dialog which uses native calls to set up file filters, among other things. There are other places where workarounds are in place, or custom OS functionality.

2021-07-12 11:41 UTC, Be-ing commented
:scream:

2021-07-12 11:47 UTC, Be-ing commented
@falkTX do you know if the GTK APIs are GTK2 or 3?

2021-07-12 11:52 UTC, falkTX commented
afaik it depends on the WxWidgets being in use. some time ago they made it be gtk3 compatible.
at least the version as packaged in Ubuntu 20.04 uses gtk3.

2021-07-12 12:07 UTC, sykhro commented
> audacity has a custom file dialog which uses native calls to set up file filters
So they're using the whole glib for something that can be easily done with native APIs? It's a couple of ifdefs at best

2021-07-12 12:16 UTC, falkTX commented
Gtk uses glib, so on linux you cant escape that dependency.

2021-07-12 12:17 UTC, sykhro commented
> Gtk uses glib, so on linux you cant escape that dependency.

escaping it on windows and macos wouldn't be a bad idea. it's especially painful to compile it on windows

2021-07-12 23:38 UTC, Be-ing commented
It compiles! Now to get it to link...

2021-07-13 01:43 UTC, Be-ing commented
Woooo it builds on my machine with Fedora 34! I copied the FindGTK.cmake module from WebKitGTK and wrote little CMakeLists.txt's for portsmf which has no Fedora package and libnyquist.

2021-07-13 01:47 UTC, Be-ing commented on src/commands/ScriptCommandRelay.cpp
> +#include "../../../lib-src/libnyquist/nyquist/xlisp/xlisp.h"
WTAF

2021-07-13 01:51 UTC, Be-ing commented
The UI scaling is all borked on my 3840 x 2160 screen, but hey, it's something!
![image](https://user-images.githubusercontent.com/9455094/125377592-d8429e00-e352-11eb-842a-bfc4154b6c47.png)

2021-07-13 02:04 UTC, Be-ing commented on src/commands/ScriptCommandRelay.cpp
> +#include "../../../lib-src/libnyquist/nyquist/xlisp/xlisp.h"
#including private headers of your vendored dependencies is a totally normal thing to do right???? :upside_down_face:

2021-07-13 02:05 UTC, Be-ing commented
Please test building this. There is definitely more work to do to complete this and clean it up, but at least this is a proof of concept that this is a viable route forward.

2021-07-13 09:30 UTC, SFR-git commented
Tested this PR on an Arch build, and I've managed to successfully build Tenacity without Conan. :tada: 

([build log](https://builds.sr.ht/~sfr/job/543653#task-build), for anyone interested)

One minor caveat, though: the Arch repositories have an outdated version of `wxgtk`, so I had to build it from source; this led to a build time of 36 minutes.

2021-07-13 10:55 UTC, Be-ing commented
> (build log, for anyone interested)

That was not built, only configured.

2021-07-13 11:24 UTC, AnotherFoxGuy commented
I've tried building this on windows, cmake trows one error and one warning
```
CMake Warning (dev) at C:/msys64/mingw64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (EXPAT) does
  not match the name of the calling package (expat).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.20/Modules/FindEXPAT.cmake:65 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:457 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

```
CMake Error at C:/msys64/mingw64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "3.1")
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/msys64/mingw64/share/cmake-3.20/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  CMakeLists.txt:469 (find_package)
```

The odd thing is that wx has been installed:
```
$ wx-config --list

    Default config is msw-unicode-3.0

  Default config will be used for output

  Alternate matches:
    msw-unicode-3.1
    msw-unicode-static-3.0
    msw-unicode-static-3.1
```

2021-07-13 11:28 UTC, Be-ing commented
> Default config is msw-unicode-3.0

On Fedora I had to uninstall wxWidgets 3.0 because it kept preferring that to 3.1 even though I explicitly specified 3.1 as the minimum version. Help fixing this would be appreciated.

2021-07-13 11:33 UTC, AnotherFoxGuy commented
Uninstalled wxWidgets 3.0, still the same cmake error
```
$ wx-config-3.1 --list

    Default config is msw-unicode-3.1

  Default config will be used for output

  Alternate matches:
    msw-unicode-static-3.1

```

2021-07-13 11:38 UTC, Be-ing commented
I just pushed a hack around this:
```
set(wxWidgets_CONFIG_OPTIONS --version=3.1)
find_package(wxWidgets 3.1 REQUIRED COMPONENTS adv base core html qa xml net)
```
Ideally the upstream CMake module should be fixed to use the minimum version passed to it with wxConfig.

2021-07-13 11:44 UTC, AnotherFoxGuy commented
I've tested with the wxWidgets_CONFIG_OPTIONS hack, cmake still can't find wx

2021-07-13 12:01 UTC, Be-ing commented
Are you using MSYS2 with MinGW? Have you tried vcpkg?

2021-07-13 12:11 UTC, AnotherFoxGuy commented
> Are you using MSYS2 with MinGW?

Yes I'm using MSYS2 with MinGW with Clion as the IDE
>  Have you tried vcpkg?

No, but because tenacity is a privacy-friendly project I don't think that vcpkg should be needed to build it

2021-07-13 16:36 UTC, mmmaisel commented
> The UI scaling is all borked on my 3840 x 2160 screen, but hey, it's something!
> ![image](https://user-images.githubusercontent.com/9455094/125377592-d8429e00-e352-11eb-842a-bfc4154b6c47.png)

I already had this issue with my Audacity development builds since version 3.0.

2021-07-13 22:21 UTC, Be-ing commented
@AnotherFoxGuy try explicitly specifying the path to wx-config with `-DwxWidgets_CONFIG_EXECUTABLE=PATH` https://forums.wxwidgets.org/viewtopic.php?t=46338

2021-07-14 09:41 UTC, Holzhaus commented
> >  Have you tried vcpkg?
> 
> No, but because tenacity is a privacy-friendly project I don't think that vcpkg should be needed to build it

Over at @mixxxdj/vcpkg, we build the libraries using vcpkg, make an archive and deploy it to our server. The users can just grab the precompiled libraries (no telemetry). If you want to build the libraries yourself, you can do that and use the `-disableMetrics` flag:  https://vcpkg.readthedocs.io/en/latest/about/privacy/

2021-07-14 12:48 UTC, AnotherFoxGuy commented
I've got it to configure without any issues by using the mingw64 shell direct, instead of using Clion

But running make throws compiler errors: 

```
$ make -j6
Consolidate compiler generated dependencies of target portsmf
[  5%] Building C object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyx.c.obj
[  7%] Built target locale
[  7%] Building CXX object libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/UrlEncode.cpp.obj
[  7%] Building CXX object libraries/lib-strings/CMakeFiles/lib-strings.dir/Identifier.cpp.obj
[  8%] Building CXX object libraries/lib-utility/CMakeFiles/lib-utility.dir/MemoryX.cpp.obj
[  8%] Building CXX object lib-src/portsmf/CMakeFiles/portsmf.dir/allegrowr.cpp.obj
g++.exe: error: C:\msys64\FID;C:\msys64\projects\tenacity\_build\src\private\configwin.h: Invalid argument
g++.exe: error: C:\msys64\FID;C:\msys64\projects\tenacity\_build\src\private\configwin.h: Invalid argument
g++.exe: error: C:\msys64\FID;C:\msys64\projects\tenacity\_build\src\private\configwin.h: Invalid argument
make[2]: *** [libraries/lib-utility/CMakeFiles/lib-utility.dir/build.make:76: libraries/lib-utility/CMakeFiles/lib-utility.dir/MemoryX.cpp.obj] Error 1
make[2]: *** [libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/build.make:76: libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/UrlEncode.cpp.obj] Error 1
make[2]: *** [libraries/lib-strings/CMakeFiles/lib-strings.dir/build.make:76: libraries/lib-strings/CMakeFiles/lib-strings.dir/Identifier.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:442: libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:494: libraries/lib-utility/CMakeFiles/lib-utility.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:468: libraries/lib-strings/CMakeFiles/lib-strings.dir/all] Error 2
[  8%] Building C object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cext.c.obj
[  8%] Building C object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cleanup.c.obj
[  9%] Building C object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cmdline.c.obj
[ 13%] Built target plug-ins
D:/projects/tenacity/lib-src/libnyquist/nyquist/cmt/cext.c:13:10: fatal error: switches.h: No such file or directory
   13 | #include "switches.h"
      |          ^~~~~~~~~~~~
compilation terminated.
In file included from D:/projects/tenacity/lib-src/libnyquist/nyquist/cmt/cmdline.c:86:
D:/projects/tenacity/lib-src/libnyquist/nyquist/cmt/cext.h:43:10: fatal error: switches.h: No such file or directory
   43 | #include "switches.h"
      |          ^~~~~~~~~~~~
compilation terminated.
In file included from D:/projects/tenacity/lib-src/libnyquist/nyquist/cmt/cleanup.c:4:
D:/projects/tenacity/lib-src/libnyquist/nyquist/cmt/cext.h:43:10: fatal error: switches.h: No such file or directory
   43 | #include "switches.h"
      |          ^~~~~~~~~~~~
compilation terminated.
[ 13%] Building C object lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cmtcmd.c.obj
In file included from D:/projects/tenacity/lib-src/portsmf/allegrowr.cpp:13:
D:/projects/tenacity/lib-src/portsmf/allegro.h: In member function 'const char* Serial_read_buffer::get_string()':
D:/projects/tenacity/lib-src/portsmf/allegro.h:602:33: error: 'strlen' was not declared in this scope
  602 |                          ptr += strlen(s);
      |                                 ^~~~~~
D:/projects/tenacity/lib-src/portsmf/allegro.h:52:1: note: 'strlen' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
   51 | #include <assert.h>
  +++ |+#include <cstring>
   52 | #include <istream>
make[2]: *** [lib-src/libnyquist/CMakeFiles/libnyquist.dir/build.make:118: lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cmdline.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [lib-src/libnyquist/CMakeFiles/libnyquist.dir/build.make:90: lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cext.c.obj] Error 1
make[2]: *** [lib-src/libnyquist/CMakeFiles/libnyquist.dir/build.make:104: lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cleanup.c.obj] Error 1
make[2]: *** [lib-src/portsmf/CMakeFiles/portsmf.dir/build.make:146: lib-src/portsmf/CMakeFiles/portsmf.dir/allegrowr.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:390: lib-src/portsmf/CMakeFiles/portsmf.dir/all] Error 2
D:/projects/tenacity/lib-src/libnyquist/nyquist/cmt/cmtcmd.c:3:10: fatal error: switches.h: No such file or directory
    3 | #include "switches.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib-src/libnyquist/CMakeFiles/libnyquist.dir/build.make:132: lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyquist/cmt/cmtcmd.c.obj] Error 1
D:/projects/tenacity/lib-src/libnyquist/nyx.c:31:10: fatal error: switches.h: No such file or directory
   31 | #include "switches.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [lib-src/libnyquist/CMakeFiles/libnyquist.dir/build.make:76: lib-src/libnyquist/CMakeFiles/libnyquist.dir/nyx.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:416: lib-src/libnyquist/CMakeFiles/libnyquist.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

2021-07-14 14:41 UTC, Be-ing commented
@AnotherFoxGuy please give it another try.

I don't know how CLion works so I can't help you with that.

2021-07-14 15:29 UTC, AnotherFoxGuy commented
Still throws the same g++ errors

2021-07-14 18:05 UTC, emabrey commented
> 
> 
> Still throws the same g++ errors

I have CLion installed. Can you give me the version of CLion and version of gcc you used? I'm sure I could look through the log but it's easier to just ask lol.

2021-07-14 18:24 UTC, Be-ing commented
What is this hell we have entered? Ubuntu does not package wxWidgets 3.1, so I tried to get this building locally with wxWidgets from vcpkg. First, it did not link:
```
[1/506] Linking CXX shared library shared/Debug/lib-string-utils.so
FAILED: shared/Debug/lib-string-utils.so 
: && /usr/bin/c++ -fPIC -pthread -g   -shared -Wl,-soname,lib-string-utils.so -o shared/Debug/lib-string-utils.so libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/UrlEncode.cpp.o libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/UrlDecode.cpp.o libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/CodeConversions.cpp.o libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/DateTimeConversions.cpp.o -L/home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib -Wl,-rpath,/home/be/sw/tenacity/build/bin/Debug//lib64/audacity:/home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib  -L/home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib  -pthread  /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/libwx_gtk3u_qa-3.1.a  /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/libwx_baseu_net-3.1.a  /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/libwx_gtk3u_html-3.1.a  /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/libwx_gtk3u_core-3.1.a  /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/libwx_baseu_xml-3.1.a  /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/libwx_baseu-3.1.a  -lgtk-3  -lgdk-3  -lpangocairo-1.0  -lpango-1.0  -lharfbuzz  -latk-1.0  -lcairo-gobject  -lcairo  -lgdk_pixbuf-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lSM  -lICE  -lX11  -lXext  -lXtst  -lwx_gtk3u_core-3.1  -lgtk-3  -lgdk-3  -lpangocairo-1.0  -lpango-1.0  -lharfbuzz  -latk-1.0  -lcairo-gobject  -lcairo  -lgdk_pixbuf-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lSM  -lICE  -lX11  -lXext  -lXtst  -Wl,-Bstatic  -ljpeg  -Wl,-Bdynamic  -llibpng.a>  -llibpng16d.a>  -Wl,-Bstatic  -lz  -Wl,-Bdynamic  -lm  -llibtiff.a>  -llibtiffd.a>  -lliblzma.a>  -lliblzmad.a>  -Wl,-Bstatic  -ljpeg  -lz  -Wl,-Bdynamic  -lm  -Wl,-Bstatic  -lSDL2main  -Wl,-Bdynamic  -lSDL2  -pthread  -lgtk-3  -lgdk-3  -lpangocairo-1.0  -lpango-1.0  -lharfbuzz  -latk-1.0  -lcairo-gobject  -lcairo  -lgdk_pixbuf-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lSM  -lICE  -lX11  -lXext  -lXtst  -lwx_baseu-3.1  -llibexpat.a>  -llibexpat.a>  -lgtk-3  -lgdk-3  -lpangocairo-1.0  -lpango-1.0  -lharfbuzz  -latk-1.0  -lcairo-gobject  -lcairo  -lgdk_pixbuf-2.0  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lSM  -lICE  -lX11  -lXext  -lXtst  -Wl,-Bstatic  -lz  -Wl,-Bdynamic  -lwxregexu-3.1  -lsecret-1  -lgio-2.0  -lgobject-2.0  -lglib-2.0  -lc  -pthread  -ldl  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/libtiffd.a  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/libexpat.a  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/libz.a  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/libpng16d.a  -lgtk-3  -lgdk-3  -lpangocairo-1.0  -lpango-1.0  -lharfbuzz  -latk-1.0  -lcairo-gobject  -lcairo  -lgdk_pixbuf-2.0  -lSM  -lICE  -lX11  -lXext  -lXtst  -lwx_gtk3u_core-3.1  -Wl,-Bstatic  -ljpeg  -Wl,-Bdynamic  -llibpng.a>  -llibpng16d.a>  -Wl,-Bstatic  -lz  -Wl,-Bdynamic  -llibtiff.a>  -llibtiffd.a>  -lliblzma.a>  -lliblzmad.a>  -Wl,-Bstatic  -lSDL2main  -Wl,-Bdynamic  -lSDL2  -lwx_baseu-3.1  -llibexpat.a>  -lwxregexu-3.1  -lsecret-1  -lc  -ldl  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/liblzmad.a  -lpthread  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/libjpeg.a  -lm  /home/be/sw/vcpkg/installed/x64-linux/debug/lib/libz.a && cd /home/be/sw/tenacity/build/libraries/lib-string-utils && echo -x /home/be/sw/tenacity/build/shared/Debug/lib-string-utils.so && cd /home/be/sw/tenacity/build/libraries/lib-string-utils && /usr/bin/cmake -E copy /home/be/sw/tenacity/build/shared/Debug/lib-string-utils.so /home/be/sw/tenacity/build/bin/Debug//lib64/audacity/lib-string-utils.so
/usr/bin/ld: cannot find -ljpeg
/usr/bin/ld: cannot find -llibpng.a
/usr/bin/ld: cannot find -llibtiff.a
collect2: error: ld returned 1 exit status
[2/506] Linking CXX shared library shared/Debug/lib-strings.so
```
It turns out this is a bug in the hacky wx-config script. One of the vcpkg maintainers is [working on a fix](https://github.com/microsoft/vcpkg/pull/18580) and opened a [PR for upstream wxWidgets](https://github.com/microsoft/vcpkg/pull/18580). I checked out that vcpkg branch with the unmerged patch, and lib-strings links, but then Tenacity has more build failures...
```
[352/717] Building CXX object src/CMakeFiles/Audacity.dir/AboutDialog.cpp.o
FAILED: src/CMakeFiles/Audacity.dir/AboutDialog.cpp.o 
/usr/bin/ccache /usr/bin/c++ -DAUDACITY_DLL_API="" -DAudacity_EXPORTS -DBUILDING_AUDACITY -DCMAKE -DEXPERIMENTAL_DRAGGABLE_PLAY_HEAD -DEXPERIMENTAL_EASY_CHANGE_KEY_BINDINGS -DEXPERIMENTAL_EFFECT_MANAGEMENT -DEXPERIMENTAL_FULL_WASAPI -DEXPERIMENTAL_HALF_WAVE -DEXPERIMENTAL_KEY_VIEW -DEXPERIMENTAL_MODULE_PREFS -DEXPERIMENTAL_NOISE_REDUCTION -DEXPERIMENTAL_NOTETRACK_OVERLAY -DEXPERIMENTAL_NYQUIST_SPLIT_CONTROL -DEXPERIMENTAL_PUNCH_AND_ROLL -DEXPERIMENTAL_REALTIME_AUDACITY_EFFECTS -DEXPERIMENTAL_SCIENCE_FILTERS -DEXPERIMENTAL_SCROLLING_LIMITS -DEXPERIMENTAL_SCRUBBING_SCROLL_WHEEL -DEXPERIMENTAL_SCRUBBING_SUPPORT -DEXPERIMENTAL_SPECTRAL_EDITING -DEXPERIMENTAL_SYNC_LOCK -DEXPERIMENTAL_THEMING -DEXPERIMENTAL_TWO_TONE_TIME_RULER -DEXPERIMENTAL_ZERO_PADDED_SPECTROGRAMS -DEXPERIMENTAL_ZOOM_TOGGLE_BUTTON -DHAVE_LRINT -DHAVE_LRINTF -DHAVE_MLOCK -DSTRINGS_API="" -DSTRING_UTILS_API="" -DUTILITY_API="" -DWXUSINGDLL -D__WXGTK3__ -D__WXGTK__ -Isrc/private -I../include -I../src -I../lib-src/libnyquist/. -I../libraries/lib-string-utils -I../libraries/lib-strings -I../libraries/lib-utility -isystem /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/lib/wx/include/gtk3-unicode-static-3.1 -isystem /home/be/sw/vcpkg/packages/wxwidgets_x64-linux/include/wx-3.1 -isystem /home/be/sw/vcpkg/installed/x64-linux/include -isystem /usr/include/gtk-3.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/harfbuzz -isystem /usr/include/freetype2 -isystem /home/be/sw/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../../include -isystem /home/be/sw/vcpkg/installed/x64-linux/debug/lib/pkgconfig/../../../include/libpng16 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -isystem /usr/include/libxml2 -isystem /usr/include/cairo -isystem /usr/include/pixman-1 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/cloudproviders -isystem /usr/include/atk-1.0 -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib64/dbus-1.0/include -isystem /usr/include/at-spi-2.0 -pthread -g -include /home/be/sw/tenacity/build/src/private/configunix.h -DAUDACITY_VERSION=3 -DAUDACITY_RELEASE=0 -DAUDACITY_REVISION=4 -DAUDACITY_MODLEVEL=0 -DAUDACITY_VERSION_STRING=L\"3.0.4-alpha\" -DAUDACITY_FILE_VERSION=L\"3,0,4,0\" -DPROHIBITED==delete -Dsafenew=new -DWXINTL_NO_GETTEXT_MACRO -D_DEBUG=1 -DIS_ALPHA -DUSE_ALPHA_MANUAL -pthread -std=gnu++17 -MD -MT src/CMakeFiles/Audacity.dir/AboutDialog.cpp.o -MF src/CMakeFiles/Audacity.dir/AboutDialog.cpp.o.d -o src/CMakeFiles/Audacity.dir/AboutDialog.cpp.o -c ../src/AboutDialog.cpp
../src/AboutDialog.cpp: In member function ‘void AboutDialog::PopulateInformationPage(ShuttleGui&)’:
../src/AboutDialog.cpp:589:19: error: no matching function for call to ‘AboutDialog::AddBuildinfoRow(wxTextOutputStream*, TranslatableString, wxString)’
  589 |    AddBuildinfoRow(&informationStr, XO("Commit Id:"), REV_IDENT );
      |    ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/AboutDialog.cpp:29:
../src/AboutDialog.h:68:9: note: candidate: ‘void AboutDialog::AddBuildinfoRow(wxTextOutputStream*, const wxChar*, const TranslatableString&, const TranslatableString&)’
   68 |    void AddBuildinfoRow( wxTextOutputStream *str, const wxChar * libname,
      |         ^~~~~~~~~~~~~~~
../src/ [...]

2021-07-14 19:49 UTC, Be-ing commented
I built wxWidgets 3.1.5 manually without vcpkg and Tenacity built with it. The scaling of the buttons is fixed:
![image](https://user-images.githubusercontent.com/9455094/125683825-53a1f8b3-d7e9-483a-aacd-952df2af1b90.png)

2021-07-14 21:31 UTC, Be-ing commented
I tried manually building wxWidgets 3.1.5 on the Ubuntu GitHub Actions runner, but building Tenacity failed with:

```
/usr/include/c++/9/bits/unique_ptr.h: In instantiation of ‘typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = wxBitmap; _Args = {const char* const* const&, int}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<wxBitmap>]’:
/home/runner/work/tenacity/tenacity/src/MixerBoard.cpp:1309:59:   required from here
/usr/include/c++/9/bits/unique_ptr.h:857:30: error: invalid conversion from ‘const char* const*’ to ‘int’ [-fpermissive]
  857 |     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              const char* const*
In file included from /usr/local/include/wx-3.1/wx/bitmap.h:280,
                 from /usr/local/include/wx-3.1/wx/generic/icon.h:14,
                 from /usr/local/include/wx-3.1/wx/icon.h:37,
                 from /usr/local/include/wx-3.1/wx/iconbndl.h:16,
                 from /usr/local/include/wx-3.1/wx/toplevel.h:21,
                 from /usr/local/include/wx-3.1/wx/frame.h:18,
                 from /home/runner/work/tenacity/tenacity/src/MixerBoard.h:17,
                 from /home/runner/work/tenacity/tenacity/src/MixerBoard.cpp:13:
/usr/local/include/wx-3.1/wx/gtk/bitmap.h:69:19: note:   initializing argument 1 of ‘wxBitmap::wxBitmap(int, int, int)’
   69 |     wxBitmap( int width, int height, int depth = wxBITMAP_SCREEN_DEPTH )
      |               ~~~~^~~~~
make[2]: *** [src/CMakeFiles/Audacity.dir/build.make:762: src/CMakeFiles/Audacity.dir/MixerBoard.cpp.o] Error 1
```

So I tried building the audacity-fixes-3.1.3 branch of the [fork](https://github.com/tenacityteam/wxWidgets), but then Tenacity fails to build with a different error:

```
[ 55%] Building CXX object src/CMakeFiles/Audacity.dir/LabelDialog.cpp.o
In file included from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:30,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from /home/runner/work/tenacity/tenacity/src/KeyboardCapture.cpp:19:
/usr/include/gtk-3.0/gdk/gdktypes.h:143:39: error: conflicting declaration ‘typedef struct _GdkWindow GdkWindow’
  143 | typedef struct _GdkWindow             GdkWindow;
      |                                       ^~~~~~~~~
In file included from /usr/local/include/wx-3.1/wx/event.h:14,
                 from /home/runner/work/tenacity/tenacity/src/KeyboardCapture.h:17,
                 from /home/runner/work/tenacity/tenacity/src/KeyboardCapture.cpp:11:
/usr/local/include/wx-3.1/wx/defs.h:2926:33: note: previous declaration as ‘typedef struct _GdkDrawable GdkWindow’
 2926 |     typedef struct _GdkDrawable GdkWindow;
      |                                 ^~~~~~~~~
```

This is exhausting. I'm not sure how much more energy I can put into this.

2021-07-16 17:43 UTC, SFR-git commented
Here are manifests for a [modified Arch Linux build](https://paste.sr.ht/blob/110857ed8f1a9185336a3d89152e7d939620febb) and a *brand new* [Alpine build](https://paste.sr.ht/blob/8111364059bea683e9aabc3ad75586a161e4fef4), utilizing native distribution libraries. They're definitely not optimized, but I tried to get them to the bare minimum of "working".

They're very slow because they build wxWidgets, but once we set up caching on sourcehut this is going to get faster.

I'd be glad to send the patch through email or push to your branch.

2021-07-16 17:50 UTC, Be-ing commented
Take a look at the [GH Actions workflow on this branch](https://github.com/tenacityteam/tenacity/pull/228/files#diff-972f46383ddae3d249353b0b6d89fe421260bcb22e48fc94ff36da8628cbfd5eR116) for how I am using ccache for the wxWidgets build.

2021-07-16 17:54 UTC, SFR-git commented
SourceHut has yet to implement caches, so in the meantime we're going to have to use an external server (cc @Semisol).

2021-07-16 17:55 UTC, AnotherFoxGuy commented
sccache has remote storage options:
https://github.com/mozilla/sccache#storage-options

2021-07-16 18:25 UTC, SFR-git commented
Interesting, but that's outside the scope of this PR regardless. The important thing is that we have sourcehut CI working.

2021-07-25 12:42 UTC, SFR-git commented
What else needs to be done before this PR is ready for review?

2021-07-26 13:24 UTC, Be-ing commented
Some dependencies are still not linking, for example FFmpeg. Also vcpkg needs to be set up for Windows and macOS.

2021-08-01 00:50 UTC, Be-ing commented
:tada:
![A badge that says "Works on my machine"](https://user-images.githubusercontent.com/9455094/127755648-03cad155-0828-4041-8b1c-ace183f98351.png)

This works with all optional features using devendored libraries. Libnyquist is not currently possible to devendor because of the application code #including a private header from it as mentioned above. Now, to get it working with vcpkg...

2021-08-01 02:52 UTC, Be-ing commented
Prerequisite PR to fix building with wxWidgets from vcpkg: https://github.com/microsoft/vcpkg/pull/19274

2021-08-06 02:22 UTC, Be-ing commented on src/Experimental.cmake
> +   #MIDI_OUT
This is what breaks the build with PortAudio. It looks like Audacity is working on fixing that:
https://github.com/audacity/audacity/pull/1431

2021-08-07 21:43 UTC, emabrey requested changes

2021-08-07 21:43 UTC, emabrey commented on .gitmodules
> +	url = git@github.com:Be-ing/vcpkg.git
Change to https://github.com/tenacityteam/vcpkg please.

2021-08-08 09:59 UTC, Be-ing commented
Progress update:
Builds are working now on Linux and macOS. Unfortunately there are still several bugs with the vcpkg port for wxwidgets: 
https://github.com/microsoft/vcpkg/pull/17111 https://github.com/microsoft/vcpkg/pull/19274
For now wxWidgets 3.1 needs to be built manually on CI because neither Ubuntu nor Arch package it. The Ubuntu builds on GitHub Actions are using vcpkg for dependencies except for wxWidgets, GTK, and GLib. The Arch builds are using Arch packages except for wxWidgets. With caching, Linux and macOS builds take about 5 minutes, which is the same as the master branch.

I have added a CMake option `VCPKG` which can be `ON` or `OFF` to use vcpkg for dependencies. It defaults to `ON` for Windows and macOS. For Linux, to use vcpkg, just configure CMake with `cmake -D VCPKG=ON`. This will clone the vcpkg Git submodule if you haven't already, then vcpkg's CMake toolchain file builds the vcpkg executable (although on Windows it downloads a prebuilt one) which then builds dependencies during the CMake configuration step (this can be done ahead of time by running `vcpkg install` as well if you prefer). If you prefer to have the vcpkg repo in a different location, you can pass another option to CMake `VCPKG_ROOT` with the path to your vcpkg repository.

The bugs in the vcpkg wxwidgets port don't seem to be affecting Windows, so Windows builds are using wxWidgets from vcpkg. There are still some link errors to resolve with Windows.

2021-08-10 16:51 UTC, Be-ing commented
Finally this is building on Linux, macOS, and Windows with caching. CI job times are the same as master at 5 minutes for Linux and macOS and 10 minutes for Windows. SourceHut CI with Arch Linux packages takes 15 minutes due to caching not being implemented in SourceHut.

vcpkg is automatically set up and used by default on macOS and Windows. It can also be used on Linux by passing `-D VCPKG=ON` to the CMake configuration command. I have rewritten BUILDING.md to explain this in more detail. Please review and test this yourself on different OSes.

2021-08-10 18:13 UTC, Semisol approved these changes, later dismissed
![image](https://user-images.githubusercontent.com/45574030/128912865-35b74c5e-ea75-4124-b396-44cb9ef8a4ed.png)

2021-08-10 18:13 UTC, Be-ing commented
What OS does your machine run, @Semisol?

2021-08-10 18:14 UTC, Semisol commented
macOS Big Sur

2021-08-10 18:26 UTC, SFR-git commented
Are the commits neatly split? This big a change definitely warrants more than 1 commit, but I won't blame you for not wanting to review *1 million deleted lines*.

2021-08-10 18:27 UTC, Be-ing commented
I split the commits as much as possible without having broken commits. The deletion of the vendored dependencies and the cmake-proxies hacks are both split into their own commits.

2021-08-10 18:30 UTC, SFR-git commented
> I split the commits as much as possible without having broken commits. The deletion of the vendored dependencies and the cmake-proxies hacks are both split into their own commits.

Could you clean up the commit messages then? Capital first letter, 50 chars, 72 for description, etc.

2021-08-10 19:14 UTC, Semisol commented
Current status:

- [ ] Windows
    - 10, wx from vcpkg, vcpkg on
- [ ] macOS
	- Big Sur, wx from Homebrew, vcpkg on
- [ ] Linux
	- [ ] Arch
	- [ ] Fedora
	- [ ] Ubuntu
		- [ ] elementaryOS (in progress)
			- wx from source, vcpkg on
	- [ ] Something else? Add it here

2021-08-10 20:20 UTC, SFR-git commented on BUILDING.md
> +#### Debian, Ubuntu, and derived distributions:
Nitpick: why's there a colon here but not in the Fedora or Arch headers

2021-08-10 20:20 UTC, Be-ing commented on BUILDING.md
> +#### Debian, Ubuntu, and derived distributions:
good catch

2021-08-10 21:57 UTC, SFR-git requested changes
I think the lines in BUILDING.md should be hardwrapped at 80 characters; it's very hard to read or review long paragraphs when they're all on one line.

2021-08-10 21:59 UTC, Be-ing commented
I could do that. Or alternatively, another way I've worked with Markdown documents for review in Git is by breaking lines for each sentence.

2021-08-10 22:16 UTC, Be-ing commented
Okay, I wrapped BUILDING.md at 80 characters.

2021-08-10 22:24 UTC, SFR-git submitted a review, later dismissed
`BUILDING.md` and `.builds/archlinux.yml` look good, but I'm not innately qualified to review the rest.

2021-08-11 16:20 UTC, akleja commented
I'm having some issues building on my Arch system: [build.log](https://github.com/tenacityteam/tenacity/files/6969655/build.log)
I installed wxWidgets from the AUR package, and the rest of the dependencies from the standard repos.
There's also a small typo in `BUILDING.md:48` where the export command is passed as an argument for paru.

2021-08-11 16:57 UTC, Be-ing commented
Arch has outdated packages for portSMF and libsbsms that do not work with Tenacity. I will add CMake options to disable these.

2021-08-11 17:06 UTC, Be-ing commented
Can you post the contents of the pkgconfig files for portsmf and sbsms in Arch? Maybe we could detect the version of those and exclude them.

2021-08-11 17:14 UTC, SFR-git commented
> Arch has outdated packages for portSMF and libsbsms that do not work with Tenacity. I will add CMake options to disable these.

The Arch repositories have a "flag as outdated" button to let the maintainers know, I'd recommend doing that

2021-08-11 17:18 UTC, Be-ing commented
As I said on Matrix, I can't for AUR packages. I have already done so for portmidi and portsmf.

2021-08-11 17:37 UTC, akleja commented
Ah okay I see they're both flagged as out-of-date.
portsmf version: 234-2
sbsms version: 2.0.2-3 (from the aur)
I'm not sure what the pkgconfig files are, do you mean the pkgbuild files?

2021-08-11 17:41 UTC, crsib commented
>portsmf version: 234-2

PortSMF 234 is the latest version. I would say it is 10 years newer than the latest version. 

PortSMF and PortMIDI live in the same SourceFourge project - PortMedia. All the latest commits to it were to PortMidi and only to the PortMidi build scripts (besides 218, that fixed Win64)

2021-08-11 17:43 UTC, Be-ing commented
We have forked [PortSMF](https://github.com/tenacityteam/portsmf) and the latest version is 236. Likewise the latest version of [PortMidi](https://github.com/mixxxdj/portmidi) is 236.

2021-08-11 17:49 UTC, Be-ing commented
>  I'm not sure what the pkgconfig files are, do you mean the pkgbuild files?

pkgconfig files provide metadata about libraries and are typically installed to /usr/lib/pkgconfig. I see from the list of files installed by the Arch portsmf package that it is at /usr/lib/pkgconfig/portSMF.pc. If that includes the version, I can check if portSMF is too old.

2021-08-11 17:49 UTC, crsib commented
SourceForge still has 234. https://sourceforge.net/p/portmedia/code/commit_browser

Do you plan to ask package maintainers to switch to your upstream instead of Rogers?

2021-08-11 17:50 UTC, Be-ing commented
They have already [expressed interest in doing so](https://github.com/mixxxdj/portmidi/pull/2#issuecomment-882078998).

2021-08-11 18:43 UTC, Be-ing commented
For now I have removed portsmf from the package list for Arch and added a TODO note to BUILDING.md to put it back when the package is updated. This should fix the build for Arch users copying and pasting the commands. I have also added and documented CMake options for all the optional features so users can explicitly disable them even if the required libraries are found.

2021-08-11 19:00 UTC, akleja commented
Contents of `portSMF.pc`
```
libdir=/usr/lib
includedir=/usr/include/portsmf

Name: portSMF
Description: Portmedia Simple Midi File library
Requires: 
Version: 0.1

Libs: -L${libdir} -lportSMF 
Cflags: -I${includedir} -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -Wall
```

2021-08-11 19:04 UTC, Be-ing commented
Ugh, PortSMF didn't really have versions before... I don't know why the version in the pkgconfig file is 0.1... I doubt it's a great idea to rely on that. For now I recommend just not installing the portsmf package for Arch users until the package is updated. Or you can pass `-D MIDI=OFF` to CMake.

2021-08-11 19:56 UTC, Be-ing commented
@akleja can you confirm you are able to build this branch on Arch either by uninstalling the portsmf package or using `-D MIDI=OFF`?

2021-08-11 20:30 UTC, Be-ing commented
@emabrey expressed interest in reviewing this. Let's wait for that, then I think this is ready for merging.

2021-08-11 20:31 UTC, Be-ing commented
@AnotherFoxGuy do you want us to wait for your review as well?

2021-08-11 20:47 UTC, akleja commented
I removed packages portsmf and sbsms and then it built fine.
I also had no issues with the vcpkg build.

I didn't try -DMIDI_OFF but I could in a little while

2021-08-11 20:49 UTC, Be-ing commented
> I didn't try -DMIDI_OFF but I could in a little while

There is no need. I just wanted to confirm the instructions in BUILDING.md work verbatim without any caveats.

2021-08-11 20:51 UTC, AnotherFoxGuy commented
> do you want us to wait for your review as well?

I don't think that I'm going to review this, because I think this pr makes the build system even more fragile and complicated to maintain than it was with conan

2021-08-11 20:55 UTC, akleja commented
> > I didn't try -DMIDI_OFF but I could in a little while
> 
> There is no need. I just wanted to confirm the instructions in BUILDING.md work verbatim without any caveats.

I did before I read this and it built fine as well

2021-08-12 06:29 UTC, panos requested changes, later dismissed
I can't review this fully because of the GitHub GUI and because of how my skillset limits me, but I did share a couple of concerns. I used to package things for Haiku every now and then, and I can agree that sometimes the `Find*.cmake` files were the hardest with, but that can be worked on. if a need like that arises.

With that being said, I'd like to encourage @AnotherFoxGuy to review and talk about why this approach is going to be more fragile, because their opinion is probably three times more valuable than mine and we probably don't want to mess this up.

2021-08-12 06:29 UTC, panos commented on cmake-modules/FindUUID.cmake
> +Finds the UUID library.
Sorry to be so blunt but, uh, nope. :D (The library has already been removed as well completely from the tree for obvious reasons...)

2021-08-12 06:29 UTC, panos commented on .gitmodules
> +	url = https://github.com/tenacityteam/vcpkg.git
Are we sure we're not repeating history here by using our own forks that nobody will ever, ever package?

2021-08-12 06:29 UTC, panos commented on lib-src/header-substitutes/allegro.h
> +#ifdef PORTSMF_CAPITAL
This isn't a change request but I just wanted to take a second to say "jeez, the fact that we have to do this is awful".

2021-08-12 06:42 UTC, Be-ing commented on cmake-modules/FindUUID.cmake
> +Finds the UUID library.
good catch

2021-08-12 06:43 UTC, Be-ing commented on lib-src/header-substitutes/allegro.h
> +#ifdef PORTSMF_CAPITAL
Yup. This is because PortSMF didn't really have a build system or releases before. Its documentation advised vendoring it. So Linux distros installed the headers to different paths :upside_down_face:

2021-08-12 06:54 UTC, Be-ing commented on .gitmodules
> +	url = https://github.com/tenacityteam/vcpkg.git
The vast majority of packages come from upstream vcpkg. This is using a fork which has a handful of packages in an [overlay](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) to override and add to what is available in upstream vcpkg. Of course I am working on upstreaming all the ports in the overlay. When they are merged to upstream vcpkg, they can be removed from the overlay. Updating the rest of the packages that are not in the overlay is trivially easy; all it takes is merging the latest updates from the upstream vcpkg master branch.

Most of the ports in the overlay are also in Mixxx's overlay; indeed, I verbatim copied some. Also, many of the other dependencies in upstream vcpkg are shared with Mixxx. So I would be maintaining these even if Tenacity did not use vcpkg, as well as other Mixxx developers.

2021-08-12 06:56 UTC, AnotherFoxGuy commented
> I'd like to encourage @AnotherFoxGuy to review and talk about why this approach is going to be more fragile

TLDR; The biggest issue I have with this PR is depending on `FindXXX.cmake` files for finding libraries
In the 8 years I've worked with cmake I never found them reliable to use, they just seem to do whatever they like and if they break they are extremely difficult to debug 

Also, vcpkg looks incredible fragile to me, since it apparently immediately breaks if cmake outputs the wrong line endings

2021-08-12 07:08 UTC, panos commented on .gitmodules
> +	url = https://github.com/tenacityteam/vcpkg.git
Thanks for explaining this to me.

2021-08-12 07:10 UTC, panos commented
Yeah, I think we both can very much agree on the things you just said based on our own experiences. However, I'm not sure if there's a better solution OR if Audacity's idiosyncrasies were better, though.

2021-08-12 07:10 UTC, Be-ing commented
> In the 8 years I've worked with cmake I never found them reliable to use, they just seem to do whatever they like and if they break they are extremely difficult to debug

I do not understand this concern. The find modules indeed do whatever they want; that is the point. These find modules first look for libraries and headers using pkgconfig and fall back to simply looking for the files if the pkgconfig file is not there. They can be written to handle whatever weird edge cases they need to, for example different Linux distributions installing PortSMF headers to `/usr/include/portsmf` versus `/usr/include/portSMF`. The alternative would be to have all that complexity in a gigantic CMakeLists.txt.

This branch is working and the build instructions have been validated on Fedora, Ubuntu, Arch, macOS, and Windows (except we're still working out one detail about Windows on Matrix right now), so I don't understand the concern about fragility.

2021-08-12 07:20 UTC, AnotherFoxGuy commented
> The find modules indeed do whatever they want; that is the point.

That is why I prefer Conan, it bypasses this mess entirely and knows where and what header locations/libraries a package has and generates absolute paths to it so you know it is the correct configuration


> I don't understand the concern about fragility

Well, I saw on Matrix that you needed to uninstall some system packages, because they were outdated and the find scripts found them instead of the ones included in vcpkg

2021-08-12 07:24 UTC, Be-ing commented
> That is why I prefer Conan, it bypasses this mess entirely and knows where and what header locations/libraries a package has and generates absolute paths to it so you know it is the correct configuration

That's irrelevant on Linux where people do not want to use Conan. It may be possible to use Conan in a better way than the mess Audacity set up, but that's something I do not like about Conan. There are so many different ways to use it -- which one is the best way? I don't care to research each and experiment. I just want it to work, and now it is with vcpkg.

> Well, I saw on Matrix that you needed to uninstall some system packages, because they were outdated and the find scripts found them instead of the ones included in vcpkg

No this was because of the really hacky build system in master using Conan.

2021-08-12 07:29 UTC, Be-ing commented
I want to emphasize that unlike the really hacky build system in master, this is not inherently tied to vcpkg. The current build system in master requires a bunch of hacks in Tenacity's CMake scripts to support Conan. By contrast, in this branch, the same CMake scripts work with Linux distribution packages and vcpkg without any special case handling for vcpkg. So hypothetically other package managers could be used with this on Windows or macOS, but I don't think there's much of a point doing that when vcpkg is working.

2021-08-12 07:37 UTC, AnotherFoxGuy commented
> I don't care to research each and experiment

Good thing that I've used Conan for the past 3 years, so I know which ones work the best in specific cases 

> The current build system in master requires a bunch of hacks in Tenacity's CMake scripts to support Conan

Well, I prefer a "bunch of hacks" in cmake to have a reproducible build system than one that does whatever it likes

2021-08-13 12:51 UTC, panos commented
Do we have some sort of middle ground here? Conan works in some cases, CMake header detection hacks work in some cases, both don't work in some other cases, why not support both? Worst case scenario, both of these solutions won't work for a specific distribution, and they'll just send in a patch that will make things better. Not sure why it's "one or the other", Conan was made optional instead of being removed for a good reason. (Or if it wasn't, we can now come up with one!)

2021-08-13 13:00 UTC, panos commented
We don't really have to end up tearing each other apart to recognize that most of the things in the Audacity build system were a disaster and that some of their ideas can't have been this bad after all.

I never got Conan to work on another system (see [here](https://xkcd.com/1987/)) (which explains my personal prejudice), but it worked splendidly on my Arch Linux system. My only real concern here now is that if we restrict ourselves to Conan, that could probably mean that we wouldn't get picked up by Linux distributions. IDK. What I want to say is that both of these solutions have very valid and prevalent uses for our project and we shouldn't be aggressive towards each other because of something that pretty much boils down to personal preference. It's counterproductive, we don't have anything to lose here.

2021-08-13 13:48 UTC, Be-ing commented
Supporting multiple package managers for Windows and macOS is the worst of all options and pointless.

> we shouldn't be aggressive towards each

I'm confused. I don't see any aggression in this discussion. We're having a discussion about technical matters. I don't think @AnotherFoxGuy is going to agree that vcpkg is a better solution than Conan and that's fine. He has already said (on Matrix, not this PR, so maybe you missed it) he's fine with switching to vcpkg so long as someone else maintains it. So I don't understand what problem you're trying to solve by continuing to discuss Conan @panos.

2021-08-14 06:10 UTC, panos commented
> So I don't understand what problem you're trying to solve by continuing to discuss Conan @panos.

My bad.

2021-08-14 13:47 UTC, leio commented
This built for me fine on Gentoo with no PortSMF there (guess MIDI is automagic here now) against wxGTK-3.0, after I put my stuff from #300 on top, changed toplevel CMakeLists.txt from 3.1 to 3.0 in wx and temporarily disabling a part of commit c0c275ffafcd8, as that now needs more 3.0 support work to act correctly there.

I have not reviewed any of it for code, as cmake is just a mystery to me that I don't care to learn over meson. But it seems to work fine and looking forward for this going in, so I can formalize my #300 on top of it for the ready parts and work on the rest in a way that allows me to actually build, unlike current master.

2021-08-15 15:26 UTC, Be-ing commented
Ready for merge finally.

2021-08-15 16:24 UTC, Be-ing commented
macOS link warnings are resolved now. vcpkg dependencies, wxWidgets, and Tenacity are all built for a minimum macOS version of 10.12.

Windows Debug builds are working too.

2021-08-16 02:29 UTC, emabrey reviewed
It took me a few hours but I have reviewed every... single... change.

2021-08-16 02:29 UTC, emabrey commented on .github/workflows/cmake_build.yml
> +          os: ubuntu-20.04
Do we want to use `os: ubuntu-latest` instead?

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindFLAC++.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
This comment isn't accurate.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindFLAC.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue as FLAC++.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindPortSMF.cmake
> +    set(PORTSMF_CAPITAL 1)
This variable should be cached, I think that will fix the issue with rebuild with different `CMAKE_BUILD_TYPE`.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindPortTime.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue as FLAC and FLAC++.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindSQLite3.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindSndFile.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindSoundTouch.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindSoxr.cmake
> +  pkg_check_modules(PC_Soxr QUIET flac)
Is this supposed to say flac?

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/FindTwolame.cmake
> +  pkg_check_modules(PC_Twolame QUIET flac)
Same, is this also supposed to say flac?

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/Findid3tag.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/Findlilv.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/Findmp3lame.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on cmake-modules/Findsuil.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Same comment issue.

2021-08-16 02:29 UTC, emabrey commented on scripts/ci/dependencies.sh
>          choco_packages=(
Should we add https://community.chocolatey.org/packages/ninja ?

2021-08-16 02:32 UTC, Be-ing commented on scripts/ci/dependencies.sh
>          choco_packages=(
No, it is included in MSVC.

2021-08-16 02:37 UTC, Be-ing commented on .github/workflows/cmake_build.yml
> +          os: ubuntu-20.04
:shrug:

2021-08-16 02:37 UTC, Be-ing commented on cmake-modules/FindSoxr.cmake
> +  pkg_check_modules(PC_Soxr QUIET flac)
nope, good catch

2021-08-16 02:48 UTC, Be-ing commented on cmake-modules/FindPortTime.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
Are these comments okay now?

2021-08-16 03:36 UTC, emabrey commented on cmake-modules/FindPortTime.cmake
> +# This file is part of Mixxx, Digital DJ'ing software.
👍🏻

2021-08-16 16:12 UTC, Be-ing commented
All optional features are building on Windows and macOS now with the exception of LV2 plugin hosting which requires suil. I'm not sure what to do about that so I [asked the suil maintainer](https://gitlab.com/lv2/suil/-/issues/3). I think figuring that out is beyond the scope of this pull request. Let's merge.

2021-08-16 17:38 UTC, AnotherFoxGuy commented
Could you also add the space requirements to BUILDING.md? you need at least 10GB on windows to build

2021-08-16 18:51 UTC, Be-ing commented
> Could you also add the space requirements to BUILDING.md? you need at least 10GB on windows to build

Done.

2021-08-17 12:08 UTC, Be-ing commented on cmake-modules/Findid3tag.cmake
> +  set (ZLIB_ROOT ${env}/bin)
This looks suspicious... are you sure this is necessary?

2021-08-17 12:31 UTC, Be-ing commented on cmake-modules/Findid3tag.cmake
> +  set (ZLIB_ROOT ${env}/bin)
Where does `${env}` come from? What is its value?

2021-08-18 00:42 UTC, merged

2021-08-18 02:27 UTC, Be-ing commented
Thanks to everyone who tested and reviewed, especially @emabrey! And thanks to @Holzhaus for originally writing many of the CMake find modules for Mixxx and introducing me to vcpkg.

2021-08-30 18:38 UTC, caughtquick commented
@Be-ing this appear to create a large increase in binary size, any idea why?

2021-08-30 18:57 UTC, AnotherFoxGuy commented
> this appear to create a large increase in binary size, any idea why?

The executable size has increased after this PR from 22MB to 361MB

2021-08-30 19:32 UTC, leio commented
Nothing is wrong with this PR in this regard, other than maybe the CI rules. The build defaults to CMAKE_BUILD_TYPE=Debug, and the CI workflows seem to set CMAKE_BUILD_TYPE=RelWithDebInfo. This ending up in a 300MB+ tenacity binary is expected when the debug information doesn't get split out into a separate -dbg or -debug package, which it probably isn't.

The cmake build system looks great to me, but the CI build rules may need some tweaking, either going to Release build type or doing the plumbing to split out debuginfo into a separate package like proper distro packages would do.

2021-09-01 15:51 UTC, Be-ing commented
I disagree. I think we should keep using RelWithDebInfo on CI. Distro packages can set the CMake build mode themselves according to their policies.

2021-10-07 10:06 UTC, RJVB commented
Quick question: is vcpkg (or your CMake logic calling it) clever enough to detect when dependencies are available? Audacity has logic to force the use of system-provided versions of its "vendored dependencies", it looks like you didn't keep that?

Context: I'm the maintainer of the Audacity port in MacPorts, and wondering if I'm going to have to spend a lot of time (and not-yet grey hairs ;)) trying to get your build system to behave "the MacPorts way", or rather spend that time finding and patching out the bad bits from the original code...
(Audacity's move to CMake made port maintenance a lot easier for me, in part because my feedback was heeded.)

2021-10-07 10:20 UTC, AnotherFoxGuy commented
> Quick question: is vcpkg (or your CMake logic calling it) clever enough to detect when dependencies are available?

Nope, it isn't. There are only two ways to build, using only system packages or using only vcpkg

2021-10-07 15:20 UTC, Be-ing commented
Yes there is an option for that: https://vcpkg.io/en/docs/users/manifests.html#vcpkg_prefer_system_libs

But I don't know why you would use vcpkg in a package for another package manager. vcpkg isn't even usable within most package managers because it requires a network connection. Downloads can be done ahead of time, but that's not really how it's intended to be used.