Add horizontal zooming/scrolling to "Plot Spectrum/Frequency Analysis" window
tenacityteam/tenacity-legacy pull request #229
Opened 2021-07-12 03:28 UTC by nyanpasu64

Also resolves pre-existing bugs (not reported):

- Zooming out doesn't clamp vertical scroll until next redraw ([video](https://youtu.be/CrzcWWTBoc4)).
- When resizing the window horizontally with a cursor active, the cursor remains on the same pixel but changes frequency ([video](https://youtu.be/aKZL80_Mrtw)).

This adds the ability to zoom and scroll the spectrum plot dialog (not track spectrogram) horizontally in frequency or period.

This makes larger FFT sizes more usable, since you can zoom into peaks which were previously too narrow to see the amplitude precisely. Additionally, you can zoom into regions of interest and hide unwanted portions of the spectrogram (like treble or in logarithmic scale, low bass).

![Screenshot of horizontally zooming into spectrum viewer](https://user-images.githubusercontent.com/913957/125222284-9a744580-e27e-11eb-8c44-d09f2359ef9c.png)

## Details

I rewrote the frequency viewer code to use `NumberScale` for converting between pixels and frequencies, instead of the hard-coded addition/multiplication loops used beforehand. This changes the exact shape of the plot slightly, even when not zoomed in. Using a `NumberScale` results in less rounding errors than repeated float32 addition or multiplication (and better plot accuracy for the right side of absurdly wide 16k-pixel-wide windows). I eliminated the `xMax-xStep` when computing the maximum value of the horizontal ruler, though I don't think it has an appreciable effect on the plot or cursor positioning (and doesn't affect the accuracy of peak-finding).

The primary motivation for this was because it simplified the process of zooming into part of the available frequency range. Additionally, it simplified the code and made it more declarative. This also makes it easy to add support for `NumberScale`'s Mel/Bark/ERB/Period scale modes in the future.

## Future improvements (not implemented yet, I may or may not implement)

- In the future, the spectrum plot could add options for Mel/Bark/ERB/Period scaling, instead of just linear and log.
- Zoom level is saved while Tenacity is open, but horizontal scrolling resets to centered when closing the dialog. This is no worse than vertical scale and zoom, but maybe it could be improved.
- Dragging the zoom slider now results in zooming in slightly to the left of the center of the plot ([video](https://youtu.be/P6AmwVeSxBI)).
	- This is because every change in zoom level recomputes the horizontal scrollbar's size and position, rounding the position down to the nearest integer. The rounding errors accumulate over many updates.
	- This needs to be solved by storing the intended center/boundaries of the viewport (either its frequency or position) independently of the scrollbar.
- Changing between linear and logarithmic scales, or changing FFT size, causes the plot to shift around. This is because the scrollbar position is maintained, not the minimum and maximum frequencies shown.
- Adding support for panning (dragging or middle-dragging), scrolling ([shift-]wheel), and/or zooming (ctrl-[shift-]scroll) into the plot.
	- My plan is for ctrl-scroll to zoom into the mouse cursor, rather than the center of the plot. This should make it easier to zoom into a particular part of the plot (generally low frequencies). However, computing changes to scrollbar position based on mouse position and scroll events (not just the current position of scrollbars and sliders) requires more planning to get right.

I'm still working on the best approach to solve the zoom together, which I will submit in a future pull request.

My currently planned approach (in a currently-private Google doc) involves storing extra information for the current zoom/frequency state, and having user action callbacks alter this state (in addition to resizing and positioning the scrollbar). The on-screen plot's viewport position/size will depend on internal state, rather than depending on the zoom slider and scrollbar widgets. Additionally, `FrequencyPlotDialog::DrawPlot()` will no longer set the scrollbar position, but only draw the plot.

## Potential issues

While testing my changes, I managed to get the GUI into a state where some of the widgets were stuck in place and glitched out behind other widgets when resizing the window vertically ([video](https://youtu.be/ZiLiS9O7-gU)). I have not been able to reproduce this since. It may be a pre-existing Wx/GTK bug.

On KDE, when closing the "Frequency Analysis" window when it's wider than the screen, the sides of the window can't be used to resize it until I've used the top/bottom or a corner to resize the window. I don't think this is related to my changes.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-12 05:45 UTC, panos commented
This is a considerably awesome PR! I haven't had the time to check it for myself yet, but I will. Thank you so much for your contribution!

(Note for other reviewers: May not be a good idea to squash and merge here.)

2021-07-12 12:09 UTC, fossdd requested changes
Are the variable re-names like `mPanScroller` to `vPanScroller` neseccary? Really nice contribution!

2021-07-12 17:35 UTC, nyanpasu64 commented
> Are the variable re-names like `mPanScroller` to `vPanScroller` neseccary?

If I don't rename `mPanScroller` to `vPanScroller`, what would you name `hPanScroller` and `hZoomSlider` to make it clear that it served as horizontal zoom/scale? Would you leave them at their current names?

Also would you not rename `FreqZoomSliderID` to `FreqVZoomSliderID` (and `FreqPanScrollerID`) either? What would you name `FreqHZoomSliderID` and `FreqHPanScrollerID` instead?

Another option for names is "frequency/freq" vs "amplitude/ampl", but I chose to go with h/v. Unfortunately, this would require renaming `FreqZoomSliderID` to `AmplZoomSliderID` (because it zooms amplitude), and adding a new `FreqZoomSliderID` (or a different name) for horizontal frequency (or period) zooming, which makes the diff misleading IMO.

----

My reason for renaming is:

- The names of `mPanScroller/ZoomSlider` make them sound like "the only" scrollbar/slider (which was the case prior to my PR).
- They don't clearly indicate "vertical". This is *somewhat* alleviated when placed next to `h` members. The current code only accesses `v` variables in vertical scrolling regions, and `h` variables in horizontal scrolling regions, which may/not be enough for other people to infer the purpose of these variables.
	- Whether I use `m` or `v`, I could add doc comments for the fields of FrequencyPlotDialog:
	  ```cpp
	     /// Vertical scrollbar.
	     wxScrollBar *mPanScroller;
	     /// Vertical zoom slider.
	     wxSlider *mZoomSlider;
	     // Horizontal scrollbar.
	     wxScrollBar *hPanScroller;
	     // Horizontal zoom slider.
	     wxSlider *hZoomSlider;
	  ```
	- This could make the code clearer (regardless of names chosen), or could be an attempt to workaround ambiguous variable names through comments. The downside is that it could produce more diff noise, and it would create more text to read, decreasing the signal-noise ratio (IMO OK by itself, but I think it'll be a problem if I try to document every single one of the 20-ish member variables):
- I tried renaming `v` back to `m` in my code to see how the result looked. The vertical scrolling code looks OK in isolation, and more similar to how it was before this PR.
	- However it's possible to use `mPanScroller` by mistake when computing horizontal scrolling and positioning, and it won't look obviously wrong. I don't know if I would've made this mistake, because I wrote my code *after* renaming `m` to `v`. So I don't know if this is an issue for others in the future (though I suspect so).
- Note that while writing this issue comment, and when I tried renaming my code to `m` and writing doc comments, I (twice) mistakenly wrote that the `m` variables were horizontal scrolling rather than vertical, before catching the mistake. IMO this is not a promising sign that the `m` variable names are sufficiently clear. Possibly it'll be less confusing to people working on the code who may have prior experience with this file, compared to my confusion when actively renaming `v` to `m`.

Is that a good justification?

----

If desired, I could rebase the commit history and avoid refactoring the existing vertical scrolling code (remove https://github.com/tenacityteam/tenacity/pull/229/commits/178572aadd73e3abf44ef19b56795ef39fbe4c52), except to fix bugs (by manually applying https://github.com/tenacityteam/tenacity/pull/229/commits/5be46fc0f8f80e4744c31f83384f33b5607895a2) (though the end result *might* be worse code). Or I could more aggressively rewrite that code to be more self-documenting and match my new horizontal scrolling more, and possibly even use an exponential vertical zooming formula rather than reciprocal zoom.

2021-07-17 08:24 UTC, fossdd submitted a review, later dismissed
Okay, all is fine. Really nice contribution.

2021-07-17 23:00 UTC, FugiMuffi approved these changes, later dismissed
very useful addition, works great for me!

2021-07-17 23:26 UTC, nyanpasu64 commented
Should I rebase on master?

2021-07-18 16:14 UTC, panos commented
Currently waiting on @nyanpasu64 to prepend `FreqWindow:` in each one of their commits, rebase and force-push, so that we can merge their entire branch at once. :D

2021-07-19 00:37 UTC, nyanpasu64 commented
force pushed, need to have workflows approved and code reviewed

2021-07-19 06:04 UTC, FugiMuffi approved these changes

2021-07-19 23:49 UTC, Be-ing approved these changes

2021-07-19 23:49 UTC, merged

2021-07-19 23:50 UTC, Be-ing commented
Nice work, thank you @nyanpasu64! It is great that we now have a feature that Audacity does not only because of their CLA pushing developers away. I hope you continue to add more. :)