Rebranding: Replace Audacity references in AudacityApp.cpp
tenacityteam/tenacity-legacy pull request #266
Opened 2021-07-14 19:18 UTC by panos

This includes the name used in the application, as well as directory paths, filenames and various comments. The change was authored with cautiousness to avoid conflicts with other proposed changes that revolve around rebranding.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-14 21:29 UTC, FugiMuffi approved these changes

2021-07-15 01:27 UTC, ajayyy requested changes

2021-07-15 01:27 UTC, ajayyy commented on src/AudacityApp.cpp
> +"Tenacity was not able to lock the temporary files directory.\nThis folder may be in use by another copy of Audacity.\n")
This is a key for translations. It can't be changed unless all the translation files are changed too. Most of the strings that look human readable are like that.

2021-07-15 02:52 UTC, emabrey commented on src/AudacityApp.cpp
> +"Tenacity was not able to lock the temporary files directory.\nThis folder may be in use by another copy of Audacity.\n")
Correct. Anything in an `XO` wrapper is a translatable `wxString`. `Verbatim` is used for raw strings AFAIK.

2021-07-15 03:04 UTC, ajayyy commented on src/AudacityApp.cpp
> +"Tenacity was not able to lock the temporary files directory.\nThis folder may be in use by another copy of Audacity.\n")
I noticed some other wrappers too such as `X` that also call the i18n code, which is why I was vague in my comment.

2021-07-15 04:13 UTC, fitojb commented on src/AudacityApp.cpp
> +"Tenacity was not able to lock the temporary files directory.\nThis folder may be in use by another copy of Audacity.\n")
> This is a key for translations. It can't be changed unless all the translation files are changed too. Most of the strings that look human readable are like that.

gettext's msgmerge command takes care of updating the POT and POs after a string is changed.

2021-07-15 07:02 UTC, panos commented on src/AudacityApp.cpp
> +"Tenacity was not able to lock the temporary files directory.\nThis folder may be in use by another copy of Audacity.\n")
> This is a key for translations. It can't be changed unless all the translation files are changed too. Most of the strings that look human readable are like that.

I'm aware of this, but the point is to replace the references in the source code first and *then* take on the translation files that have been a pain for us over the past few days. Is that not alright?

2021-07-21 17:58 UTC, emabrey commented
I've gotten this done in a different commit already. I'm going to close this PR.

2021-07-21 17:58 UTC, closed without merging