Updating sv.po
tenacityteam/tenacity-legacy pull request #285
Opened 2021-07-16 18:32 UTC by Gapstare

Resolves: *(direct link to the issue)*

Continuing with the translation to Swedish.

- [ ] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [ ] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-16 18:45 UTC, SFR-git commented
Please follow the [contributing guidelines](https://github.com/tenacityteam/tenacity/tree/master/CONTRIBUTING.md) and make sure all boxes are checked before opening a PR.

2021-07-16 19:12 UTC, emabrey commented on .github/workflows/cmake_build.yml
> +    branches:
Please do not change `cmake_build.yml`

2021-07-16 21:37 UTC, Gapstare commented on .github/workflows/cmake_build.yml
> +    branches:
> Please follow the [contributing guidelines](https://github.com/tenacityteam/tenacity/tree/master/CONTRIBUTING.md) and the template when opening a PR.

I have to compile the whole thing for translating too?



> Please do not change `cmake_build.yml`

Sorry, I did not know that I did. I did not touch the file manually. I tried to follow the contributing guidelines but perhaps I messed something up in the process.

There is a lot of mentions of Audacity that needs to be changed in one go and it's too tedious to do by hand on some website. That's why I opened this.

2021-07-17 08:08 UTC, SFR-git commented on .github/workflows/cmake_build.yml
> +    branches:
> > Please follow the [contributing guidelines](https://github.com/tenacityteam/tenacity/tree/master/CONTRIBUTING.md) and the template when opening a PR.
> 
> I have to compile the whole thing for translating too?

If you'd followed the template carefully, you would have learned that no, you don't. But that's not the only box left unchecked.

2021-07-17 08:36 UTC, fossdd requested changes

2021-07-17 08:36 UTC, fossdd commented on locale/sv.po
> +msgid "Tenacity needs the file '%s' to import and export audio via FFmpeg."
You changed the msg-ids of the translations. Please don't to that, the compiler doesn't know which which is. Please also try to compile it by translations. If you change stuff that doesn't effect in any way the compiler, like the README.md you don't have to.

2021-07-18 07:41 UTC, Gapstare commented
This is too complicated, good luck with the project.

2021-07-18 07:41 UTC, closed without merging

2021-07-18 08:02 UTC, panos commented
If it's of any help for the future with your open source endeavours, you can do the following:

Before making a commit:
- `git commit -m "hello jello" --signoff`

After making a commit:
- `git commit --amend --signoff`
- or `git rebase HEAD~1 --signoff` (replace 1 with the number of commits you want to sign off in the future)

As far as translations are concerned, we use [Weblate](https://hosted.weblate.org/projects/tenacity/tenacity/) in order to simplify the process. We appreciate your efforts, thanks and best of luck <3

2021-07-18 14:33 UTC, Gapstare commented
@panos Thanks for the tip, much appreciated. I have come to the conclusion that I will indeed use Weblate instead and someone that knows what they're doing can fix any hardcoded mentions of 'Audacity'. :slightly_smiling_face: