WIP: Restore compatibility with wxWidgets-3.0
tenacityteam/tenacity-legacy pull request #300
Opened 2021-07-18 11:18 UTC by leio

This restores compatibility with wxWidgets-3.0, but has the following things unhandled:

* AutoRecoveryDialog changes are not tested - this is the main thing that actually makes use of new wx3.1 GUI features and could use a closer look by someone, if 3.0 compat is to happen
* FileConfig change just makes the issue probably happen that the wx3.1 specific API call intends to solve, which is just removed in case of building against 3.0. It might be possible to solve this universally without this flushing hack, as the old comments allude to, but not sure it's worth it, as there are more important things to do and the regression doesn't seem too bad - plus 3.2 will hopefully be out by end of year anyhow. Though I do think relying on this DisableAutoSave behaviour is problematic for 3.2 too.
* I'm unsure if I got the hashing thing right, with the wxWidgets introduced one being slightly different than what I put in as something audacity had before to make this work with 3.0.
* This is not compile tested against master, as I don't have working conan build, so I worked on top of #228 with the wx dep reduced on top of that locally, to get it to accept my system wxGTK-3.0.5
* Relatedly it still misses a commit to reduce the minimum requirement in the build system, with things very much in flux re #228 and other pending things.

All that said: 
![Kuvatõmmis 2021-07-18 12-46-21](https://user-images.githubusercontent.com/133723/126065092-e0dfa179-5ef9-461c-a3a8-12eb512a8b4a.png)

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-18 13:44 UTC, leio commented
I had forgotten to expand on the AutoRecoveryDialog stuff:

The current code makes use of wxListCtrl::EnableCheckBoxes and co, which is new since wx3.1.0. It presumably allows to pick and choose which things to recover from the dialog, so if you had multiple projects open in a previous crash (or something), you could choose to recover only some of them. Earlier code in Audacity times did not use this stuff - it probably was an all or nothing choice then. When the 3.1 dependency got introduced there, it initially had a USE_CHECKBOXES preprocessor macro behind which this was in (albeit the preprocess macro was always defined at the top of the file, but probably undefining it worked too - so in my WIP commit I use the same #define, but make it conditional of wx version).

So the current code could be conditionally made to be without the checkboxes in case of 3.0 again, and have an all or nothing recovery behaviour, whereas with 3.1/3.2 it can be like it is. The WIP commit blindly does that, but I may be off with some indexes and I didn't think much of the logic beyond getting it to just compile. It is very likely broken at runtime.

The main purpose was to explore how hard it would really be to restore compatibility with stable wxWidgets releases, so that all linux distributions (including the one I as downstream maintainer refuse to package an ABI unstable wxGTK-3.1) would be able to package tenacity without waiting for wxWidgets 3.2 release near the end of 2021 (and given past experience, I think it slipping again to even more into the future wouldn't be a surprise at all).

The result of that exploration seems to be that it's not very hard at all to do this, really. Unfortunately I can not really put much more time into this. If no-one picks this up in my place, I think some of the commits may be useful regardless as-is here - probably all but the AutoRecoveryDialog one with minimal improvements still needed, if the eventual goal is to support 3.0 again for now; otherwise at least the very first commit about wxOVERRIDE makes sense in any case, in my opinion.

2021-07-18 14:56 UTC, Be-ing commented
Nice work. This diff doesn't look too big. I think it may be reasonable to pursue this.

2021-07-22 09:41 UTC, panos commented
This seems to be important in order to get Tenacity packaged on Void Linux.

The main reason that they're shipping an old version of Audacity right now is, a) wxWidgets 3.1, b) Conan.

2021-07-23 05:10 UTC, panos commented
Is there anything more that should be done that any of us could help with?

2021-07-23 08:27 UTC, leio commented
The main thing is that someone needs to figure out the AutoRecoveryDialog stuff to work cleanly with 3.0 too. I only made it build to map out how big a work in total it would be to make it build against 3.0, and I am quite sure it's broken at runtime after my WIP patch here. The good news was, that the rest was easy.

2021-07-23 11:43 UTC, leio commented
I think the correct long-term path forward with wxWidgets and AutoRecoveryDialog is to rewrite it to use wxDataViewCtrl instead of wxListCtrl. wxListCtrl is sort of deprecated (but I guess not really..) and wxDataViewCtrl is the preferred way. It also can offer us these checkboxes per row on top of wx3.0 as well just fine.
wxDataViewCtrl has a native UI implementation for wxGTK, wxQt and wxOSX, whereas wxMSW uses the generic version but with quite a bit of wxMSW specifics in there to make it good. wxListCtrl has a native implementation only for wxMSW and wxQt and upstream mostly considers wxDataViewCtrl to supersede wxListCtrl and co.

See also: https://github.com/wxWidgets/wxWidgets/pull/153#issuecomment-165091094

2021-07-31 14:47 UTC, Be-ing commented
I propose that we defer this for after the first Tenacity release.

2021-07-31 14:47 UTC, Be-ing commented
The "close and comment" button strikes again, despite the continued lack of need for its existence...

2021-07-31 14:53 UTC, SFR-git commented
> I propose that we defer this for after the first Tenacity release.

I disagree. Contacting downstreams and sorting out packaging for repositories is a necessary step before the first release, and using a widely-supported version of wxWidgets will make their job a whole lot easier.

2021-07-31 15:24 UTC, Be-ing commented
Well then someone needs to step up to finish this.

2021-07-31 15:59 UTC, leio commented
I won't have time to do this (just rewriting it with wxDataViewCtrl) before at least 1 or 2 more weekends. If it helps, I can extract the ready bits (everything but the recovery dialog) into another PR later today/tomorrow.

2021-07-31 16:05 UTC, Be-ing commented
Separating the parts that are ready into their own PRs would be helpful.

2021-08-08 10:06 UTC, panos commented
> I propose that we defer this for after the first Tenacity release.

We have time and other things to work on in the meantime, not merging this will mean that nobody will package us and we'll miss out on a great advantage.

2021-08-08 14:41 UTC, Be-ing commented
There are distributions packaging wxWidgets 3.1.

2021-08-13 15:06 UTC, panos commented
> There are distributions packaging wxWidgets 3.1.

About that... https://repology.org/project/wxwidgets/versions

2021-08-25 13:13 UTC, leio commented
I have the AutoRecoveryDialog port to wxDataViewListCtrl pretty much ready (works with 3.0 without losing the checkboxes), just some finishing touches and cleanups and testing after I get another couple of hours time for it, then it's ready for PR. So no need for others to look at helping with that anymore.

Currently left for 3.0 compat besides that:
* Figuring out problem with my initial TranslatableString compatibility (mentioned in self-review of #514)
* Making the newly added XDG paths stuff work with 3.0 (XDG layout doesn't exist in 3.0 yet, will need some 3.0 specific code; should be easy enough to handle, we've got glib functions we can depend on for now on wxGTK)
* Build system changes to accept 3.0 - mainly I'm not sure if it's just about lowering 3.1 to 3.0, or if that would make it not try 3.1 first anymore; if it just picks the wx-config it finds and checks that, then I guess there's actually nothing more to it.

2021-08-25 16:09 UTC, Be-ing commented
> Build system changes to accept 3.0 - mainly I'm not sure if it's just about lowering 3.1 to 3.0, or if that would make it not try 3.1 first anymore; if it just picks the wx-config it finds and checks that, then I guess there's actually nothing more to it.

We can run `find_package(wxWidgets 3.1)` first, then if that fails, fall back to `find_package(wxWidgets 3.0)`.

2021-08-25 16:18 UTC, leio commented
> We can run `find_package(wxWidgets 3.1)` first, then if that fails, fall back to `find_package(wxWidgets 3.0)`.

That's a bit surprising to me, but my info on this comes from 2008. Can I convince you to write that part for me cleanly? But note that I'm going to force push to the branch backing this PR probably later today, maybe a separate PR or just work branch from which I can cherry-pick from?

2021-08-25 17:55 UTC, Be-ing commented
> work branch from which I can cherry-pick from

Done: https://github.com/Be-ing/tenacity/commit/4fa24fa69532581b6b08cfef43a81023a964277c

2021-09-06 09:15 UTC, solfisher requested changes, later dismissed

2021-09-06 09:15 UTC, solfisher commented on BUILDING.md
> +wxWidgets 3.1 is suggested but not packaged in Alpine Linux. Refer to the
We should provide the wxWidgets 3.0 package name. It's `wxgtk(-dev?)` on Alpine, `wxgtk3` on Arch, and I'm not sure about the others.

2021-09-06 10:05 UTC, solfisher commented
This builds without errors on Arch and Alpine edge, just need to update `BUILDING.md` and then I'll approve

2021-09-06 10:45 UTC, leio commented
I added a little blurb for Alpine. I'm not sure how to do it for Arch, as it already has a 3.1 package listed apparently. I think it really depends on how strongly we want to suggest usage of 3.1 instead. With my downstream hat on, I don't think we should do that at all, and use and suggest stable 3.0; but otherwise I think it's probably good to target 3.1 in the hope that 3.2 will actually be out later this year as a stable cycle.

2021-09-06 14:44 UTC, Be-ing commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
This is no longer correct.

2021-09-07 05:41 UTC, solfisher commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
Is it? The [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wxwidgets-dev-light#n157) still seems to have it.

2021-09-07 14:52 UTC, Be-ing commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
It is a different path for wxWidgets 3.0.

2021-09-07 14:55 UTC, solfisher commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
Does the 3.0 binary get detected automatically, or do you need to export something else?

2021-09-07 15:50 UTC, Be-ing commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
This path is explicitly pointing to use wxWidgets 3.1. I don't know what the path is for 3.0. That needs to be tested by someone with an Arch installation.

2021-09-07 16:01 UTC, leio commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
I'm a bit confused; the changeset here doesn't even mention 3.0 for Arch, so why is it a problem to tell a 3.1 path, when the package listed for Arch IS 3.1?

2021-09-07 16:14 UTC, Be-ing commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
Oh, sorry, I got confused. The WX_CONFIG path should be documented if the user wants to use `wxgtk3` though.

2021-09-07 17:46 UTC, solfisher commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
`WX_CONFIG` should be set to `/usr/bin/wx-config-gtk3`, pushing a change now.

2021-09-07 17:47 UTC, solfisher commented on BUILDING.md
>  export WX_CONFIG=/usr/bin/wx-config-gtk3-3.1
sidenote: both Alpine and Arch use `wx-config-gtk3`, maybe we should try and autodetect that?

2021-09-07 18:05 UTC, solfisher commented
The AutoRecoveryDialog commits have been merged and can be removed from this PR

2021-09-08 19:34 UTC, Be-ing commented on libraries/lib-strings/TranslatableString.cpp
> +#if HAS_I18N_CONTEXTS
Where is this defined? I do not see it in CMakeLists.txt. Is it defined by wxWidgets?

2021-09-08 21:45 UTC, leio commented on libraries/lib-strings/TranslatableString.cpp
> +#if HAS_I18N_CONTEXTS
It's defined in `libraries/lib-strings/Internat.h` and the same file you are reviewing already used it from audacity legacies (they hadn't killed 3.0 support in the other path yet) one method down (`DoChooseFormat`), so I ended up replicating that other path here too - with the weird to me formatting, warts, and all.

2021-09-08 21:57 UTC, Be-ing commented on libraries/lib-strings/TranslatableString.cpp
> +#if HAS_I18N_CONTEXTS
okay

2021-09-11 09:09 UTC, n0toose approved these changes
Looks good to me!

Relevant resource provided by @leio when I asked for clarification regarding `wxCHECK_VERSION(3, 1, 1)`: https://docs.wxwidgets.org/3.0/group__group__funcmacro__version.html#gae7a4bbd65402259b17a664fe87f2ec17

2021-09-11 09:22 UTC, nbsp commented
I think that if this PR looks good, we should rewrite `BUILDING.md` to recommend using 3.0 -- instead of the changes we have now.

2021-09-11 09:25 UTC, n0toose commented
> I think that if this PR looks good, we should rewrite `BUILDING.md` to recommend using 3.0 -- instead of the changes we have now.

Using 3.0 may introduce some additional bugs, like the whole HiDPI spectacle, because that version just doesn't properly support that stuff properly.

2021-09-11 09:32 UTC, leio commented
I think we should/can tweak things afterwards, once this is merged. I plan to look into getting one of the CI builds to actually build against 3.0 instead of 3.1, etc.

2021-09-11 14:22 UTC, panos commented
Yep, let's not shed bikes!

2021-09-12 14:11 UTC, merged