Update `README.md` Github Actions badge
tenacityteam/tenacity-legacy pull request #320
Opened 2021-07-20 13:46 UTC by emabrey

The former badge URL was generating 500 series errors; so let's swap for a different one.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

2021-07-20 13:48 UTC, Semisol submitted a review, later dismissed
I don't see any 500 errors with the original but sure I guess.

2021-07-20 13:49 UTC, SFR-git commented
Could you squash the commits?

2021-07-20 13:49 UTC, emabrey commented
> 
> 
> I don't see any 500 errors with the original but sure I guess.

It was giving an error badge for me. And every few requests it would tell me that the serverless worker had crashed.

2021-07-20 13:50 UTC, Semisol commented
> Could you squash the commits?

Yep that is what I would want.

2021-07-20 17:31 UTC, SFR-git requested changes

2021-07-20 17:31 UTC, SFR-git commented on README.md
> +[![GitHub builds](https://badgen.net/github/status/tenacityteam/tenacity)](https://github.com/tenacityteam/tenacity/actions?query=branch%3Amaster)
Just noticed that this doesn't actually link to what we want. PRs from branches named `master` will also appear. Here's a fix: 

```suggestion
[![GitHub builds](https://badgen.net/github/status/tenacityteam/tenacity)](https://github.com/tenacityteam/tenacity/actions?query=branch%3Amaster+event%3Apush)
```

2021-07-23 21:13 UTC, SFR-git approved these changes

2021-07-24 16:14 UTC, fossdd approved these changes

2021-07-25 06:54 UTC, merged