Add hiDPI support for Windows
tenacityteam/tenacity-legacy pull request #327
Opened 2021-07-21 11:22 UTC by fossdd

Resolves: https://github.com/tenacityteam/tenacity/issues/168

Hopefully, adds hiDPI support for Windows. We still need to verify that with a real windows machine.

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

2021-07-21 18:51 UTC, emabrey commented
![image](https://user-images.githubusercontent.com/3370875/126543566-82f9b003-1a1a-471c-be23-4c816b28051c.png)
![image](https://user-images.githubusercontent.com/3370875/126543585-9c7a2e96-3c5e-4060-a93a-3e079bf3e747.png)

2021-07-21 19:03 UTC, emabrey commented
I test it on windows and it built but it won't start.

2021-07-21 19:26 UTC, AnotherFoxGuy commented
Also tested on windows, same issue

2021-07-23 14:45 UTC, SFR-git commented
This PR builds and launches fine for me on a Windows VM.

2021-07-23 18:46 UTC, fossdd commented
Okay, nice is hiDPI enabled? @SFR-git

2021-07-23 18:58 UTC, SFR-git commented
> Okay, awesome. Is HiDPI enabled? @SFR-git

I'm not sure? I've not really checked for it, I just wanted to see if it runs. The app looks fine both with and without the patch.

*Disclaimer: I've not used Windows in... a while.*

2021-07-23 19:21 UTC, emabrey commented
My monitor is 141.69 pixels/in (calculated it myself), which is considered hiDPI I believe. I built and started this build succesfully, and it seems much less blurry to me:

![image](https://user-images.githubusercontent.com/3370875/126831189-924be14e-f144-49b2-83cb-aee49cf27ebc.png)

2021-07-25 08:52 UTC, SFR-git commented
> I built and started this build succesfully, and it seems much less blurry to me:

Could you review this PR, then?

2021-07-26 07:23 UTC, emabrey approved these changes, later dismissed

2021-07-26 07:23 UTC, emabrey commented
> 
> 
> > I built and started this build succesfully, and it seems much less blurry to me:
> 
> Could you review this PR, then?

I thought I did. My bad.

2021-07-26 08:16 UTC, SFR-git commented
Unless someone else with a HiDPI monitor can test, I think we can merge this PR.

2021-07-26 09:34 UTC, FugiMuffi commented
The CI build does not launch on my system ("side by side configuration invalid")

2021-07-26 12:50 UTC, fossdd commented
> The CI build does not launch on my system ("side by side configuration invalid")

Which windows version do you use?

2021-07-26 12:51 UTC, FugiMuffi commented
> Which windows version do you use?

Windows 10 21H1 Build 19043.1110

2021-07-26 13:00 UTC, Fox2Code commented on win/Tenacity.exe.manifest
> +  <description>Tenacity Cross-Platform Sound Editor</description>">
the `">` at the end look like a typo

2021-07-26 13:19 UTC, FugiMuffi commented on win/Tenacity.exe.manifest
> +  <description>Tenacity Cross-Platform Sound Editor</description>">
```suggestion
  <description>Tenacity Cross-Platform Sound Editor</description>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
```
After changing this, it built successfully.

2021-07-26 13:34 UTC, fossdd commented on win/Tenacity.exe.manifest
> +  <description>Tenacity Cross-Platform Sound Editor</description>">
Okay, looks like ca8a67b16f2810d466e07a02c3c015f6c12474ff did the error. @FugiMuffi Please retry with f57559194

2021-07-26 13:37 UTC, SFR-git commented
Please squash on merge

2021-07-26 13:37 UTC, FugiMuffi commented on win/Tenacity.exe.manifest
> +  <description>Tenacity Cross-Platform Sound Editor</description>">
Did you remove that line on purpose? Without it that's not valid xml.
```xml
<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
```

2021-07-26 14:00 UTC, FugiMuffi requested changes

2021-07-26 14:00 UTC, FugiMuffi commented on win/Tenacity.exe.manifest
> -  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
This line was removed by accident by ca8a67b16f2810d466e07a02c3c015f6c12474ff.

2021-07-28 13:24 UTC, FugiMuffi approved these changes

2021-07-28 18:47 UTC, SFR-git approved these changes

2021-07-28 18:49 UTC, merged