🔧 Install conan using system pkg manager instead of pip
tenacityteam/tenacity-legacy pull request #369
Opened 2021-07-24 18:32 UTC by AnotherFoxGuy

This should install Conan a little faster than pip

<details>
<summary>Contributor stuff</summary>

:white_check_mark: The code in this pull request is licensed under "GPLv2 or any later version"\*
:white_check_mark: I made sure the code compiles on my machine
:white_check_mark: I made sure there are no unnecessary changes in the code\*
:white_check_mark: I made sure the title of the PR reflects the core meaning of the issue you are solving\*
:white_check_mark: I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

</details>

2021-07-24 19:19 UTC, SFR-git commented
Please do not replace the contribution checkboxes with emoji.

2021-07-24 19:22 UTC, SFR-git requested changes

2021-07-24 19:22 UTC, SFR-git commented on scripts/ci/environment.sh
> +gh_export GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
I assume that's your editor doing this automatically. Please install an EditorConfig plugin.

2021-07-24 19:26 UTC, SFR-git approved these changes, later dismissed

2021-07-24 19:30 UTC, fossdd requested changes

2021-07-24 19:30 UTC, fossdd commented on scripts/ci/dependencies.sh
> +        choco install sccache conan -y
Please use shell array for package listing like `pip_packages`

2021-07-24 19:30 UTC, fossdd commented on scripts/ci/dependencies.sh
> +    if which dpkg; then
Please put these commands inside "if which apt-get". ' If apt-get is installed dpkg is also. Please also try to use curl and pipe the ourpur into dpkg that no temp files are required.

2021-07-24 19:38 UTC, AnotherFoxGuy commented on scripts/ci/dependencies.sh
> +    if which dpkg; then
> Please also try to use curl and pipe the output into dpkg that no temp files are required.

Is this something you can do? Looking online it seems that dpkg only can read files from disk

2021-07-24 20:17 UTC, fossdd commented on scripts/ci/dependencies.sh
> +    if which dpkg; then
Mh. Okay, sorry. I also don't get it working. Looks like the devs don't implemented it.. 🙄

2021-07-25 09:56 UTC, fossdd submitted a review, later dismissed

2021-07-25 10:30 UTC, SFR-git requested changes
With the emoji prepended, the commit message is now 68 characters long. Please refrain from using emoji in your commit messages -- you're the only one who uses them here, and they don't work outside of GitHub.

2021-07-26 11:30 UTC, SFR-git commented
```
From: Edgar <Edgar@AnotherFoxGuy.com>
Date: Sat, 24 Jul 2021 20:27:54 +0200
Subject: [PATCH] =?UTF-8?q?=F0=9F=91=B7=20Install=20conan=20using=20pkg=20?=
 =?UTF-8?q?manager=20instead=20of=20pip?=
```

Yeah, emoji don't work.

2021-07-26 11:38 UTC, AnotherFoxGuy commented
> Yeah, emoji don't work.

That seems more like an issue with sourcehut, since I've had plenty of emails with emoji in the subject line

2021-07-26 11:41 UTC, SFR-git commented
> > Yeah, emoji don't work.
> 
> That seems more like an issue with sourcehut, since I've had plenty of emails with emoji in the subject line

This isn't sourcehut: this is the `.patch` file generated *by GitHub* for use in git.

2021-07-26 11:44 UTC, SFR-git commented
I'm not surprised by this at all: GitHub loves to ignore industry standards and lock projects to their ecosystem. 
For example, `code blocks` are only rendered correctly in GitHub.

2021-07-26 13:25 UTC, Be-ing commented
I agree with not using emojis in commit messages.

2021-07-26 13:46 UTC, AnotherFoxGuy commented
Well, CONTRIBUTING.md does not specify what you can and can't put in the commit messages ¯\\_(ツ)_/¯

2021-07-26 17:47 UTC, SFR-git commented
The commit message is just a bit too long. Try this:

```
ci: Install conan using pkg manager instead of pip
```

2021-07-26 18:08 UTC, SFR-git approved these changes

2021-07-26 22:03 UTC, fossdd approved these changes

2021-07-26 22:04 UTC, merged