Add CodeQL static analysis
tenacityteam/tenacity-legacy pull request #384
Opened 2021-07-26 08:42 UTC by emabrey

Add workflow that runs static analysis every 6 hours daily.

Signed-off-by: Emily Mabrey <emabrey@tenacityaudio.org>

This should help make it easier to find and fix any C++ or Python security issues. This uses CodeQL, an open-source static analyzer available here: https://securitylab.github.com/tools/codeql/.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-07-26 08:45 UTC, Semisol commented
`Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps.  Failure invoking /opt/hostedtoolcache/CodeQL/0.0.0-20210702/x64/codeql/cpp/tools/autobuild.sh with arguments .`
Also you might want to run it for every commit, especially for PRs.

2021-07-26 08:59 UTC, Semisol requested changes

2021-07-26 08:59 UTC, Semisol commented on .github/workflows/codeql-analysis.yml
> +        exec bash "scripts/ci/install.sh"
You remove the analysis part.
```suggestion
        exec bash "scripts/ci/install.sh"
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
```

2021-07-26 10:00 UTC, SFR-git commented
I don't like the idea of using GitHub for this. This (a) increases our dependence on GitHub, and (b) wouldn't work on patches sent by mail.

2021-07-26 16:11 UTC, emabrey commented
@SFR-git If we transition from Github it just stops working. It doesn't add any extra dependence on Github that we don't already have. I could just add this to the `cmake_build.yml` so it's more like modifying what is already there. The only reason it's in a separate file is for cron job support.

2021-07-26 16:12 UTC, SFR-git commented
The issue with patches still stands. Could you edit the builds.sr.ht manifest to use this as well?

2021-07-26 18:17 UTC, emabrey commented
> 
> 
> The issue with patches still stands. Could you edit the builds.sr.ht manifest to use this as well?

No. It would violate the license. https://securitylab.github.com/tools/codeql/license/

I view this as an extra tool for GitHub usage only, not as the sole vulnerability scanning allowed. We can always implement an additional GitHub independent vulnerability scanner. The only reason I am using this one is because it seamlessly integrates with the GitHub "Security" tab. If we leave GitHub then we don't have a Security tab, so we would just stop using it by deleting the workflow at that time. This doesn't have to be our only vulnerability scanner; I view this as an addendum not an exclusive.

2021-07-26 20:44 UTC, merged

2021-08-03 11:05 UTC, aeiouaeiouaeiouaeiouaeiouaeiou commented
Sorry to bother but does the CodeQL analysis trigger too often?

2021-08-03 11:06 UTC, Semisol commented
Wdym