Update CONTRIBUTING.md
tenacityteam/tenacity-legacy pull request #385
Opened 2021-07-26 17:27 UTC by panos

Resolves: https://github.com/tenacityteam/tenacity/pull/369#issuecomment-886717796 (Not an issue)

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine (N/A)
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-07-26 17:30 UTC, SFR-git submitted a review, later dismissed

2021-07-26 17:34 UTC, panos commented
Needs more feedback, these rules should be carefully examined and discussed (maybe) so that we actually abide by them and so that we are on the same page. (CC: @AnotherFoxGuy)

2021-07-26 17:47 UTC, panos commented
I do like the concept of [Gitmoji](https://github.com/tenacityteam/tenacity/issues/375#issuecomment-886598126), but I'm not sure if there's a way to support it without it breaking other things.

2021-07-26 17:52 UTC, fossdd commented
> I do like the concept of [Gitmoji](https://github.com/tenacityteam/tenacity/issues/375#issuecomment-886598126), but I'm not sure if there's a way to support it without it breaking other things.

It shouldn't really break anything, maybe show on TTYs only a `:tada:`. But, yes, it's not really part of the concept of git, email (patches), IRC, etc..

I personally would avoid using emojies in commits or anything related.

2021-07-26 17:58 UTC, SFR-git commented
If we want to use emoji, we either break git or take the emoji name length into account. Neither of the solutions are ideal, sadly.

2021-07-26 19:11 UTC, emabrey submitted a review, later dismissed

2021-07-26 19:11 UTC, emabrey commented on CONTRIBUTING.md
> +* Avoid using dots or past tenses in your commit messages.
"Avoid using full stops or past tense in your commit messages."

2021-07-26 19:11 UTC, emabrey commented on CONTRIBUTING.md
> +* Avoid using emojis or GitHub-specific references (e.g. `:tada:`) to emojis
I would say that the emojis are fine in the commit body, but not in the commit subject. Thoughts?

2021-07-26 19:11 UTC, emabrey commented on CONTRIBUTING.md
> +  repository and patches that are meant to be used in Tenacity.
Add line (to clarify GitHub behavior so people don't think they made a mistake when GitHub auto-magically replaces the hyperlink): 

- If you use a hyperlink instead of just the `#nnn` format, GitHub will still show the `#nnn` format on the website, but other websites and/or the command line will show the full hyperlink.

2021-07-26 19:27 UTC, panos commented on CONTRIBUTING.md
> +* Avoid using emojis or GitHub-specific references (e.g. `:tada:`) to emojis
@SFR-git

2021-07-26 19:27 UTC, panos commented on CONTRIBUTING.md
> +* Avoid using dots or past tenses in your commit messages.
Yeah, that's a much better way to put it.

2021-07-26 19:30 UTC, SFR-git commented on CONTRIBUTING.md
> +* Avoid using emojis or GitHub-specific references (e.g. `:tada:`) to emojis
Actual Unicode emoji will cause problems. GitHub ones should be fine, but for simplicity's sake we should disallow them outright.

2021-07-26 22:26 UTC, fossdd requested changes, later dismissed
Maybe also tell the user where to start contributing. And also to fill GH's PR/Issue templates.

2021-07-26 22:26 UTC, fossdd commented on CONTRIBUTING.md
> -### Contributing through GitHub
You `open` pull requests on GH.

2021-07-26 22:26 UTC, fossdd commented on CONTRIBUTING.md
> +  is preferred, because these links will not break outside of GitHub and will
What about using `GH #1234`?

2021-07-27 07:22 UTC, panos commented
Additional note: Add `Reference-to:` segment

2021-07-27 07:22 UTC, panos commented on CONTRIBUTING.md
> +  is preferred, because these links will not break outside of GitHub and will
It's still harder to find than a copied and pasted link?

2021-08-02 14:56 UTC, SFR-git commented
Notice about EditorConfig, possibly?

2021-08-05 17:38 UTC, panos commented
> Notice about EditorConfig, possibly?

Not sure how I could include that. Since this pull request has been open for way too long, it'd be helpful if you could either overwrite my patch, or if we dealt with this at a later date (for the sake of speed and efficiency).

2021-08-06 16:26 UTC, SFR-git submitted a review, later dismissed

2021-08-06 16:35 UTC, Semisol requested changes

2021-08-06 16:35 UTC, Semisol commented on CONTRIBUTING.md
> +if you would like to discuss with us in real time.
Make it a seperate web link? And remove the )
```suggestion
You can also reach out to us in the room #tenacity at Libera.chat [(web)](https://web.libera.chat/gamja/?channels=#tenacity)
if you would like to discuss with us in real time.
```

2021-08-06 16:35 UTC, Semisol commented on CONTRIBUTING.md
> +4. Follow the [commit message guidelines](#commit-messages).
Do we need to have Audacity compatibility this at this point?
```suggestion
1. Follow proper code formatting guidelines e.g. If the file uses spaces, do not
   change them to tabs.
2. Do not change any variable names unless necessary.
43 Follow the [commit message guidelines](#commit-messages).
```

2021-08-06 16:36 UTC, panos commented on CONTRIBUTING.md
> +if you would like to discuss with us in real time.
We could also replace all the links with https://web.libera.chat/#tenacity

2021-08-06 18:01 UTC, panos commented on CONTRIBUTING.md
> +4. Follow the [commit message guidelines](#commit-messages).
Well, no, but it's like whatever at this point.

2021-08-06 19:34 UTC, Semisol submitted a review, later dismissed

2021-08-07 10:18 UTC, SFR-git requested changes

2021-08-07 10:18 UTC, SFR-git commented on CONTRIBUTING.md
> +if you would like to discuss with us in real time.
I don't really like the way this is laid out.
- "Libera" should be replaced with "irc.libera.chat", no codeblocks, so that people who use IRC but not Libera know how to connect to the server.
- This part of the file is outdated, I think, and as much as I'd like to see people using the mailing lists more, the IRC links need to come first.
- `s/e-mail/email/g`

2021-08-07 10:26 UTC, panos commented on CONTRIBUTING.md
> +if you would like to discuss with us in real time.
Libera is the most popular IRC server at the moment, the IRC hyperlink is there, this will basically confuse everyone else apart from the minority that uses IRC but doesn't know of Libera, somehow.

2021-08-07 10:29 UTC, Semisol commented on CONTRIBUTING.md
> +if you would like to discuss with us in real time.
```suggestion
The best place to ask questions about using Tenacity, discuss feature requests, is the `#tenacity` [Libera](https://web.libera.chat/#tenacity)
([irc.libera.chat](ircs://irc.libera.chat:6697/#libera)/
[Matrix](https://matrix.to/#/#tenacity:libera.chat)) channel, which is real time.

You may also use the
[tenacity-discuss mailing list](https://lists.sr.ht/~tenacity/tenacity-discuss)
for bug reports, feature requests and discussion, but it is not real time.
Using a mailing list is as simple as sending an ordinary email. Keep in mind
that all emails posted in our mailing list will be archived publicly.
It may be a good idea to look through our archives, because it is possible that
someone else has asked the same question as you have before.
```

2021-08-07 11:29 UTC, SFR-git commented on CONTRIBUTING.md
> +if you would like to discuss with us in real time.
Hmm, linking that way also looks weird. How about this:

```md
The best place to ask questions about using Tenacity and discuss feature
requests is on our IRC channel, [`#tenacity` on
irc.libera.chat](https://web.libera.chat/#tenacity)
([IRC](https://web.libera.chat/#tenacity)/[Matrix](https://matrix.to/#/#tenacity:libera.chat)), 
where we have real-time discussions.     
```

The best place to ask questions about using Tenacity and discuss feature requests is on our IRC channel, [`#tenacity` on irc.libera.chat](https://web.libera.chat/#tenacity) ([IRC](https://web.libera.chat/#tenacity)/[Matrix](https://matrix.to/#/#tenacity:libera.chat)), where we have real-time discussions.

2021-08-07 11:30 UTC, SFR-git requested changes
Also why are there random files edited

2021-08-07 15:10 UTC, panos commented
> Also why are there random files edited

Dang it, experimental changes that I accidentally tracked. :/

Will fix it after I address the latest review.

2021-08-11 12:32 UTC, SFR-git requested changes
Other than these, LGTM.

2021-08-11 12:32 UTC, SFR-git commented on CONTRIBUTING.md
> +to report bugs and propose feature requests *only*.
I feel like it's worth reiterating this here:

```suggestion
to report bugs and propose feature requests *only*. Support questions will be 
ignored.

2021-08-11 12:32 UTC, SFR-git commented on CONTRIBUTING.md
> +   - Wrong: `Added support for the Commodore 64.`
```suggestion
   - Incorrect: `Added support for the Commodore 64.`

2021-08-11 12:32 UTC, SFR-git commented on CONTRIBUTING.md
> +someone else has asked the same question as you have before.
`mailto` link to the mailing list, possibly? Not entirely sure about this.

```suggestion
Using the mailing list is as simple as sending an ordinary email to 
[`~tenacity/tenacity-discuss@lists.sr.ht`](mailto:~tenacity/tenacity-discuss@lists.sr.ht).
Keep in mind that all emails posted in our mailing list will be archived
publicly. It may be a good idea to look through our archives, because it is 
possible that someone else has asked the same question as you have before.

2021-08-12 16:30 UTC, n0toose commented
Question, we keep messing up the part where we all have to sign off the DCO. Should we add a clause where we say that "by making any further commits as off August 12th,  2021 that are signed off, you also expressly agree that your previous contributions to the project adhere to it" or something like this?

We got it wrong on 62a523f: Not only did we include a reference to GitHub, but we also did not sign-off anything.

2021-08-12 16:50 UTC, SFR-git commented
Feel free to sign me off on this commit.

2021-08-12 17:06 UTC, merged