Fix and improve metadata file for Flatpak
tenacityteam/tenacity-legacy pull request #426
Opened 2021-08-02 01:06 UTC by TheEvilSkeleton

- Remove bolding
- Fix APP ID typo
- Fix project license
- Add releases tags
- Migrate to metainfo from appdata
- Change screenshot

Signed-off-by: TheEvilSkeleton <theevilskeleton@riseup.net>

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-08-02 01:53 UTC, Be-ing submitted a review, later dismissed

2021-08-02 02:03 UTC, TheEvilSkeleton commented
@Be-ing can you approve again?

2021-08-02 02:03 UTC, Be-ing submitted a review, later dismissed

2021-08-02 09:19 UTC, SFR-git reviewed
The wiki links are out of date -- I think it's best we remove them entirely until we have our own. Maybe link to `#tenacity` on irc.libera.chat?

2021-08-02 09:19 UTC, SFR-git commented on help/tenacity.metainfo.xml
> +  <project_license>GPL-2.0 AND CC-BY-3.0</project_license>
CC BY 3.0 is the license for the icon and logo only, does it need to be specified here?

2021-08-02 09:19 UTC, SFR-git commented on help/tenacity.metainfo.xml
> +  <project_license>GPL-2.0 AND CC-BY-3.0</project_license>
Does Flatpak have a format for `GPL-2.0-or-later`?

2021-08-02 09:20 UTC, SFR-git requested changes
The Ubuntu CI fails, as it looks for the old file. Please update it as well

2021-08-02 09:44 UTC, SFR-git commented
Other than that, LGTM; ping me once the issues are fixed so I can approve it.

2021-08-02 11:27 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +  <project_license>GPL-2.0 AND CC-BY-3.0</project_license>
I don't really know. Although the icon and logo are part of the project so I'd suggest keeping CC BY 3.0.

2021-08-02 11:31 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +  <project_license>GPL-2.0 AND CC-BY-3.0</project_license>
Yes.

2021-08-02 11:37 UTC, SFR-git commented on help/tenacity.metainfo.xml
> +  <project_license>GPL-2.0 AND CC-BY-3.0</project_license>
Well, in any case, I misspoke and it's actually `CC BY 4.0`.

2021-08-02 11:40 UTC, SFR-git commented on help/tenacity.metainfo.xml
> +  <project_license>GPL-2.0 AND CC-BY-3.0</project_license>
Hmm, the documentation for Tenacity (which is unchanged from Audacity's) is licensed under 3.0. We might want to discuss updating it to be consistent: I'll bring it up on the IRC dev channel

2021-08-02 11:59 UTC, TheEvilSkeleton commented
> The wiki links are out of date -- I think it's best we remove them entirely until we have our own. Maybe link to `#tenacity` on irc.libera.chat?

What do you mean by "them"?

2021-08-02 12:09 UTC, SFR-git commented
> > The wiki links are out of date -- I think it's best we remove them entirely until we have our own. Maybe link to `#tenacity` on irc.libera.chat?
> 
> What do you mean by "them"?
```xml
  <url type="faq">https://manual.audacityteam.org/man/faq.html</url>
  <url type="help">https://manual.audacityteam.org/</url>
```

2021-08-02 12:16 UTC, SFR-git submitted a review, later dismissed

2021-08-02 12:17 UTC, Semisol requested changes
I don't see any problems except that we should edit the following part with our own links.
```xml
  <screenshots>
    <screenshot type="default">
      <image type="source">https://www.audacityteam.org/wp-content/uploads/2016/01/audacity-212-linux.png</image>
    </screenshot>
    <screenshot>
      <image type="source">https://www.audacityteam.org/wp-content/uploads/2015/11/Audacity-2-2-0-on-Linux.png</image>
    </screenshot>
  </screenshots>
```
Please take this review with a grain of salt, I didn't test.

2021-08-02 12:20 UTC, TheEvilSkeleton commented
I wanted to take some screenshots. Sadly I don't think I will be able to do it because there are some issues:

![image](https://user-images.githubusercontent.com/50847364/127861016-746e0896-8246-4b17-bb85-04f490778aa3.png)

2021-08-02 13:47 UTC, SFR-git commented
If someone wants to take a couple of pictures, please send them to me (preferably through email) so I can upload them to the website.

2021-08-02 13:59 UTC, TheEvilSkeleton commented
> If someone wants to take a couple of pictures, please send them to me (preferably through email) so I can upload them to the website.

@vchernin from what I seen on https://github.com/flathub/flathub/pull/2444#issuecomment-890648320, Tenacity looks good on your system. Are you okay with providing screenshots?

2021-08-02 14:15 UTC, TheEvilSkeleton commented
Hmmm, one of my friends found something:

> The license given in the project_license tag should be the ‘main’ license of the project. For a software project, this is typically the license for the code. It is not recommended to include the license for accompanying documentation (for example) in project_license, as that could confuse users. In particular, the CC-BY-SA-3.0 license which is commonly used for documentation is not an (FSF or OSI) approved license for free software, so including it in project_license results in the project as a whole being considered non-free.

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license

I'm going to remove CC license in the metadata file.

2021-08-02 14:32 UTC, SFR-git requested changes
```
This MR is intended to correct the mistakes and improve integration with Flatpak. The following changes include:

- Remove bolding
- Fix APP ID typo
- Fix project license
- Add releases tags
- Migrate to metainfo from appdata

This MR is intended to partially resolve flathub/flathub#2444 and #25.

Signed-off-by: TheEvilSkeleton <theevilskeleton@riseup.net>
```

This commit message doesn't comply to the contributing guidelines. The lines are longer than 72 characters, and while the information is topical, it isn't necessarily relevant to the commit log.

Try this:

```
- Remove bolding
- Fix APP ID typo
- Fix project license
- Add releases tags
- Migrate to metainfo from appdata

Signed-off-by: TheEvilSkeleton <theevilskeleton@riseup.net>
```

2021-08-02 14:37 UTC, TheEvilSkeleton commented
Is this better?

2021-08-02 14:43 UTC, SFR-git commented
I don't mean the PR description, I mean the commit description.

You can `git commit --amend` with no changes to bring up the description.

2021-08-02 14:44 UTC, TheEvilSkeleton commented
Ah my bad. I missed that

2021-08-02 14:49 UTC, SFR-git approved these changes

2021-08-02 14:50 UTC, SFR-git requested changes
Wait, no, sorry, one last nitpick.

Our EditorConfig manifest declares 4-space indentation. Please use an EditorConfig plugin!

2021-08-02 14:58 UTC, TheEvilSkeleton commented
I'm confused. The editor/IDE I use is GNOME Builder, and it already has EditorConfig integration.

2021-08-02 15:00 UTC, SFR-git commented
Hmm. Maybe because it's an old file, it prioritizes "don't rewrite the whole file" over "follow the EditorConfig"? I think that's the case, because Audacity uses 3-space (eww) and my plugin doesn't catch that on save.

In that case, could you manually indent the file? Just the Flatpak manifest is okay.

2021-08-02 15:07 UTC, TheEvilSkeleton commented
So you want me to indent the Flatpak manifest or the metainfo file?

2021-08-02 15:13 UTC, SFR-git commented
> So you want me to indent the Flatpak manifest or the metainfo file?

Ah, sorry, I meant the metainfo file.

2021-08-02 15:16 UTC, TheEvilSkeleton commented
I just re-indented everything and there's no difference. I tried using GNOME Builder and VSCode.

2021-08-02 15:18 UTC, vchernin commented
> > If someone wants to take a couple of pictures, please send them to me (preferably through email) so I can upload them to the website.
> 
> 
> 
> @vchernin from what I seen on https://github.com/flathub/flathub/pull/2444#issuecomment-890648320, Tenacity looks good on your system. Are you okay with providing screenshots?

Sure I can upload them here and email them. I'll use the default Adwaita theme as I did there.

[Other than what's here](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info), are there any requests from the maintainers of what and how I should screenshot?

2021-08-02 15:27 UTC, SFR-git commented
> Sure I can upload them here and email them. I'll use the default Adwaita theme as I did there.
> 
> [Other than these AppData docs](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info), are there any requests from the maintainers of what and how I should screenshot?

Something to match [what Audacity has](https://www.audacityteam.org/wp-content/uploads/2016/01/audacity-212-linux.png) is fine, I think. Please send them to sol@solfisher.com!

2021-08-02 15:30 UTC, SFR-git commented
Alright, I changed it myself from the GitHub Web UI. Could you rebase it into the one commit?

2021-08-02 15:31 UTC, TheEvilSkeleton commented
Ah, that's what you meant. I'm surprised that GitHub does 4 indents whereas VSCode and Builder do 2.

2021-08-02 15:32 UTC, SFR-git commented
> Ah, that's what you meant. I'm surprised that GitHub does 4 indents whereas VSCode and Builder do 2.

It's a setting you can change, most likely, though VSCode should respect EditorConfig by default.

2021-08-02 15:33 UTC, SFR-git approved these changes, later dismissed

2021-08-02 15:52 UTC, vchernin commented
![Tenacity 1](https://user-images.githubusercontent.com/38842733/127888848-605351fb-5c3c-4495-a61f-294ad3bb3c7d.png)

![Tenacity 2](https://user-images.githubusercontent.com/38842733/127889134-894a69b5-206e-48d9-b1e2-c05f4be8cdb4.png)

These look worth emailing?

2021-08-02 15:59 UTC, SFR-git commented
maybe 50% smaller, so the UI is a bit more clear.

2021-08-02 16:07 UTC, TheEvilSkeleton commented
@vchernin out of curiosity, are you using the flatpak?

2021-08-02 16:09 UTC, vchernin commented
> maybe have the window 50% smaller, so the UI is a bit more clear.

No problem. Those were taken at 200% scaling on a 4k monitor. I'll try that monitor at at 300% or a 2560x1440 at 200% monitor. The density should be the same but I think the 4k one will look nicer. Either way they should roughly be 50% smaller.

Do the waveform shapes seem decent? All I did was give the microphones on my laptop on laptop a massage.

Unfortunately I won't be back at my computer for 3-4 hours or so, but I'll make sure to retake them then.

> @vchernin out of curiosity, are you using the flatpak?

Yeah I'm using the same Flatpak build I used yesterday for the Audacity+Tenacity screenshot.

2021-08-02 16:10 UTC, TheEvilSkeleton commented
I see. Tenacity looks awful on my side. I'll open an issue if it the issue stays after a release.

2021-08-02 20:52 UTC, vchernin commented
![Tenacity 1 300% 3840x2160](https://user-images.githubusercontent.com/38842733/127922323-63ffd5c9-a925-43bf-bcb4-2871637fd8a4.png)

![Tenacity 2 300% 3840x2160](https://user-images.githubusercontent.com/38842733/127922330-8dc6bb95-4db0-4491-8d68-02dd8d7699d4.png)

2021-08-03 03:31 UTC, vchernin commented
Are the above screenshots worth emailing, or is there anything that could be improved?

2021-08-03 05:19 UTC, SFR-git commented
These look great.

2021-08-03 05:44 UTC, vchernin commented
@SFR-git Email sent.

2021-08-03 06:00 UTC, vchernin commented
I formally license these screenshots under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) per request by @SFR-git:

![image](https://user-images.githubusercontent.com/38842733/127965484-bdd1e572-4250-482f-bf8e-2335887e387f.png)

![image](https://user-images.githubusercontent.com/38842733/127965504-8749ae63-cbf6-406e-8632-155388e81308.png)

2021-08-03 06:10 UTC, vchernin commented
@TheEvilSkeleton the first screenshot should be good to go in the metadata file now. Personally not sure of any good [captions](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) though, but those are optional.

It's probably best to use the URL from https://github.com/tenacityteam/assets once the screenshot is merged there (https://github.com/tenacityteam/assets/pull/3).

2021-08-03 08:24 UTC, panos commented
I'm sorry if I'm being very nitpick-ish and for imposing a larger burden here on your end, but wouldn't it be a good idea to add dark mode screenshots as well, while we're at it?

2021-08-03 08:58 UTC, SFR-git commented
Please use this URL:
```
https://raw.githubusercontent.com/tenacityteam/assets/master/screenshots/tenacity-screenshot-light-3840x2160.png
```

2021-08-03 13:14 UTC, TheEvilSkeleton commented
Done!

2021-08-03 13:16 UTC, AnotherFoxGuy commented on help/tenacity.metainfo.xml
> +            <image type="source">https://raw.githubusercontent.com/tenacityteam/assets/master/screenshots/tenacity-screenshot-light-3840x2160.png</image>
raw.githubusercontent.com shouldn't be used as a CDN
```suggestion
            <image type="source">https://cdn.statically.io/gh/tenacityteam/assets/781026d130ebe9b2e48c269d6b355cb576920211/screenshots/tenacity-screenshot-light-3840x2160.png</image>
```

2021-08-03 13:17 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +            <image type="source">https://raw.githubusercontent.com/tenacityteam/assets/master/screenshots/tenacity-screenshot-light-3840x2160.png</image>
Out of curiosity, why?

2021-08-03 13:25 UTC, SFR-git approved these changes, later dismissed

2021-08-03 16:43 UTC, fossdd requested changes, later dismissed

2021-08-03 16:43 UTC, fossdd commented on help/tenacity.metainfo.xml
> +            <image type="source">https://www.audacityteam.org/wp-content/uploads/2016/01/audacity-212-linux.png</image>
Please only show a screenshot by Tenacity

2021-08-03 16:43 UTC, fossdd commented on help/tenacity.metainfo.xml
> +        <category>AudioVideo</category>
This catecory is invalid

2021-08-03 19:06 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +        <category>AudioVideo</category>
Good catch.

2021-08-03 19:11 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +        <category>AudioVideo</category>
Nope, it exists

![image](https://user-images.githubusercontent.com/50847364/128072467-bf0418e5-d00f-4226-892d-0bbb0181c4eb.png)

https://specifications.freedesktop.org/menu-spec/latest/apa.html

2021-08-03 21:21 UTC, Semisol commented
could you preferably not amend all the time? it makes viewing diffs hard sort of, it can be squashed later.

2021-08-03 22:30 UTC, TheEvilSkeleton commented
Sorry 😅

2021-08-04 08:59 UTC, Semisol commented
Yeah no problem.

2021-08-04 09:07 UTC, Semisol requested changes
_I have only reviewed the information + a quick glance of the build changes, not if it will build._

Looks mostly good to me but...

2021-08-04 09:07 UTC, Semisol commented on help/tenacity.metainfo.xml
> +    </categories>
Do we process video anyways?
```suggestion
    <categories>
        <category>Audio</category>
    </categories>
```

2021-08-04 09:07 UTC, Semisol commented on help/tenacity.metainfo.xml
> +    <project_license>GPL-2.0-or-later</project_license>
I think this is currently misleading as it is a mix of GPL-2.0 and GPL-2.0-or-later.

2021-08-04 09:07 UTC, Semisol commented on help/tenacity.metainfo.xml
> +    <metadata_license>CC0-1.0</metadata_license>
If this refers to say the images, they are under CC-BY-4.0

2021-08-04 09:07 UTC, Semisol commented on help/tenacity.metainfo.xml
> +    <update_contact>~tenacity/tenacity-discuss@lists.sr.ht</update_contact>
Looks good to me, but is a mailing list really suitable?

2021-08-04 09:51 UTC, SFR-git commented on help/tenacity.metainfo.xml
> +    <project_license>GPL-2.0-or-later</project_license>
What? -or-later is a superset of licenses, which contains GPL2. Even if most of the code is GPL2, we accept later versions.

2021-08-04 10:54 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +    </categories>
I disagree with the change. Having AudioVideo makes sense.

2021-08-04 10:55 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +    <metadata_license>CC0-1.0</metadata_license>
Metadata license is the license of this file. We don't need to change anything.

2021-08-04 10:56 UTC, TheEvilSkeleton commented on help/tenacity.metainfo.xml
> +    <update_contact>~tenacity/tenacity-discuss@lists.sr.ht</update_contact>
I think it's okay to keep it that way temporarily. A mailing list is better than nothing.

2021-08-04 13:25 UTC, TheEvilSkeleton commented
Decided to make it draft so this doesn't get merged by accident.

I edited the metadata file to include periods in the description and including donation and translation links.

2021-08-04 18:03 UTC, Semisol submitted a review, later dismissed

2021-08-04 18:03 UTC, Semisol commented on help/tenacity.metainfo.xml
> +    <url type="translate">https://hosted.weblate.org/projects/tenacity/tenacity</url>
Problem, this is a duplicate

2021-08-04 18:03 UTC, Semisol commented on help/tenacity.metainfo.xml
> +    <url type="translate">https://hosted.weblate.org/projects/tenacity/tenacity</url>
Duplicate linking
```suggestion
    <url type="donation">https://opencollective.com/tenacity</url>
    <url type="translate">https://hosted.weblate.org/projects/tenacity/tenacity</url>
```

2021-08-04 19:30 UTC, SFR-git submitted a review, later dismissed
LGTM. You should rebase and sign-off, though.

2021-08-04 19:33 UTC, TheEvilSkeleton commented
If it's good, I'm going to rebase.

2021-08-06 01:09 UTC, Semisol approved these changes, later dismissed
Looks good to me, can someone test though so that we don't screw up.

2021-08-06 01:17 UTC, vchernin commented
A quick run of Flathub's appstream-glib validate results in failure:
```
$ flatpak run org.freedesktop.appstream-glib validate ~/devel/tenacity/help/tenacity.metainfo.xml
/var/home/v/devel/tenacity/help/tenacity.metainfo.xml: FAILED:
• tag-invalid           : Expected children for tag
• tag-missing           : <release> required
Validation of files failed
```
See https://github.com/flathub/flathub/wiki/App-Requirements#appstream

2021-08-06 01:20 UTC, vchernin commented
Also appstream-util gives:
```
$ appstream-util validate tenacity.metainfo.xml
tenacity.metainfo.xml: FAILED:
• tag-invalid           : Expected children for tag
• attribute-invalid     : <screenshot> width too large [https://cdn.statically.io/gh/tenacityteam/assets/781026d130ebe9b2e48c269d6b355cb576920211/screenshots/tenacity-screenshot-light-3840x2160.png] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://cdn.statically.io/gh/tenacityteam/assets/781026d130ebe9b2e48c269d6b355cb576920211/screenshots/tenacity-screenshot-light-3840x2160.png] maximum is 900px
• tag-missing           : <release> required
Validation of files failed
```
It looks like the screenshots need to be scaled down. Better than having to be scaled up I guess.

2021-08-06 01:24 UTC, vchernin commented
The [AppStream screenshot docs](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info) don't say anything about max resolution though.

I assume Flathub's checker doesn't complain since Flathub serves the screenshot itself, and I think it scales them down to different resolutions.

2021-08-06 01:43 UTC, TheEvilSkeleton commented
> A quick run of Flathub's appstream-glib validate results in failure:
> 
> ```
> $ flatpak run org.freedesktop.appstream-glib validate ~/devel/tenacity/help/tenacity.metainfo.xml
> /var/home/v/devel/tenacity/help/tenacity.metainfo.xml: FAILED:
> • tag-invalid           : Expected children for tag
> • tag-missing           : <release> required
> Validation of files failed
> ```
> 
> See https://github.com/flathub/flathub/wiki/App-Requirements#appstream

Don't worry, it's purposefully done. The script at https://github.com/TheEvilSkeleton/flatpaks/blob/org.tenacityaudio.Tenacity/org.tenacityaudio.Tenacity.yaml#L270 adds a version, which prevents that issue:

```
$ flatpak run org.freedesktop.appstream-glib validate help/tenacity.metainfo.xml
help/tenacity.metainfo.xml: FAILED:
• tag-invalid           : Expected children for tag
• tag-missing           : <release> required
Validation of files failed
$ sed -e '40i <release version="commit-657a83b9efa53e66d0273de992ad2944fa585dab" date="2021-08-01"/>' -i help/tenacity.metainfo.xml
$ flatpak run org.freedesktop.appstream-glib validate help/tenacity.metainfo.xml
help/tenacity.metainfo.xml: OK
$ 
```

2021-08-06 01:50 UTC, vchernin commented
> Don't worry, it's purposefully done. The script at https://github.com/TheEvilSkeleton/flatpaks/blob/org.tenacityaudio.Tenacity/org.tenacityaudio.Tenacity.yaml#L270 adds a version, which prevents that issue:

Right, so if I understand correctly it's a non issue once Tenacity has releases and the file is updated.

I wonder what to do about the screenshot issue then? Flathub will be fine, but what about other packages that use metainfo?

2021-08-06 02:25 UTC, TheEvilSkeleton commented
> > Don't worry, it's purposefully done. The script at https://github.com/TheEvilSkeleton/flatpaks/blob/org.tenacityaudio.Tenacity/org.tenacityaudio.Tenacity.yaml#L270 adds a version, which prevents that issue:
> 
> Right, so if I understand correctly it's a non issue once Tenacity has releases and the file is updated.
> 
> I wonder what to do about the screenshot issue then? Flathub will be fine, but what about other packages that use metainfo?

Same thing I presume. They'll run a script at the end to add the version.

2021-08-06 02:31 UTC, vchernin commented
>> Right, so if I understand correctly it's a non issue once Tenacity has releases and the file is updated.
>> 
>> I wonder what to do about the screenshot issue then? Flathub will be fine, but what about other packages that use metainfo?

> Same thing I presume. They'll run a script at the end to add the version.

For clarity, I was refering to [the screenshot issue mentioned here](https://github.com/tenacityteam/tenacity/pull/426#issuecomment-893932669). I don't think a script to add the version would help for that.

2021-08-06 02:34 UTC, TheEvilSkeleton commented
I'm confused. Won't they just grab the metainfo from Tenacity itself?

2021-08-06 02:38 UTC, vchernin commented
> I'm confused. Won't they just grab the metainfo from Tenacity itself?

This isn't anything to do with the version tag issue.

The issue was this metainfo info they'd grab from Tenacity includes URLs to high resolution screenshots. appstream-util complains about them and says they're too large. So distro builds will likely be trouble, since their build systems (probably) require the appstream-util check to pass.

Flathub's version of appstream-util doesn't complain about them likely since it resizes screenshots itself.

2021-08-06 03:09 UTC, emabrey requested changes
LGTM once you address the XML comment I have requested.

2021-08-06 03:09 UTC, emabrey commented on help/tenacity.metainfo.xml
> +    <metadata_license>CC0-1.0</metadata_license>
Please add an XML comment that clarifies that this is not the license for anything but this file.

2021-08-06 03:13 UTC, TheEvilSkeleton commented
@emabrey apparently I wasn't able to comment on the review so I'll comment here. `<metadata_license>CC0-1.0</metadata_license>` is only for metadata file, it's obvious IMO.

2021-08-06 03:17 UTC, emabrey commented
> 
> 
> @emabrey apparently I wasn't able to comment on the review so I'll comment here. `<metadata_license>CC0-1.0</metadata_license>` is only for metadata file, it's obvious IMO.

It's obvious to you because you know what it is already. It's not at all obvious to a new reader if "metadata_license" means "for the metadata" or "metadata about the license". I don't want this commit to be construed as re-licensing the project somehow, so adding a comment would aleviate the risk of a misinterpretation.

2021-08-06 03:18 UTC, TheEvilSkeleton commented
Ah, that's completely fair.

2021-08-06 04:30 UTC, emabrey submitted a review, later dismissed

2021-08-06 04:46 UTC, Semisol reviewed
Looks good to me, there is a dark screenshot too if you want to add it: https://github.com/tenacityteam/assets/blob/master/screenshots/tenacity-screenshot-dark-3840x2160.png

2021-08-06 04:50 UTC, Semisol commented
let me do one final inspection & merge it hopefully

2021-08-06 14:24 UTC, TheEvilSkeleton commented
> > I'm confused. Won't they just grab the metainfo from Tenacity itself?
> 
> This isn't anything to do with the version tag issue.
> 
> The issue was this metainfo file they'd grab from Tenacity includes URLs to high resolution screenshots. [appstream-util complains about them and says they're too large](https://github.com/tenacityteam/tenacity/pull/426#issuecomment-893932669). So distro builds will likely be trouble, since their build systems (probably) require the appstream-util check to pass.
> 
> Flathub's version of appstream-util doesn't complain about them likely since it resizes screenshots itself.

I see. In this case, we could try using 1080 screenshots.

2021-08-07 12:07 UTC, SFR-git commented
> I see. In this case, we could try using 1080 screenshots.

Would downscaling the 4K screenshots to 1080p be sufficient?

2021-08-07 15:30 UTC, TheEvilSkeleton commented
> > I see. In this case, we could try using 1080 screenshots.
> 
> Would downscaling the 4K screenshots to 1080p be sufficient?

Maybe? Depends how it looks when downscaled.

2021-08-10 15:01 UTC, TheEvilSkeleton commented
@SFR-git done.

2021-08-10 15:01 UTC, TheEvilSkeleton commented
...I forgot to sign

2021-08-11 08:17 UTC, SFR-git commented
Please update the hashes again

2021-08-11 10:18 UTC, TheEvilSkeleton commented
@SFR-git can you check?

2021-08-12 12:35 UTC, TheEvilSkeleton commented
Anybody can review this?

2021-08-12 12:42 UTC, SFR-git approved these changes

2021-08-12 13:18 UTC, AnotherFoxGuy approved these changes

2021-08-12 13:54 UTC, merged

2021-08-16 13:25 UTC, leio commented
The app XML file shouldn't have been renamed from metainfo to appdata. metainfo is for non-GUI things, like fonts and other aux stuff. GUI apps still have `*.appdata.xml` suffix, just get installed in /usr/share/metainfo.

2021-08-16 13:43 UTC, TheEvilSkeleton commented
Yup, appdata is going to die in a couple of years. metainfo is the successor.