Convert issue templates to forms
tenacityteam/tenacity-legacy pull request #461
Opened 2021-08-10 20:20 UTC by Semisol

Converting issue templates to forms reduces the potential for new people to screw up issues, to then be marked as invalid and closed due to not adhering to the template which may deter new people.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] (N/A) I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-08-10 20:21 UTC, Semisol commented
I confused assignees and reviewers 😅

2021-08-10 20:23 UTC, SFR-git requested changes
"I have searched the archives and haven't found any related bug" should be added somewhere

2021-08-10 20:34 UTC, SFR-git submitted a review, later dismissed

2021-08-10 20:34 UTC, SFR-git commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        Please our [mailing list](https://lists.sr.ht/~tenacity/tenacity-discuss) and IRC (#tenacity on irc.libera.chat) ([web](https://web.libera.chat/#tenacity) | [matrix](https://matrix.to/#/#tena
That's a long line

```suggestion
        Please our [mailing list](https://lists.sr.ht/~tenacity/tenacity-discuss) \
        and IRC (#tenacity on irc.libera.chat) ([web](https://web.libera.chat/#tenacity) \ 
        | [matrix](https://matrix.to/#/#tenacity:libera.chat))

2021-08-10 20:38 UTC, SFR-git commented
Actually it doesn't work, wat
GitHub doesn't seem to respect YAML standards so whatever have the long line

2021-08-10 20:46 UTC, SFR-git commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        Please our [mailing list](https://lists.sr.ht/~tenacity/tenacity-discuss) and IRC (#tenacity on irc.libera.chat) ([web](https://web.libera.chat/#tenacity) | [matrix](https://matrix.to/#/#tena
> Please our

2021-08-10 20:48 UTC, SFR-git requested changes

2021-08-10 20:48 UTC, SFR-git commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        Please ask support questions on the [mailing list](https://lists.sr.ht/~tenacity/tenacity-discuss) or IRC (#tenacity on irc.libera.chat) ([web](https://web.libera.chat/#tenacity) | [matrix](h
Matrix should be capitalized (also possibly Web, but that's less clear-cut)

2021-08-10 21:02 UTC, SFR-git requested changes

2021-08-10 21:02 UTC, SFR-git commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - Manjaro
1. Should be sorted alphabetically
2. It should be fine to include only Debian/Arch/Fedora/Gentoo, and derivatives can be specified in version.
Either that or we just make this a textarea

2021-08-10 21:08 UTC, SFR-git approved these changes

2021-08-11 00:27 UTC, emabrey approved these changes

2021-08-11 00:29 UTC, merged