Use git describe in About Dialog
tenacityteam/tenacity-legacy pull request #470
Opened 2021-08-12 15:03 UTC by humrochagf

Resolves: #460

Use AUDACITY_VERSION_STRING to be consistent with other references using
git describe, like AudacityApp.cpp CLI arg -v

Signed-off-by: Humberto Rocha <humrochagf@gmail.com>

2021-08-12 15:26 UTC, SFR-git requested changes
I think it's best if we use `GIT_DESCRIBE` directly, and eventually maybe replace all references to `AUDACITY_VERSION_STRING` with it. See #433.

2021-08-12 15:26 UTC, SFR-git commented on src/BuildInfo.h
> +                return wxString( "[[https://github.com/tenacityteam/tenacity/commit/" ) + REV_LONG + "|" + wxString( AUDACITY_VERSION_STRING ) + "]] of " +  getRevisionDateTime();
Just the version should be sufficient, I don't see a need for timestamping the commit.

2021-08-12 16:25 UTC, n0toose commented
By the way, thank you for helping us with this!

2021-08-12 17:28 UTC, humrochagf commented on src/BuildInfo.h
> +                return wxString( "[[https://github.com/tenacityteam/tenacity/commit/" ) + REV_LONG + "|" + wxString( AUDACITY_VERSION_STRING ) + "]] of " +  getRevisionDateTime();
Alright, I'll remove the timestamping

2021-08-12 17:36 UTC, humrochagf commented
Oh, no problem I'm glad to be able to help :)

About my choice for the AUDACITY_VERSION_STRING was because since all other versions related info inside the code is using it as a reference to get the description, it would be easier for a refactor later to maintain consistency on the version by using the same macro to change without forgetting that for the about page it behaves differently.

But I'll check to add the GIT_DESCRIBE injected into the context by cmake so I can use it :)

2021-08-12 22:50 UTC, humrochagf commented
Alright, changed to use `GIT_DESCRIBE` directly, I had to inject it into the macro file generated by `Version.cmake` file to have access to it inside the code.
Also, I kept the name `GIT_DESCRIBE` there, but it could name something else if you think it's better.

2021-08-13 06:46 UTC, SFR-git approved these changes
Everything looks good to me :D

2021-08-13 09:46 UTC, panos commented
We'll merge this change in a bit, thanks for your help again! ❇️

2021-08-13 10:45 UTC, panos commented
**Merged in e0f34e7.** For future reference, allowing maintainers to modify your pull request will allow us to rebase your change on top of master before we merge the change - that way, your change will appear as "Merged" on your profile. It's mostly a cosmetic thing either way.

Thanks for your help once again! <3

2021-08-13 10:45 UTC, closed without merging

2021-08-13 14:51 UTC, humrochagf commented
Oh, that's odd, I remember seeing the checkbox to allow editing as checked. Well, maybe I misread the option or the force push after the amend changed something?
But no problem I'll keep an eye on it next time :smile: