BUILDING.md: Add PortSMF Debian build instructions
tenacityteam/tenacity-legacy pull request #528
Opened 2021-08-22 07:13 UTC by juozaspo

Resolves: N/A

Since #512 was merged and broken PortSMF package was removed from the installation list for Debian/Ubuntu distributions there'd be no alternate build instructions to compile forked PortSMF from source as the original package would cause build problems during compilation as shown in #499. This PR adds such build instructions as it is confirmed that the forked version of [PortSMF](https://github.com/tenacityteam/portsmf) works properly when building tenacity.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-08-22 07:25 UTC, panos requested changes
Hi there, thank you for helping us get our documentation up to date! It's ***really*** appreciated. Here's a couple of changes that I proposed that may make the final text sound way better. Keep in mind that I am not a native speaker and that other contributors may have additional suggestions as well.

2021-08-22 07:25 UTC, panos commented on BUILDING.md
> +`-DCMAKE_PREFIX_PATH=/path/to/portsmf` to it's command line.
*its

2021-08-22 07:25 UTC, panos commented on BUILDING.md
> +when using it. If you're installing PortSMF to any other location than the
This is a minor detail, but using `you're` is not very formal in English communications.

2021-08-22 07:25 UTC, panos commented on BUILDING.md
> +in a later stage of the build. It is recommended to use a forked
"you may come across problems when you build Tenacity"

2021-08-22 07:25 UTC, panos commented on BUILDING.md
> +[PortSMF](https://github.com/tenacityteam/portsmf) version built from source until
"that you should build from source"

`built from source` may confuse people as to whether we offer our own builds of the library.

2021-08-22 07:25 UTC, panos commented on BUILDING.md
> +`-DCMAKE_PREFIX_PATH=/path/to/portsmf` to it's command line.
s/to it's command line/to your parameters/

2021-08-22 07:25 UTC, panos commented on BUILDING.md
> +`-DCMAKE_PREFIX_PATH=/path/to/portsmf` to it's command line.
> s/to it's command line/to your parameters/

Someone else may have to correct me here.

2021-08-22 07:45 UTC, juozaspo commented on BUILDING.md
> +`-DCMAKE_PREFIX_PATH=/path/to/portsmf` to it's command line.
Done.

2021-08-22 07:57 UTC, juozaspo commented on BUILDING.md
> +when using it. If you're installing PortSMF to any other location than the
Changed to you are

2021-08-22 07:58 UTC, juozaspo commented on BUILDING.md
> +in a later stage of the build. It is recommended to use a forked
Replaced as suggested

2021-08-22 07:58 UTC, juozaspo commented on BUILDING.md
> +[PortSMF](https://github.com/tenacityteam/portsmf) version built from source until
Done

2021-08-22 08:33 UTC, panos requested changes
So, this is coming together rather nicely! Here are a couple of additional remarks. Apologies in advance for not bringing these things up earlier, it's just that these issues just didn't exactly pop from my point of view.

(P.S. You don't have to squash your commits until we know for sure that the text is ready to go. :D)

2021-08-22 08:33 UTC, panos commented on BUILDING.md
> +from source until the upstream version gets updated and it is confirmed that the
This sentence is VERY large and I can't quite understand the second part (after the "and").

2021-08-22 08:33 UTC, panos commented on BUILDING.md
> +location than the system-wide you should point CMake to the correct location by
"than the system-wide" is unclear. I'm not sure how it could be improved though. Perhaps you could focus on the fact that the location is custom and chosen by the user instead, rather than "not the default location that Debian packages use"

2021-08-22 09:03 UTC, juozaspo commented on BUILDING.md
> +from source until the upstream version gets updated and it is confirmed that the
Rewording complete, should be easier to understand in the second part.

2021-08-22 09:04 UTC, juozaspo commented on BUILDING.md
> +location than the system-wide you should point CMake to the correct location by
Replaced system-wide with the actual locations, also added suggested examples.

2021-08-22 09:15 UTC, panos commented
Oops, forgot to sign it off myself, I'll do so later. I added the actual library directories and slightly modified the wording. Not sure if you're okay with this, I'll undo/modify my change if that's a problem. If you think it's good to go, I'll ask some additional reviewers to take a look.

2021-08-22 09:24 UTC, juozaspo commented
@panos From the looks of it, I'm fine of the final result. Just don't forget to sign your commit (and force push afterwards)

2021-08-22 09:27 UTC, juozaspo reviewed
Good.

2021-08-22 11:05 UTC, panos approved these changes, later dismissed
Needs to be squashed and signed by me. I will merge this, but I'm seeking an additional review here.

2021-08-22 17:15 UTC, SFR-git commented
Can someone with Debian/*buntu/derivatives confirm that this works?

2021-08-22 18:26 UTC, Be-ing commented on BUILDING.md
> +is not included in the above list: It is outdated and using it may cause problems
```suggestion
is not included in the above list: It is outdated and using it will cause Tenacity to fail to build.
```

2021-08-22 18:26 UTC, Be-ing commented on BUILDING.md
> +when building Tenacity. It is recommended to use a forked
```suggestion
when building Tenacity. If you want to use MIDI, it is recommended to use a forked
```
PortSMF is an optional dependency.

2021-08-22 18:27 UTC, Be-ing commented on BUILDING.md
> +point CMake to it by adding `-DCMAKE_PREFIX_PATH=/path/to/portsmf` to your parameters.
```suggestion
point CMake to it by adding `-DCMAKE_PREFIX_PATH=/path/to/portsmf` to the CMake configuration step.
```

2021-08-22 18:38 UTC, panos commented
@juozaspo, @Be-ing probably did the review thing better than me in the sense that you can commit his suggestions yourself if it looks fine by you. Either way, we're getting closer! Thanks for helping us with this (again)! :)

2021-08-22 19:23 UTC, Semisol commented
> Needs to be squashed and signed by me. I will merge this, but I'm seeking an additional review here.
Don't do that, they need to sign off it.

2021-08-23 13:08 UTC, Be-ing commented on BUILDING.md
> +from source until the upstream version gets updated. If you are installing PortSMF
```suggestion
from source until the packaged version gets updated. If you are installing PortSMF
```

2021-08-23 13:09 UTC, Be-ing commented on BUILDING.md
> +is not included in the above list: It is outdated and using it will cause Tenacity
```suggestion
is not included in the above list because it is outdated and using it will cause Tenacity
```

2021-08-23 14:54 UTC, Be-ing approved these changes, later dismissed
Let's squash this when merging.

2021-08-23 15:00 UTC, juozaspo commented
@Be-ing, @panos needs to sign his commit before any squashing can be done otherwise in general this looks ok to me, I've signed all of my commits so far.

2021-08-24 19:41 UTC, panos commented
MY BAD

2021-08-28 05:46 UTC, caughtquick approved these changes, later dismissed
We should be good to merge this now

2021-08-30 17:56 UTC, merged