CMake/CI Build Improvements
tenacityteam/tenacity-legacy pull request #545
Opened 2021-08-27 21:25 UTC by emabrey

* Automatically enable inter-procedural optimization (IPO) on supporting compilers using CMake configuration changes
* Fix 32-bit builds to not redefine compiler/cstdlib internal functions during IPO enabled builds ( as it is not possible because of IPO in-lining)
* Add GitHub CI configuration to use Visual Studio Generator
* Fix incorrect comments/debug messages which incorrectly described the meaning of the `IS_64_BIT` variable
* Refactor GitHub CI `cmake_build.yml` workflow configuration to increase readability and maintainability
* Update vcpkg binary cache to use Github Packages
* Change CI builds to create caches by id instead of by name
* Refactor `CMakeLists.txt` to use consistent formatting and be laid out more logically

I have no idea why, but this seems to have partially resolved the MacOS build problems we've been having with CPack. I have built this several times now and it builds two different jobs on MacOS and initially none of them failed. 

Reference-to: https://github.com/tenacityteam/tenacity/pull/198
Resolves https://github.com/tenacityteam/tenacity/issues/526

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-08-28 08:57 UTC, AnotherFoxGuy commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
This isn't necessary, if chocolatey is not available it is caused by the chocolatey server and not by GH actions

2021-08-28 11:44 UTC, Be-ing requested changes
This PR has a bunch of unrelated changes together. Please split it up so they can be discussed separately.

2021-08-28 11:44 UTC, Be-ing commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
Also, in the rare event this occurs (which I have not seen), we could just rerun the job manually.

2021-08-28 13:24 UTC, emabrey commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
No, you are both incorrect.

1. It is not a rare event. Fairly often the NICs on the runner become temporarily unavailable and if that happens while we are attempting this it will fail. 
2. Just like the MacOS problem, a single failure here means rerunning every single OS build job.

2021-08-28 13:26 UTC, emabrey commented
> 
> 
> This PR has a bunch of unrelated changes together. Please split it up so they can be discussed separately.

No. They are all related fixes that improve the CI build. I'm not doing extra work to split up a bunch of related changes.

2021-08-28 15:13 UTC, Be-ing commented
I don't get how the changes to the GitHub Actions workflow file, many of which I think are steps backwards, have to do with the changes to the other files. I don't want to hold up the improvements like IPO over that.

2021-08-28 19:58 UTC, emabrey commented
> 
> 
> I don't get how the changes to the GitHub Actions workflow file, many of which I think are steps backwards, have to do with the changes to the other files. I don't want to hold up the improvements like IPO over that.

If you think that there are problems with the way I improved the cmake_build workflow then you need to be specific. 

Here are the things I fixed about that workflow:

* It incorrectly used the job names (which include spaces and are not guaranteed to be unique) instead of the job ID (which are unique and non-spaced)

* It included massive amounts of redundancy and "copy paste" between jobs, all of which destroys readability and maintainability

* It failed to use the CI process to test any CMake generator other than the one you personally prefer

* It failed to centralize configuration variables and left them strewn out across all the steps

* The packaging step somehow massively increased the prevalence of the timing issues with MacOS because of the use of `&&` instead of placing the CPack directory cleanup/removal command on a separate line.

2021-08-28 20:04 UTC, AnotherFoxGuy commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
> Fairly often the NICs on the runner become temporarily unavailable

But if that is the case this "fix" should also be applied to vcpkg

2021-08-28 20:23 UTC, Be-ing commented
I was trying to avoid getting into an in depth discussion about all of those points. Most of those are distinct and can be split to separate PRs.

2021-08-28 20:38 UTC, emabrey commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
I only ever noticed it occurring during the chocolatey step. It occurred several times but I deleted all the build steps that failed (it was like 5 or 6) except for this one:

https://github.com/tenacityteam/tenacity/runs/3418371996?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3370875/131230145-7d474344-24c5-4500-9898-2bb5df02e166.png)

This workaround would be triggered in the case that chocolatey's web infrastructure is down, and you are correct in thinking it wouldn't be able to solve that. What you are unaware of is that chocolatey has issues handling heavy network load ([according to the Chocolatey devs](https://github.com/chocolatey/choco/issues/846#issuecomment-229733571)) and that means that retrying it multiple times gives us time to outlast the transient unavailability of the NIC due to heavy load like you commonly find in a cloud CI environment.

2021-08-28 20:53 UTC, emabrey commented
> 
> 
> I was trying to avoid getting into an in depth discussion about all of those points. Most of those are distinct and can be split to separate PRs.

This PR is a general improvement to the CI builds. All the changes implemented are scoped to that idea (improve builds on CI). The IPO changes aren't external to improving CI builds, so they shouldn't be split out. The rule about separate PRs doesn't make sense to apply in this context because what you are actually saying is you want me to split it apart because you don't like some of the improvements and that makes it easier for you to discard some of them by ignoring them (more or less the coding equivalent of a heckler's veto). That's not what that rule is designed to do. If you can point out how any of the changes don't improve CI builds then I would be happy to consider splitting them out, but AFAIK all the changes are in scope to that change premise. Alternatively, if you can point out why you believe that some of the changes that are in scope to this PR are inappropriate or in need of additional changes (i.e., a review), that would also be helpful. The PR splitting procedure is not appropriately used to break a change-set into a bunch of small pieces and then ignore the ones you don't like without providing any actual criticism or review.

2021-08-28 21:13 UTC, emabrey commented
> 
> 
> > I was trying to avoid getting into an in depth discussion about all of those points. Most of those are distinct and can be split to separate PRs.
> 
> This PR is a general improvement to the CI builds. All the changes implemented are scoped to that idea (improve builds on CI). The IPO changes aren't external to improving CI builds, so they shouldn't be split out. The rule about separate PRs doesn't make sense to apply in this context because what you are actually saying is you want me to split it apart because you don't like some of the improvements and that makes it easier for you to discard some of them by ignoring them (more or less the coding equivalent of a heckler's veto**). That's not what that rule is designed to do. If you can point out how any of the changes don't improve CI builds then I would be happy to consider splitting them out, but currently AFAIK all the changes are in scope to that change premise. Alternatively, if you can point out why you believe that some of the changes that are in scope to this PR are inappropriate or in need of additional changes (i.e., a review), that would also be helpful. The PR splitting procedure is not appropriately used to break a change-set into a bunch of small pieces and then ignore the ones you don't like without providing any actual criticism or review.
> 
> Edit: ** Without the connotative implications about being impolite. I'm not implying that.

The only change that maybe should be split out would be the fix to `cmake-modules/FindVampHostSDK.cmake`, but I was planning on adding CI configurations to test debug builds in addition to release builds, so it's more like it's related but not as strongly.

2021-08-28 21:16 UTC, AnotherFoxGuy commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
If this is a choco issue wouldn't it be better to move from choco to https://scoop.sh/ ?
It is also way faster since choco takes around 1-2 minutes to install the packages

2021-08-28 22:34 UTC, Be-ing commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
I don't think scoop is installed in the GitHub Actions runner VMs.

2021-08-28 23:29 UTC, emabrey commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
[Here is the list](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) which contains all the tools within virtual environment for Windows Server 2019.

We could just go `cargo install sccache` but that would take even longer, since it builds from scratch and it has to pull down about ~400 dependencies on the current version.

2021-08-29 00:49 UTC, Be-ing commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
Building sccache on GitHub Actions takes about 10 minutes. Mixxx has to do this because sccache hasn't made a release with a bug fix Mixxx needs.

2021-08-29 01:10 UTC, emabrey commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
A bit off topic, but out of curiosity which bug fix? I have a PR waiting to fix a bug on their repo and it's just sitting there. I spoke with the mozilla people and they said the maintainer is just really busy.

2021-08-29 01:10 UTC, emabrey commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
A bit off topic, but out of curiosity which bug fix? I have a PR waiting to fix a bug on their repo and it's just sitting there. I spoke with the mozilla people and they said the maintainer is just really busy.

2021-08-29 05:31 UTC, Be-ing commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
https://github.com/mozilla/sccache/pull/962

`/fp:fast` might be appropriate for Tenacity too but I'm not sure.

2021-08-29 06:27 UTC, SFR-git requested changes
I don't think anything related to DarkAudacity should be touched. If anything, we should remove it outright.

2021-08-29 09:04 UTC, SFR-git commented
> I don't think anything related to DarkAudacity should be touched. If anything, we should remove it outright, but that's outside the scope of this PR.

Wait, no, I might've misunderstood the change. Why is a file not related to DarkAudacity whatsoever named `darkaudacity.ico`?

2021-08-29 17:48 UTC, Be-ing commented on scripts/ci/dependencies.sh
> +        # This retry workaround is because on Github actions this just randomly fails when
Obsoleted by #557

2021-08-29 18:21 UTC, Be-ing requested changes
Please stop making this PR even bigger with even more unrelated commits.

2021-08-29 19:22 UTC, Be-ing commented
Generally the only reason a PR should change multiple distinct things together is because merging them independently would leave the master branch in a (partially) broken state, for example #228 or #543. That is not the case here. As a start, please split off separate PRs for:
  * IPO
  * CPU architecture detection
  * GitHub Packages
  * Innosetup installer fixes

There are also commits in this branch that seem to cancel out earlier commits which makes it difficult to review.

I am not sure that the Vamp host SDK detection fix should be addressed in this repository. It looks like there is a bug in the vcpkg port.

2021-08-30 07:32 UTC, emabrey commented
I believe I may have been able to solve the issue with MacOS builds (but I've thought that about 10 times already before so I'm not saying it's definitely fixed 😆 . I will look at the failing Arch build in the morning.

2021-08-30 07:39 UTC, emabrey commented
> 
> 
> Generally the only reason a PR should change multiple distinct things together is because merging them independently would leave the master branch in a (partially) broken state, for example #228 or #543. That is not the case here. As a start, please split off separate PRs for:
> 
>     * IPO
> 
>     * CPU architecture detection
> 
>     * GitHub Packages
> 
>     * Innosetup installer fixes
> 
> 
> There are also commits in this branch that seem to cancel out earlier commits which makes it difficult to review.
> 
> I am not sure that the Vamp host SDK detection fix should be addressed in this repository. It looks like there is a bug in the vcpkg port.

If we don't fix the Vamp Host issue then we have to rollback vcpkg support to not be the default anymore on Windows. It's flatly not acceptable to have the default build type fail on the most popular desktop OS. Secondly, I am not splitting this PR apart for the same reason you didn't split apart #228 - it's impractical.

2021-08-30 09:55 UTC, solfisher requested changes
Now that the commits are a bit more managable:

- 969da961c083ef8af0f101f8ce194866b74124ae: The changes were merged *from* upstream, it'd be silly to have that merge commit pushed to upstream as well. This could be fixed by instead rebasing the branch that you're working on (this won't break Weblate).
- 424b8babacf38948cabb981e76c7802438d7772c: Seems to have been superseded by #557
- 2e2675a5b03e88a6fb25fc8b00fec1bc7075ab7f: Has this been tested on compilers which don't support IPO?

Once these issues are addressed, I'm fine with cherry-picking them to master while you keep working on the other commits.

2021-08-30 13:44 UTC, emabrey commented
> Now that the commits are a bit more managable:
> 
> - 969da961c083ef8af0f101f8ce194866b74124ae: The changes were merged *from* upstream, it'd be silly to have that merge commit pushed to upstream as well. This could be fixed by instead rebasing the branch that you're working on (this won't break Weblate).
> - 424b8babacf38948cabb981e76c7802438d7772c: Seems to have been superseded by #557
> - 2e2675a5b03e88a6fb25fc8b00fec1bc7075ab7f: Has this been tested on compilers which don't support IPO?
> 
> Once these issues are addressed, I'm fine with cherry-picking them to master while you keep working on the other commits.

Yes, the IPO code works either way.

The innosetup commit was coauthored because before it would've been a hassle to rebase the branch ref,  so I just duplicated the changes to make the merge conflict go away. Now I can rebase it easier with the commits cleaned up, so I'll rewrite the branch.

The scoop thing hasn't been merged so there's no sense in anticipating the changes. If there's a merge conflict here by the time we are ready to merge then ill handle it then.

You don't have to cherry pick the commits, I will do that. The hard bit of the PR split is rewriting all the changes from a interweaved history into a serial history, now that that is done the PR split isn't a big deal.

2021-08-30 13:48 UTC, solfisher commented
> The scoop thing hasn't been merged so there's no sense in anticipating the changes. If there's a merge conflict here by the time we are ready to merge then ill handle it then.

We should merge it, then. It's been approved more than 12h ago. I'll do that now.

2021-09-02 11:46 UTC, solfisher requested changes

2021-09-02 11:46 UTC, solfisher commented on .builds/alpine.yml
> +  - tiff-devz
?

2021-09-02 11:46 UTC, solfisher commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
This list is sorted alphabetically, sort of. Could you add this in the correct place?

2021-09-02 11:49 UTC, emabrey commented on .builds/alpine.yml
> +  - tiff-devz
It was a typo, I already fixed it.

2021-09-02 11:50 UTC, emabrey commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
I'll just alphabetize it for real after I'm sure it works.

2021-09-02 11:52 UTC, solfisher commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
`vamp-sdk` exists only in Alpine's edge repository, not in any stable branch.

2021-09-02 11:54 UTC, emabrey commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
https://git.alpinelinux.org/aports/tree/testing/vamp-sdk/APKBUILD It literally just builds it, why can't we include it anyways?

2021-09-02 11:55 UTC, solfisher commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
We're using Alpine 3.14, the latest stable version, which is recommended for use on desktops. edge is a rolling release branch.

2021-09-02 11:58 UTC, emabrey commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
Well if we don't have it then this CI needs to build with VAMP disabled. It will continue to fail otherwise.

2021-09-02 11:58 UTC, solfisher commented on .builds/alpine.yml
> +  - vamp-plugin-sdk
Fine by me.

2021-09-02 15:45 UTC, emabrey commented
Assuming this last force-push builds successfully I will split this up into separate branches where possible and submit separate PRs.

2021-09-03 21:25 UTC, emabrey commented
Split PRs:

https://github.com/tenacityteam/tenacity/pull/577
https://github.com/tenacityteam/tenacity/pull/578

2021-09-04 05:25 UTC, emabrey commented
I believe this will be fixed once https://github.com/tenacityteam/tenacity/pull/578 is merged and then it can be reviewed without any errors.

2021-09-04 12:41 UTC, emabrey commented
> 
> 
> I believe this will be fixed once #578 is merged and then it can be reviewed without any errors.

I was right 😎

2021-09-04 12:49 UTC, solfisher commented on CMakeLists.txt
> +#This must appear after the project declaration so it can detect ENABLED_LANGUAGES
Nitpick: space after `#`

2021-09-04 12:49 UTC, solfisher commented on CMakeLists.txt
> -  set( AUDACITY_NAME "tenacity" )
I assume this was auto-formatted, but it looks really weird

2021-09-04 12:49 UTC, solfisher commented on src/CMakeLists.txt
> +            -D SRC="${_EXEDIR}/${AUDACITY_NAME}.exe"
All of these changes could be refactored into a separate `Generalize project name` commit

2021-09-04 13:09 UTC, emabrey commented on src/CMakeLists.txt
> +            -D SRC="${_EXEDIR}/${AUDACITY_NAME}.exe"
They could but I'm getting tired of splitting this thing lol

2021-09-04 13:10 UTC, solfisher commented on src/CMakeLists.txt
> +            -D SRC="${_EXEDIR}/${AUDACITY_NAME}.exe"
Fair enough.

2021-09-04 13:10 UTC, emabrey commented on CMakeLists.txt
> -  set( AUDACITY_NAME "tenacity" )
It matches the rest of the formatting. And it was partially automatically formatted but I ended up having to go back and do it all manually anyways.

2021-09-04 13:14 UTC, emabrey commented on CMakeLists.txt
> +#This must appear after the project declaration so it can detect ENABLED_LANGUAGES
Wait a second. You are reviewing an outdated version somehow. 
![image](https://user-images.githubusercontent.com/3370875/132095644-242c94af-5917-4e4b-bd37-306856be0847.png)

2021-09-04 13:15 UTC, solfisher commented on CMakeLists.txt
> +#This must appear after the project declaration so it can detect ENABLED_LANGUAGES
I also noticed that, which is why I resolved this myself. No idea how that happened.

2021-09-04 13:15 UTC, emabrey commented on src/CMakeLists.txt
> +            -D SRC="${_EXEDIR}/${AUDACITY_NAME}.exe"
Also they were already attempting to generalize the project name, they just did it inconsistently. I consider it to be part of the refactor because I'm not adding new feature with that only making sure it's consistently used.

2021-09-04 13:16 UTC, solfisher commented on CMakeLists.txt
> +#This must appear after the project declaration so it can detect ENABLED_LANGUAGES
Wait, no, I see why: this was fixed in a later commit in the same PR. I was reviewing the specific commit.

2021-09-07 11:43 UTC, merged

2021-09-07 11:49 UTC, Be-ing commented
Whoa wtf? This branch was not approved!