Change flatpak worflow cache key
tenacityteam/tenacity-legacy pull request #570
Opened 2021-08-31 19:26 UTC by emabrey

The cache key was the same across the matrix, leading to cache collisions. Because GitHub Actions prevents cache collisions by detecting duplicate keys, only one of the build architectures was being cached per run (whichever one accessed the cache storage by key for writes first). This simply adds additional information to the cache key so that the two runs won't collide.

Signed-off-by: Emily Mabrey <emabrey@tenacityaudio.org>

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-08-31 19:54 UTC, nbsp commented
> worflow

typo in commit message

2021-08-31 20:10 UTC, emabrey commented
> 
> 
> > worflow
> 
> typo in commit message

Fixed.

2021-08-31 20:33 UTC, Be-ing submitted a review, later dismissed
good catch

2021-08-31 21:24 UTC, solfisher requested changes

2021-08-31 21:24 UTC, solfisher commented on .github/workflows/flatpak.yml
> +        cache-key: flatpak-builder-${{matrix.arch}}-${{ github.sha }}
Nitpick: spacing of `{{matrix.arch}}`

2021-09-01 06:14 UTC, tytan652 commented on .github/workflows/flatpak.yml
> +        cache-key: flatpak-builder-${{matrix.arch}}-${{ github.sha }}
The arch is useless if you switch to the v4 of the action which handle multi-arch now

2021-09-01 06:58 UTC, tytan652 commented
This if you use the recommended cache key, the hash of the flatpak manifest.

This "error", which is rather a warning, will always happen if you don't change the manifest. Because the cache with the needed already exist ant doesn't need to be rebuilt. And this is normal this is why it don't fail the whole job.

The cache only cache the built deps module of the manifest, if you don't change it there is no need to update the cache this is why they recommend the manifest hash as cache key.

2021-09-01 12:32 UTC, emabrey commented
> 
> 
> This will also happen if you use the recommended cache key, the hash of the flatpak manifest.
> 
> This "error", which is rather a warning, will always happen if you don't change the manifest. Because the cache with the needed already exist ant doesn't need to be rebuilt. And this is normal this is why it don't fail the whole job.
> 
> The cache only cache the built deps module of the manifest, if you don't change it there is no need to update the cache this is why this error happen and they recommend the manifest hash as cache key.

I realize it's a warning and not an error, that's why I never referred to it as an error. I don't know why you are disagreeing me saying something which I never said. 

Additionally, GitHub doesn't expect you to try to write two cache entries to the same key, so the second one fails, but as you pointed out, it does so gracefully. That's not the same thing as doing it correctly. Github actions expects cache key writes to be unique, and if as you say the cache is identical between the build runs, then having two copies of it is harmless. If however there ever ends up being a difference between the cache content by arch, meaning that the two CI runs with differing inputs give differing outputs (something that seems entirely reasonable to assume is possible or even expected), then this behavior is actually a problem, since it would not be deterministic.

2021-09-01 12:40 UTC, tytan652 commented
> I realize it's a warning and not an error, that's why I never referred to it as an error. I don't know why you are disagreeing me saying something which I never said.

Sorry for the misunderstanding, I never considered that you take it as an error.

> If however there ever ends up being a difference between the cache content by arch, meaning that the two CI runs with differing inputs give differing outputs (something that seems entirely reasonable to assume is possible or even expected), then this behavior is actually a problem, since it would not be deterministic.

The v3 of the action don't support multi-arch the v4 does.
The v4 take the key and add the arch to it automatically and it seems you don't setup  QEMU for aarch64 build.

2021-09-01 12:48 UTC, emabrey commented
> 
> 
> This will also happen if you use the recommended cache key, the hash of the flatpak manifest.
> 
> This "error", which is rather a warning, will always happen if you don't change the manifest. Because the cache with the needed already exist ant doesn't need to be rebuilt. And this is normal this is why it don't fail the whole job.
> 
> The cache only cache the built deps module of the manifest, if you don't change it there is no need to update the cache this is why this error happen and they recommend the manifest hash as cache key.

The docs for the action state the following:
<html><body>
<!--StartFragment-->

cache-key | Specifies the cache key. CPU arch is automatically added, so there is no need to add it to the cache key. | Optional | flatpak-builder-${sha256(manifestPath)}
-- | -- | -- | --


<!--EndFragment-->
</body>
</html>

It says it appends the arch to the hash key (presumably meaning that it , but for some reason it actually is not, so I'm doing it manually.

> 
> 
> > I realize it's a warning and not an error, that's why I never referred to it as an error. I don't know why you are disagreeing me saying something which I never said.
> 
> Sorry for the misunderstanding, I never considered that you took it as an error.
> 
> > If however there ever ends up being a difference between the cache content by arch, meaning that the two CI runs with differing inputs give differing outputs (something that seems entirely reasonable to assume is possible or even expected), then this behavior is actually a problem, since it would not be deterministic.
> 
> The v3 of the action don't support multi-arch the v4 does.
> The v4 take the key and add the arch to it automatically and it seems it don't setup QEMU for aarch64 build.

Yes, looking at it I think we need to add QEMU to actually get it to build on ARM. I wasn't the one who wrote the original flatpak workflow so it took me a second to read through the documentation.

2021-09-01 12:51 UTC, tytan652 commented
> It says it appends the arch to the hash key (presumably meaning that it , but for some reason it actually is not, so I'm doing it manually.

In the v4, it does not the v3. The CI use the v3.

2021-09-02 01:50 UTC, emabrey commented
> 
> 
> > It says it appends the arch to the hash key (presumably meaning that it , but for some reason it actually is not, so I'm doing it manually.
> 
> In the v4, it does not in the v3. The CI use the v3.
> 
> Edit: The v4 was released recently.

Yeah I realized that when I wrote that earlier. Perhaps I should've been more clear. I was quoting the current documentation as a way to say that switching would fix it. I didn't write it very well because I wrote the first part before realizing it and wrote the second part after realizing it and didn't make it more cohesively tonal.

Either way, I have updated the flatpak workflow to use v4 and to correctly emulate the 64 bit ARM platform for flatpak builds targeting `aarch64` or any other non-`x86_64` build scenario.

2021-09-02 08:10 UTC, solfisher approved these changes
Other than this, LGTM

2021-09-02 08:10 UTC, solfisher commented on .github/workflows/flatpak.yml
> +        dnf -y install docker ninja-build
This can be shortened to one line

2021-09-02 08:17 UTC, tytan652 commented on .github/workflows/flatpak.yml
> +        dnf -y install docker ninja-build
The pipe can also be removed since it's not multiline.

2021-09-02 08:20 UTC, tytan652 commented on .github/workflows/flatpak.yml
> +        dnf -y install docker ninja-build
Yes, I don't know why they put the pipe in the action docs.

2021-09-04 02:12 UTC, Be-ing approved these changes

2021-09-04 02:12 UTC, Be-ing commented on .github/workflows/flatpak.yml
> +        platforms: arm64
This only needs to run for `matrix.arch == aarch64` but it only takes 2 seconds anyway so :shrug:

2021-09-04 05:42 UTC, merged

2021-09-04 06:18 UTC, emabrey commented
Thank you to @tytan652 for their help on this issue!