Emabrey/find vamphostsdk fix
tenacityteam/tenacity-legacy pull request #577
Opened 2021-09-03 18:23 UTC by emabrey

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [ ] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code\*
- [ ] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-09-04 01:48 UTC, Be-ing commented on cmake-modules/FindVampHostSDK.cmake
>  )
I think this solution would only be appropriate if the upstream build system adds the `d` suffix to the file name, which I doubt it does. That is [added by vcpkg](https://github.com/microsoft/vcpkg/blob/719ceca88dc9fc7f5eb4c5cc288cd3786c37a3c2/ports/vamp-sdk/CMakeLists.txt#L4), which I suspect is a bug in the package and [against vcpkg policy](https://vcpkg.io/en/docs/maintainers/maintainer-guide.html#do-not-rename-binaries-outside-the-names-given-by-upstream). Can you try building vamp-sdk manually on Windows and report what the file names of the built libraries are?

2021-09-04 03:55 UTC, emabrey commented on cmake-modules/FindVampHostSDK.cmake
>  )
That's why it looks for both. It tries to find the debug libraries (with a d suffix), but if they don't exist, it just links the whatever libraries are named as "vamp-hostsdk" and "libvamp-hostsdk". If those are the release libraries it just links the release libraries during the Debug configuration, if they aren't then it links the Release configuration version.

2021-09-04 03:56 UTC, emabrey commented on cmake-modules/FindVampHostSDK.cmake
>  )
This is in fact necessary to get vamphost-sdk to build during Debug builds. If you don't believe me swap to master, build Debug with vcpkg enabled and try to start the application. It won't start, because it can't find the DLL.

2021-09-04 06:08 UTC, emabrey commented on cmake-modules/FindVampHostSDK.cmake
>  )
I had to make some modifications to the source files I downloaded to get it to build (it had hardcoded library paths etc. that weren't valid on this version of Windows), but once I got it to build, this is the output of a dynamic Debug build:

![image](https://user-images.githubusercontent.com/3370875/132084703-461e8831-fdcc-4dd2-acfc-b5c5d51582e2.png)

2021-09-04 06:10 UTC, emabrey commented on cmake-modules/FindVampHostSDK.cmake
>  )
I do wan't to point out that if upstream vcpkg fixes the issue and stops adding d suffix to Debug builds, this will seamlessly continue to work. It's basically a workaround for their broken packaging.

2021-09-04 11:49 UTC, solfisher commented on cmake-modules/FindVampHostSDK.cmake
>  )
I'd at least put an `XXX` comment in front, so we don't forget about it and add more zombie code than already exists.

2021-09-04 12:34 UTC, Be-ing commented on cmake-modules/FindVampHostSDK.cmake
>  )
Thanks for checking that. So vcpkg adding the `d` suffix is a bug in the package. That's easy to fix. However, there is another issue with the package because it uses the same library file name `vamp-sdk` on all OSes, but the upstream library uses `VampHostSDK` on Windows... this is why libraries should not try to maintain multiple build systems. @cannam do you have any comment on this? Are the different file names for the Vamp libraries with the Visual Studio project file versus autotools intentional? Would you consider changing this upstream so the file names are the same on each OS?

2021-09-04 12:34 UTC, solfisher approved these changes, later dismissed
LGTM other than the `libvamp-hostsdkd` issue. One nitpick: *Vamp* isn't in all caps.

2021-09-04 12:34 UTC, solfisher commented on .builds/alpine.yml
> +  - configure: cmake -G Ninja -S tenacity -B build -D USE_VAMP=OFF
I wonder why the Alpine build didn't fail, even though it never used Vamp.

2021-09-04 12:35 UTC, emabrey commented
> 
> 
> LGTM other than the `libvamp-hostsdkd` issue. One nitpick about the commit message: _Vamp_ isn't in all caps.

It's not capitalized in the original source builds either. They call it "VampHostSDK" so I just copied that.

2021-09-04 12:36 UTC, Be-ing commented on .builds/alpine.yml
> +  - configure: cmake -G Ninja -S tenacity -B build -D USE_VAMP=OFF
Vamp is an optional dependency. If the library is not found, CMake does not try to build the feature.

2021-09-04 12:36 UTC, solfisher commented
I was referring to this commit:
> Disable VAMP plugins on Alpine CI

It should be Vamp

2021-09-04 12:37 UTC, emabrey commented on .builds/alpine.yml
> +  - configure: cmake -G Ninja -S tenacity -B build -D USE_VAMP=OFF
Because even when we aren't using vamp, if we try to find the library CMake fails. You have to pass USE_VAMP=OFF to disable the find lookup.

2021-09-04 12:38 UTC, Be-ing commented on cmake-modules/FindVampHostSDK.cmake
>  )
> if upstream vcpkg fixes the issue

We can fix it easily in our vcpkg repo before making a pull request for upstream vcpkg.

2021-09-04 12:39 UTC, emabrey commented on cmake-modules/FindVampHostSDK.cmake
>  )
This is the Vamp source I downloaded from https://www.vamp-plugins.org/develop.html not the Github CMake version, so maybe that is why it is different?

2021-09-04 12:49 UTC, Be-ing requested changes
This introduces complexity into Tenacity's build system to hack around a bug in the package. We can fix the package instead.

2021-09-04 12:49 UTC, Be-ing commented on cmake-modules/FindVampHostSDK.cmake
>  )
There is no CMake build system upstream. That CMakeLists.txt I linked before is in the vcpkg port.

2021-09-04 21:03 UTC, cannam commented on cmake-modules/FindVampHostSDK.cmake
>  )
> However, there is another issue with the package because it uses the same library file name `vamp-sdk` on all OSes, but the upstream library uses `VampHostSDK` on Windows [...] @cannam do you have any comment on this? Are the different file names for the Vamp libraries with the Visual Studio project file versus autotools intentional?

Yes, I think so. At the time (c. 2006) at least, Windows developers generally expected to see `ThisKindOfThing.dll` while on Linux we had `libthis-kind-of-thing.so` (and I guess the Mac was similar). With totally separate build systems for Win and Unix (inevitable at the time) using identical library names would have been a bit uncomfortable on one platform or the other.

> Would you consider changing this upstream so the file names are the same on each OS?

It's not impossible of course, but the library is more or less in maintenance mode until anything urgent comes along, and I don't think changing the library name (breaking any existing users who rely on current behaviour) really counts. Better to work with it.

2021-09-05 00:18 UTC, Be-ing commented on cmake-modules/FindVampHostSDK.cmake
>  )
Thanks for your input @cannam. I agree that the downsides of changing the file name for an old library probably outweigh the minor benefit of having a consistent name on each OS.

So the vcpkg port has two bugs, first adding the `d` suffix for debug builds and second having a different filename from the upstream build system on Windows.

2021-09-05 00:54 UTC, emabrey commented
> 
> 
> This introduces complexity into Tenacity's build system to hack around a bug in the package. We can fix the package instead.

That's called a workaround.

2021-09-05 00:59 UTC, Be-ing commented
Please test #584 with a debug build on Windows. If it works, let's merge that instead.

2021-09-05 01:13 UTC, emabrey commented
> 
> 
> Please test #584 with a debug build on Windows. If it works, let's merge that instead.

Your commit message starts with a lowercase letter.

> 
> 
> I was referring to this commit:
> 
> > Disable VAMP plugins on Alpine CI
> 
> It should be Vamp

I misunderstood.

2021-09-05 04:01 UTC, emabrey commented
> 
> 
> Please test #584 with a debug build on Windows. If it works, let's merge that instead.

It does not work. I vote we go ahead and merge this fix since it already works.

2021-09-05 04:20 UTC, emabrey commented on cmake-modules/FindVampHostSDK.cmake
>  )
> 
> 
> There is no CMake build system upstream. That CMakeLists.txt I linked before is in the vcpkg port.

That isn't what I meant. I think I remember seeing a fork of the project that included CMake files instead of autoconf/buildtools stuff. I was just clarifying I used the upstream version.

2021-09-05 04:22 UTC, emabrey commented
> 
> 
> I was referring to this commit:
> 
> > Disable VAMP plugins on Alpine CI
> 
> It should be Vamp

Done.

2021-09-06 07:49 UTC, closed without merging