Update tenacity.desktop.in
tenacityteam/tenacity-legacy pull request #594
Opened 2021-09-08 08:32 UTC by EsmailELBoBDev2

Some of users (including me) whenever we try to run the app we get `tenacity: error while loading shared libraries: libwx_baseu-3.1.so.4: cannot open shared object file: No such file or directory` then i saw https://aur.archlinux.org/packages/tenacity-git#comment-823016 and it works for me and i just wanted to make it included by defualt instead of being edited each time i update the app

2021-09-08 08:37 UTC, leio requested changes

2021-09-08 08:37 UTC, leio commented on src/tenacity.desktop.in
> +Exec=env UBUNTU_MENUPROXY=0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/wxgtk-dev/lib/ @AUDACITY_NAME@ %F
This just workarounds a linking problem for specific environments, in a way that affects all other environments too that don't need it. LD_LIBRARY_PATH shouldn't be set in some desktop file like that, especially not hardcoded to a specific path that will need to be different on different systems and not needed at all on system installs of wxWidgets.

We need to address the underlying issue instead.

2021-09-08 08:39 UTC, leio commented on src/tenacity.desktop.in
> +Exec=env UBUNTU_MENUPROXY=0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/wxgtk-dev/lib/ @AUDACITY_NAME@ %F
That issue may very well be a packaging issue, of wxgtk3-dev-opt in particular. I'm not sure why that `opt` suffixed package is being used there, which puts wxWidgets libraries in a non-standard location, yet doesn't seem to add it to library search path (/etc/ld.so.conf.d)

2021-09-08 12:06 UTC, solfisher commented
Hi! Please [read the contributing guidelines](https://git.sr.ht/~tenacity/tenacity/tree/master/item/CONTRIBUTING.md) and use the pull request template when making a contribution.

2021-09-08 13:14 UTC, Be-ing commented on src/tenacity.desktop.in
> +Exec=env UBUNTU_MENUPROXY=0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/wxgtk-dev/lib/ @AUDACITY_NAME@ %F
That is definitely a packaging issue and not our responsibility.

2021-09-08 13:54 UTC, panos commented
> Use the pull request template when making a contribution.

Adding to the thing @solfisher said, you'll have to `--signoff` your commit. I hope that we were helpful enough, do let us know if you have any questions. Thanks for helping us out!

2021-09-08 15:12 UTC, caughtquick commented on src/tenacity.desktop.in
> +Exec=env UBUNTU_MENUPROXY=0 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/wxgtk-dev/lib/ @AUDACITY_NAME@ %F
Yep, haven't we clearly said not to package tenacity yet. At this point implementing hacky workarounds to help with unofficial packing isn't worth it.

2021-09-08 18:02 UTC, closed without merging

2021-09-09 13:06 UTC, juozaspo commented
Do not try to arbitrary change the `LD_LIBRARY_PATH` variable to to specific value, you might not always be successful in every configuration. Instead use `ldconfig` tool as root to update `/etc/ld.so.cache` file, at least on Ubuntu based distributions, first add your path to `/etc/ld.so.conf` (or `/etc/ld.so.conf.d/` if it exists and `/etc/ld.so.conf` is configured to include `*.conf` from this directory) then run the tool. More details in [How to set the environmental variable LD_LIBRARY_PATH in linux](https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux) StackOverflow page, it greatly explains that. If you install library to standard location, you would still have to run `ldconfig` in some cases, so don't forget to do that.