Replace every Audacity reference with Tenacity
tenacityteam/tenacity-legacy pull request #632
Opened 2021-09-16 19:32 UTC by Mondanzo

Removes all mentions of Audacity from the MacOS Manifest filey

Signed-off-by: Mondanzo <danzo@mondanzo.de>

Resolves: #618 

Replaces all mentions of Audacity with Tenacity in the MacOS Manifest file.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-09-16 20:06 UTC, panos approved these changes
Approving reluctantly.

2021-09-16 20:06 UTC, panos commented on cmake-proxies/cmake-modules/MacOSXBundleInfo.plist.in
> +				<string>application/x-tenacity-project</string>
Not completely sure if this will be a breaking change.

2021-09-17 10:42 UTC, solfisher commented on cmake-proxies/cmake-modules/MacOSXBundleInfo.plist.in
> +				<string>application/x-tenacity-project</string>
`.aup3` is not a Tenacity project file. It's just that Tenacity uses the Audacity project file extension. NACK

2021-09-17 12:32 UTC, panos requested changes
As per @solfisher.

2021-09-17 12:34 UTC, panos approved these changes, later dismissed

2021-09-17 12:35 UTC, panos commented
We'll discuss the MIME type association a bit further internally, but this should be good to go for now.

2021-09-17 12:42 UTC, solfisher commented
Make sure to squash when merging, or just fixup the two commits.

2021-09-17 12:44 UTC, solfisher requested changes
Oh, and the commit should mention macOS in its title.

2021-09-18 10:10 UTC, solfisher commented
Something happened with the tree; duped diffs and an empty merge commit. Should be fixed now.

2021-09-18 22:14 UTC, panos commented
Considering that it's been over 12 hours and the issue you brought up has been resolved, can we merge this?

2021-09-19 05:05 UTC, solfisher commented
As long as it's been tested on macOS, sure.

2021-09-19 07:56 UTC, panos commented
Successfully tested on Catalina.

2021-09-19 07:57 UTC, merged