[POC] Make Git a mandatory build dependency
tenacityteam/tenacity-legacy pull request #636
Opened 2021-09-19 17:31 UTC by panos

We are planning to use Git to detect the current version of Tenacity, instead
of depending on a hardcoded variable, as that is an approach that is far from
foolproof. We already depended on it for Windows and macOS builds, as vcpkg
uses Git to fetch a couple of dependencies. The vcpkg has also been
appropriately adjusted and cleaned up.

It may seem a bit excessive, but the operating systems we support all have
a version of Git that is available and it is not a runtime dependency. We
assume that people who can gain access to the source code can also install
a copy of Git. If we actually come across some sort of an extreme edge case
where this is not true, we can set the versions to `9999` just like in
`win/tenacity.rc`, in order to ensure portability, at a later point in time.

This change is a measure that will ensure that we are going to avoid mistakes
that we will not be able to undo later.

For more context: See this [comments section](https://github.com/tenacityteam/tenacity/commit/dbe4b564d45a921b136b8b289a0769649b8035b0)

*(short description of the changes and the motivation to make the changes)*

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

</details>

P.S. I fully understand that this isn't how other projects do it and how this proposal can be very controversial. We should also consider the goal to offer reproducible builds and whether this change will compromise it. Feel free to throw it out if it's not needed.

2021-09-19 17:33 UTC, panos commented
The commit description pretty much brings up the pros of including something like this in the code, but that's not a hill I would die on. Truth be told, I am very skeptical as to whether we actually want to head towards that direction.

2021-09-19 18:04 UTC, leio commented
I'm strongly against this, as it means we can't ship tarballs cleanly, which means downstreams can't consume this without hoops (like packing up the git tag with git folder included for the tag looking command to succeed), which means they might not package us. It also very unconventional and controversial.

In the open source world I do see pushes towards not creating tarballs, but these pushes are for equalizing certain format tags to mean a release and everything else would be taken over by automation. Be it just stable tarballs (that do NOT change checksum even after a decade or more) generated by the git hosting, or tooling that picks up the tag and does the tarball generation and pushing out into mirroring system automatically. They all still would put the version number in the build system and make a stable tarball available in one way or another for downstream consumption.

However, it IS typical to check if git is available and the source tree is from git, and then suffix the short hash into the version string for displaying in the about dialog and/or elsewhere. Then your version will be a concrete `major.minor.nano` from tarballs, and a `major.minor.nano-<hash>` or similar when built from git, which will show the exact commit it is from. Some projects will increase the version number right before release (so the hash including versions can be taken to mean a commit after the noted release), some right after the release (so the hash shows a pre-release). Some also do both (so odd numbered nano version is from development git).

So that's basically (I think, I haven't followed closely) for what we seem to want to do, except instead of git tag parsing, it takes it from the version claimed in the build system.

There may be ways to make it work, involving dist scripts that take the git tag at tarball generation time and drop in a file into the tarball that tells the version, and the build system first checks for such a file and then uses the version claimed there, instead of trying to find some git tags, but that will then mean that snapshot tarballs (not going through dist scripts) would be broken for versioning still and more mess than I think it's worth it. Raising the version number in a single place in the toplevel build file is just one out of many things in a release checklist that is went through one by one for an official release.

2021-09-19 18:16 UTC, panos commented
Maybe the best way to deal with this could be a checklist instead.

2021-09-19 19:44 UTC, flewkey commented
If this gets merged, Gentoo packagers will probably patch the build system and continue to use tarballs.
https://devmanual.gentoo.org/ebuild-writing/functions/src_unpack/vcs-sources/index.html

2021-09-20 01:08 UTC, Be-ing requested changes
I agree with @leio. This is not a good approach to versioning releases. The version number should be in the release tarball without needing to clone the whole Git repo, which is excessively large to download for just distributing a release (especially because it contains nearly 2 million lines of vendored library code that I deleted in the history). There are a handful of ways to approach this. I propose to use `git describe` as the single source of truth about the version rather than maintaining error prone redundant information in Git tags and a number hardcoded in the build system. For release tarballs the `git describe` output can be put into an autogenerated file. Git [has a tool](https://git-scm.com/docs/gitattributes#_export_subst) which may help for that.

2021-09-20 06:32 UTC, panos commented
Got it, going to check out how this could be done differently.

2021-09-20 06:32 UTC, closed without merging

2021-09-20 06:33 UTC, solfisher commented
I also think that this is a bad idea. For some reason I totally forgot about how packaging works, despite maintaining a couple myself.

What I worry about is human error. If we can make a pre-tag hook that changes this, or better, *reminds us to change it ourselves*, then I'm fine with the variables being there.

2021-09-20 07:09 UTC, panos commented
> If this gets merged, Gentoo packagers will probably patch the build system and continue to use tarballs.
> https://devmanual.gentoo.org/ebuild-writing/functions/src_unpack/vcs-sources/index.html

Our goal is to help packagers as much as humanly possible. Horrible idea, indeed.

> What I worry about is human error. If we can make a pre-tag hook that changes this, or better, *reminds us to change it ourselves*, then I'm fine with the variables being there.

Well, at least we now have the variables back. The next steps are "integrating" them and figuring out how this cannot happen at a later point.

2021-09-27 18:18 UTC, eli-schwartz commented
> For release tarballs the `git describe` output can be put into an autogenerated file. Git [has a tool](https://git-scm.com/docs/gitattributes#_export_subst) which may help for that.

In very recent versions of git, my proposal to add an export-subst replacement for `%(describe:match=*)` is implemented, which means this tool is not limited to only being useful for release tags.