Rename desktop and mime info file to reverse DNS schema
tenacityteam/tenacity-legacy pull request #642
Opened 2021-09-24 07:08 UTC by lmarz

Signed-off-by: Leon Marz <main@lmarz.org>

Resolves: #553

Rename the files `src/tenacity.desktop.in` and `src/tenacity.xml` to the reverse DNS schema.
The mime info file `src/tenacity.xml` doesn't really have a file naming convention but I also renamed it for consistency within the freedesktop.org ecosystem.
@TheEvilSkeleton Are there more files that need to be renamed?

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-09-24 08:04 UTC, panos commented
Seems fine to me, but leaving the review up to @TheEvilSkeleton.

2021-09-24 12:36 UTC, TheEvilSkeleton requested changes
Can you change the path https://github.com/tenacityteam/tenacity/blob/e776c2f7e41cad437edf6385fa42377fe4e21030/packaging/flatpak/org.tenacity.Tenacity.json#L192 too?

2021-09-24 13:59 UTC, lmarz commented
I think this is what you meant, right?

2021-09-24 14:00 UTC, TheEvilSkeleton submitted a review, later dismissed
@lmarz yup, and I'm glad you noticed https://github.com/tenacityteam/tenacity/pull/642/files#diff-3aa1fa18fa1bebf563017c0fffdf4c058f97aa882b25e9403bc5db82aac1c048R212 because I forgot to link it.

2021-09-24 15:24 UTC, panos approved these changes, later dismissed
Looks good to me as well.

2021-09-24 16:42 UTC, Be-ing commented on packaging/flatpak/org.tenacity.Tenacity.json
> +  "rename-appdata-file": "org.tenacityaudio.Tenacity.metainfo.xml",
Is this line needed at all anymore?

2021-09-24 16:42 UTC, Be-ing commented on packaging/flatpak/org.tenacity.Tenacity.json
> +        "install -Dm644 ../help/org.tenacityaudio.Tenacity.metainfo.xml -t /app/share/metainfo",
CMake should take care of this if it doesn't already.

2021-09-24 16:43 UTC, Be-ing commented
Thanks for working on this.

2021-09-24 19:32 UTC, TheEvilSkeleton commented on packaging/flatpak/org.tenacity.Tenacity.json
> +  "rename-appdata-file": "org.tenacityaudio.Tenacity.metainfo.xml",
Nope.

2021-09-25 07:12 UTC, lmarz commented on packaging/flatpak/org.tenacity.Tenacity.json
> +        "install -Dm644 ../help/org.tenacityaudio.Tenacity.metainfo.xml -t /app/share/metainfo",
I think I need your or someones help with this. I don't really know CMake

2021-09-26 15:12 UTC, solfisher approved these changes
LGTM as well.

2021-09-26 15:44 UTC, TheEvilSkeleton approved these changes

2021-09-27 02:00 UTC, Be-ing commented on packaging/flatpak/org.tenacity.Tenacity.json
> +        "install -Dm644 ../help/org.tenacityaudio.Tenacity.metainfo.xml -t /app/share/metainfo",
Okay, that can be done in another PR.

2021-09-27 02:00 UTC, Be-ing approved these changes

2021-09-27 05:49 UTC, merged

2021-09-27 05:51 UTC, panos commented
Merged as it's been approved by two reviewers that are a part of our organization, while counting in @TheEvilSkeleton's review in the "time before the change should be merged" rule, as I believe that they are highly trustworthy as far as these sorts of changes are concerned and I originally tasked them with reviewing this proposed change in the first place.

2021-09-27 06:36 UTC, emabrey commented
This broke flatpak packaging.

2021-09-27 06:42 UTC, emabrey commented
I think line 7 of the flatpak manifest might be the problem:

```
 "rename-desktop-file": "tenacity.desktop",
 ```

2021-09-27 09:53 UTC, TheEvilSkeleton commented
Thanks for pointing it out.

2021-09-27 15:08 UTC, Semisol commented
I recommend that a new issue or PR is created for the tracking of the bug.

2021-09-27 15:09 UTC, TheEvilSkeleton commented
@Semisol we already took care of it https://github.com/tenacityteam/tenacity/commit/fe5b64a1c2c1990b4c3f863948113e55503d73be.

2021-09-27 15:10 UTC, Semisol commented
Okay, then we should be fine.

2021-09-27 15:42 UTC, panos commented
> I think line 7 of the flatpak manifest might be the problem:
> 
> ```
>  "rename-desktop-file": "tenacity.desktop",
> ```

I seriously wonder how this actually went past us, all of the 11 checks seem to have passed at the time when I merged this!

Does this warrant further investigation?

2021-09-27 16:14 UTC, Semisol commented
> I seriously wonder how this actually went past us, all of the 11 checks seem to have passed at the time when I merged this!

There was no Flatpak check running

2021-09-27 16:15 UTC, emabrey commented
> 
> 
> > I think line 7 of the flatpak manifest might be the problem:
> > ```
> >  "rename-desktop-file": "tenacity.desktop",
> > ```
> 
> I seriously wonder how this actually went past us, all of the 11 checks seem to have passed at the time when I merged this!
> 
> Does this warrant further investigation?

The flatpak run takes so long that you have to manually activate it on a PR.

2021-09-27 16:29 UTC, panos commented
> There was no Flatpak check running

> The flatpak run takes so long that you have to manually activate it on a PR.

Goddang it!