CMAKE `GIT_DESCRIBE` fix
tenacityteam/tenacity-legacy pull request #646
Opened 2021-09-27 05:12 UTC by emabrey

Resolves: https://github.com/tenacityteam/tenacity/issues/640
Related to https://github.com/tenacityteam/tenacity/pull/644 

Additionally, this undoes the accidental changes in dbe4b564d45a921b136b8b289a0769649b8035b0 . I think we should revert those changes related to the creation of new version variables that co-exist alongside the `AUDACITY_` version variables. Any replacement of the `AUDACITY_` varaibles also needs to make a mirrored change to the defines in the C++ codebase that share the same names as the CMake variables.

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-09-27 05:35 UTC, panos requested changes

2021-09-27 05:35 UTC, panos commented on CMakeLists.txt
> -set( TENACITY_RELEASE 1 ) # Minor version
Why should we remove this? Our own tags will overwrite the AUDACITY_VERSION as set earlier, and this will mess up migration code.

We've got many references to the old Audacity version that include the Audacity variables, like in Nyquist, the ExportMP3, or `scripts/maketarball.sh`. The number has to be "stable" and it should be ours. Not introducing edge cases "wow, the user does not have Git so we might as well revert everything to the Audacity version that Tenacity is based on" when there is no need to do so! That's the unintended behavior that this change is going to cause. I'm extraordinarily concerned because I don't think that there's a reason to remove something that's part of our rebranding -- it may even make Git an implicit dependency, which is something that we absolutely want to avoid. Many operating systems, like Gentoo, Haiku, and others, for example, build packages in a sandbox, after all.

2021-09-27 05:38 UTC, panos commented
Also, in any case, it'd be good to include the original contributor who started working on this as a co-contributor.

By the way, including characters as I previously suggested seems to be a horrible idea. Parts of the code like these assume that the version is going to be an integer and perform math/bitwise operations using them.

Example:
https://github.com/tenacityteam/tenacity/blob/cc24305ec973eeacec6cbaf56a01a074fc5b1787/src/effects/VST/VSTEffect.cpp#L959

2021-09-27 05:41 UTC, emabrey commented on CMakeLists.txt
> -set( TENACITY_RELEASE 1 ) # Minor version
Because there is no reason to avoid updating the AUDACITY_ version variables? You seem to have assumed that it needs to be different but I can't see why. Why do we need two different version schemes and how could that ever be better?

2021-09-27 05:52 UTC, emabrey commented on CMakeLists.txt
> -set( TENACITY_RELEASE 1 ) # Minor version
Also, it isn't appropriate to merge things incorrectly without review on the basis of it being an unimportant and inconsequential change only to swap immediately to saying it's removal will be doom and gloom. Either it's a critical project wide change that needs proper discussion and review, in which case it should be reverted, or it's an inconsequential complication, in which case it should be reverted. You unilaterally changed the proper method to determine what the answer to "what is the version of the project" is and it's going to create havoc down the line if people rely on these two different version schema inconsistently. Since nobody has started using the TENACITY_ prefixed version variables yet we can still get away with reverting it and coming to a complete determination of what needs to be changed to allow us to actually do this change you have proposed.

2021-09-27 11:35 UTC, juozaspo commented on CMakeLists.txt
> +      COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=7 --exclude=DarkAudacity-*
Watch out for unexpected behavior with no quotes syntax on unix platforms, as described in https://github.com/tenacityteam/tenacity/pull/644#issuecomment-927732450 by @leio, double quotes works better both on windows and linux so far.
> No quotes at all doesn't work correct on any linux shells, IF it goes through the shell at all with cmake. Run `touch -- --match=foo.bar.baz` and enjoy the havoc. However, I don't know if it gets interpreted by a shell or not, as I don't know what cmake does there.
> 
> I personally strongly believe that we shouldn't be looking at tags at all, as I expressed in #636, but rather it should just show the version number written out in toplevel build system file, and if building from git, suffix the current commits short hash after it. With meson this would be done via https://mesonbuild.com/Reference-manual.html#vcs_tag

2021-09-28 19:34 UTC, emabrey commented on CMakeLists.txt
> +      COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=7 --exclude=DarkAudacity-*
Is there actually unexpected behavior or are you just warning me generally? I looked through the CI runs and didn't see any problems.

2021-09-28 19:40 UTC, emabrey commented on CMakeLists.txt
> +      COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=7 --exclude=DarkAudacity-*
I added the quotes just to be safe and since I believe on Github CI it actually does matter

2021-09-28 20:04 UTC, juozaspo commented on CMakeLists.txt
> +      COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=7 --exclude=DarkAudacity-*
Nothing wrong about pr itself, just make sure everything's quoted where needed, also avoiding situations where such files (e.g. named `--match=some.badfile.txt`) would cause problems.

2021-09-28 21:16 UTC, panos commented on CMakeLists.txt
> -set( TENACITY_RELEASE 1 ) # Minor version
Here's a list of things that have to be changed: https://github.com/tenacityteam/tenacity/search?q=AUDACITY_VERSION

I put out my own solution, do you have anything else to propose in return instead of overriding the simple first step to my solution, or would it be a better idea to move on with it? We already decided on the versioning scheme a long time ago and the fact that we are refusing to finally put our money where our mouth is is precisely what's confusing packagers.

2021-09-28 21:25 UTC, panos commented on CMakeLists.txt
> -set( TENACITY_RELEASE 1 ) # Minor version
I'm requesting a further review from @leio, @solfisher and @Be-ing. We need to resolve this, it's been far too long and I've already had to tell people across 4 different distributions "hey, we are actually going to release 0.1.0", because that's what we decided on. My method for doing this may not have been approved, but by not introducing something better, we're just going back to the part where we did not do anything about it. Nothing (as in, nothing) is worse, in my opinion, and we need to head forward. I'm really not sure what's up with the fixation of having to absolutely invalidate anything just so that we can just re-merge the exact same thing 3 days later. It's a waste of our time.

Undoing this after a discussion about what happened with the people that initially made the change is just as consequential and two wrongs don't make one right. Please create a new issue, let's all express our takes and *hopefully* come up with better solutions than having two schemes, instead of trying to undo this through a change that's completely irrelevant in a low-key manner after saying that "we need to fix this in order for another pull request to be merged". Me waiting for that discussion to happen is why exactly I haven't proceeded with making any further proposed changes that replace the `AUDACITY_` variables to `TENACITY_` variables. But seriously, we can't keep being `3.0.4` for that long!

2021-09-28 21:32 UTC, panos commented
Okay, so, getting back on track: As said here, https://github.com/tenacityteam/tenacity/pull/646#discussion_r717975880 and as suggested by @emabrey, it is a good idea not to have two versioning schemes, and the only reason why that was kept there is because I was unaware as to whether anything would break. I appealed to code regarding "migrating old project files" multiple times, but I could not find any such cases in the codebase where changing the version back to something minor would affect such code. I was specifically careful about not making my change "breaking", so, I remain very concerned as to whether I've missed out on something.

2021-09-28 22:16 UTC, panos commented
Migration code: https://github.com/audacity/audacity/blob/master/src/ProjectFileIO.cpp#L685

That's going to be a problem.

2021-09-28 23:41 UTC, panos approved these changes
Approved. Let's see how we're going to deal with file versions and our own versioning system at a later PR.

2021-09-29 07:32 UTC, leio approved these changes
I fundamentally disagree with the whole approach of calling `git describe` in the first place, as this is simply not a clean way to do it in practice, and I don't know any other projects than audacity and tenacity that do it to this level. Most just add the commit hash after the version number that comes from the build system, as that version needs to be updated for fallback just before release ANYWAYS. So they don't build fragile things on top of it just to avoid wrong version number when git is used for building and someone forgot to increase the version number while tagging a release as per requirement in a release checklist. The "fallback" is going to be used in practice by almost all downstream linux packages and HAS to be right anyways.

However, because this fixes issues in an already fragile thing, I approve it. Later imo it should just all go away instead.

2021-09-29 07:36 UTC, panos commented
One step at a time. ;D

2021-09-29 19:59 UTC, merged