Update README.md
tenacityteam/tenacity-legacy pull request #660
Opened 2021-10-09 16:09 UTC by n0toose

Resolves: #658

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-10-09 16:14 UTC, panos commented
@solfisher, sr.ht builds = broken again

2021-10-09 16:46 UTC, solfisher commented
That's a weird-looking issue, is this a one-off or recurring?

2021-10-09 20:43 UTC, unbeatable-101 requested changes

2021-10-09 20:43 UTC, unbeatable-101 commented on README.md
> +You can help us translate Tenacity and make it more accessible to the people that also speak your language on [Weblate](https://hosted.weblate.org/projects/tenacity).
```suggestion
You can help us translate Tenacity and make it more accessible on [Weblate](https://hosted.weblate.org/projects/tenacity).
```
`to the people that also speak your language` seems clunky to me

2021-10-09 20:43 UTC, unbeatable-101 commented on README.md
> +### Translations
```suggestion
### Translating
```
Maybe say `Translating` here instead? Sounds better to me, what do others think?

2021-10-09 20:43 UTC, unbeatable-101 commented on README.md
> +We have not released the first version of Tenacity yet, as it is still in early stages of development.
```suggestion
We have not released the first version of Tenacity yet, as it is still in the early stages of development.
```

2021-10-09 23:41 UTC, n0toose commented on README.md
> +We have not released the first version of Tenacity yet, as it is still in early stages of development.
*the* early stages? Sounds slightly dramatic to me when read out loud.

2021-10-09 23:43 UTC, panos commented
> That's a weird-looking issue, is this a one-off or recurring?

One-off, apparently you're not forced to use the template if you generate issues out of Discussions on GitHub. The Discussion contains more than enough context, however.

2021-10-09 23:47 UTC, unbeatable-101 commented on README.md
> +We have not released the first version of Tenacity yet, as it is still in early stages of development.
¯\\_(ツ)_/¯, just sounds better to me

2021-10-10 01:47 UTC, jgamble commented on README.md
> +We have not released the first version of Tenacity yet, as it is still in early stages of development.
American English speaker here; it sounds very weird without the "the" to me.

2021-10-11 12:38 UTC, unbeatable-101 submitted a review, later dismissed

2021-10-11 14:36 UTC, TheEvilSkeleton commented on README.md
> +- [Nightly Downloads](https://tenacityaudio.org/very-early-builds)
Thoughts about adding my Flatpak nightly builds? https://github.com/TheEvilSkeleton/tenacity-flatpak-nightly

Or even better, the repo can be forked in this organization and then linked in the README.

2021-10-12 07:34 UTC, n0toose commented on README.md
> +- [Nightly Downloads](https://tenacityaudio.org/very-early-builds)
I forgot about this, but yeah, I can do that (and will invite you as external contributor/admin for the repo, I can also invite you in the organization itself for easier management reasons)

2021-10-12 07:35 UTC, n0toose commented on README.md
> +- [Nightly Downloads](https://tenacityaudio.org/very-early-builds)
I did that temporarily, but I'm starting to think that it'd be a better idea to transfer the repository in order to preserve stars + redirect to the new repository.

2021-10-12 11:46 UTC, TheEvilSkeleton commented on README.md
> +- [Nightly Downloads](https://tenacityaudio.org/very-early-builds)
If you prefer transferring, then that could work.

2021-10-17 17:05 UTC, TheEvilSkeleton requested changes

2021-10-17 17:05 UTC, TheEvilSkeleton commented on README.md
> +- [Nightly Downloads](https://tenacityaudio.org/very-early-builds)
Since we transferred the repo today, we can add the Nightly builds repo.
```suggestion
- [Nightly Downloads](https://tenacityaudio.org/very-early-builds)
- [Nightly Flatpak builds](https://github.com/tenacityteam/tenacity-flatpak-nightly/blob/main/README.md)
```

2021-10-18 09:14 UTC, merged