Add Void Linux build instructions
tenacityteam/tenacity-legacy pull request #661
Opened 2021-10-10 17:19 UTC by maciejla

Signed-off-by: Maciej <git@maciej.website>

Added dependencies and notes for building on Void Linux

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [ ] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2021-10-10 17:23 UTC, nbsp requested changes

2021-10-10 17:23 UTC, nbsp commented on BUILDING.md
> +If you need these features, it's recommended to build them from source.
Maybe link to the source or to some documentation?

2021-10-10 17:23 UTC, nbsp commented on BUILDING.md
> +If you do so, you will need to set `WX_CONFIG` environment variable:
nitpick

```suggestion
If you do so, you will need to set the `WX_CONFIG` environment variable:
```

2021-10-10 17:23 UTC, nbsp commented on BUILDING.md
> +for how to install it from source code, or see the [previous section](#wxwidgets-from-source).
Would it make sense to list wx3.1's build dependencies here?

2021-10-10 20:08 UTC, maciejla commented on BUILDING.md
> +If you need these features, it's recommended to build them from source.
I don't know what I should link to, I just wasn't able to find these packages in void linux repo

2021-10-10 20:09 UTC, maciejla commented on BUILDING.md
> +for how to install it from source code, or see the [previous section](#wxwidgets-from-source).
Probably yes, I'll do that

2021-10-19 10:25 UTC, panos commented
Hi, just circling back to this, thank you so much for working on this once again. Do you plan to finish this anytime soon and if not, should another person try and take over from here (we're all fairly busy, so it'll take a while either way)?

2021-10-24 15:36 UTC, maciejla commented
> Hi, just circling back to this, thank you so much for working on this once again. Do you plan to finish this anytime soon and if not, should another person try and take over from here (we're all fairly busy, so it'll take a while either way)?

Hi, unfortunately I don't have much time right now :( I'll try to finish this in a reasonable time, but if someone wants to take over, feel free to do it :)

2022-06-15 21:06 UTC, closed without merging