Improve .desktop file
tenacityteam/tenacity-legacy pull request #694
Opened 2022-01-26 03:37 UTC by n0toose

- Add keywords
- Add StartupWMClass, mostly useful for Flatpak
- Add additional 'midi' category
- Improve Phosh support

This should improve Flatpak support. (CC: @TheEvilSkeleton)

<details>
<summary>Checklist</summary>

- [x] I have signed off my commits using `-s` or `Signed-off-by`\* (See: [Contributing § DCO](https://github.com/tenacityteam/tenacity/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code\*
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving\*
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"\*

\* indicates required

</details>

2022-01-26 05:11 UTC, TheEvilSkeleton requested changes

2022-01-26 05:11 UTC, TheEvilSkeleton commented on src/org.tenacityaudio.Tenacity.desktop.in
> +Categories=AudioVideo;Audio;AudioVideoEditing;Midi;
I suggest adding `Recorder` too since it records audio.
```suggestion
Categories=AudioVideo;Audio;AudioVideoEditing;Midi;Recorder;
```

2022-01-26 05:11 UTC, TheEvilSkeleton commented on src/org.tenacityaudio.Tenacity.desktop.in
> +X-Purism-FormFactor=Workstation;
https://aplazas.pages.gitlab.gnome.org/blog/blog/2020/10/15/specify-form-factors-in-your-librem-5-apps.html
```suggestion
```

This is not needed:
> To make your application appear in Phosh, add the following lines to your desktop entry:

Not having this line defaults to `Workstation`, therefore it is redundant.

2022-01-26 13:41 UTC, TheEvilSkeleton requested changes

2022-01-26 13:41 UTC, TheEvilSkeleton commented on src/org.tenacityaudio.Tenacity.desktop.in
> +X-Purism-FormFactor=Workstation;
This can be entirely removed.
```suggestion
```

2022-01-26 17:06 UTC, n0toose commented on src/org.tenacityaudio.Tenacity.desktop.in
> +X-Purism-FormFactor=Workstation;
Oh, oof, left that one out.

2022-01-26 17:08 UTC, TheEvilSkeleton approved these changes

2022-01-26 21:06 UTC, caughtquick approved these changes
Looks good

2022-01-26 23:43 UTC, merged

2022-01-27 17:16 UTC, n0toose commented
for future reference: be aware of github's ways of manipulating commit messages (reference to pull request that doesn't work on other platforms or on offline copies and that it added `Co-authored-by:` twice)